### ISSUE TITLE
ggtheme does not affect risk.table

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#1]
I am testing your package, since `survMisc` with great `survMisc:::autoplot.survfit` has been removed from  CRAN and I occure a funny bug that `ggtheme`  parameter does not affect `risk.table` and the outputed plot looks ridiculous

````{R}
library(survminer)
library(ggthemes)
ggsurvplot(survfit(Surv(times, patient.vital_status)~dataset,
									 data = BRCAOV.survInfo),
					 #pval = TRUE, conf.int = TRUE,
					 risk.table = TRUE,
					 ggtheme = theme_bw(base_size = 24, base_family = "serif") ,
					 break.time.by = 800,
					 palette = c("#FF9E29", "#86AA00"))
````

![survminer](https://cloud.githubusercontent.com/assets/6773454/12948834/dd4d6fa4-d004-11e5-927d-437c67178eab.png)

I think changes should be done in those lines of `ggsurvplot` https://github.com/kassambara/survminer/blob/master/R/ggsurvplot.R#L338-L343

**Comment by kassambara** [comment]
This bug has been fixed in the latest version of survminer (on Github).

Thank you for your comments,
A. Kassambara

**Comment by MarcinKosinski** [comment]
Thanks. Looks great right now.
