### ISSUE TITLE
Next package publication to CRAN

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#10]
Are you planning to publish updated version to CRAN?

**Comment by kassambara** [comment]
Yes, the submission to CRAN is intended for friday!

**Comment by MarcinKosinski** [comment]
Great!

2016-02-17 18:56 GMT+01:00 Alboukadel KASSAMBARA <notifications@github.com>:

**Comment by kassambara** [comment]
survminer 0.2.0 is availabale on cran now.

**Comment by MarcinKosinski** [comment]
Great, good to hear that!

Marcin Kosinski

Dnia 19.02.2016 o godz. 16:58 Alboukadel KASSAMBARA <notifications@github.com> napisał(a):
