### ISSUE TITLE
Percents on OY axis

### ISSUE THREAD

**Issue by pbiecek** [kassambara/survminer#112]
Would you consider an argument that will format values in the OY axis to have percents instead of fractions?

Right now the OY axis have values like 0, 0.25, 0.5, 0.75, 1. It may be nicer to have 0, 25%, 50%, 75%, 100%

Actually it is enough to add  `+ scale_y_continuous(labels = scales::percent)` to the ggplot

**Comment by kassambara** [comment]
Hi,

The argument `surv.scale`might be what you need.

Please try this:

```r
library(survival)
library(survminer)

fit<- survfit(Surv(time, status) ~ sex, data = lung)

ggsurvplot(fit, surv.scale = "percent")

# Or use this
ggsurvplot(fit, fun = "pct")
```

**Comment by kassambara** [comment]
Hi @pbiecek,

Please, let me know if it's ok, so that we can close this issue....

**Comment by pbiecek** [comment]
Thanks!
