### ISSUE TITLE
Suggestion: ggcoxfunctional works with coxph object not formulas

### ISSUE THREAD

**Issue by pbiecek** [kassambara/survminer#115]
Would you consider a change in the design of ggcoxfunctional() function?

Right now it takes the formula and data, and is calling coxph function internally.
But it may be more flexible to separate the modelling and variable diagnostic.

The suggestion is to send an argument 'fit' instead of formula and data objects,
you can extract both formula and data from the 'fitobject'.

It will be also consistent with `ggcoxzph`, `ggcoxdiagnostics` and `ggsurvplot` functions.

**Comment by MarcinKosinski** [comment]
Thanks for the suggestion.
I did not realize this inconsistency.

**Comment by kassambara** [comment]
The design of the `ggcoxfunctional()`is now consistent with the other functions.

```r
library(survival)
fit <- coxph( Surv(futime, death) ~ mspike + log(mspike) + I(mspike^2) +
                     age + I(log(age)^2) + I(sqrt(age)), data = mgus)

library(survminer)
ggcoxfunctional(fit)
```

**Comment by pbiecek** [comment]
Great!
