### ISSUE TITLE
idea: cumulative distribution for censorings

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#116]
Came from this comment http://disq.us/p/1fa6f7p by @pbiecek

**Comment by kassambara** [comment]
Cumulative distribution for censorings

**Comment by pbiecek** [comment]
Hi, are you working on this? 
If not, I can add a function that creates either CIC like curves or normalized curves similar to these created with cdplot() function (I found this useful to see where censorings are more often).

**Comment by kassambara** [comment]
Hi @pbiecek,

I'm not working on it, so let's go for your suggestion!

**Comment by pbiecek** [comment]
Candidate solution is in #149 

Below I copy the quick overview
The `ggsurvevents` function calculates and plots distribution for events (both status=0 and status1),
with `type` parameter one can plot cumulative distribution of locally smooth density,
with `normalised` distributions are normalised.

This function helps to notice when censorings are more common

a nice example is for `colon` dataset, here censorings occur mostly after 6'th year

<img width="701" alt="screen shot 2017-02-12 at 20 24 53" src="https://cloud.githubusercontent.com/assets/4624318/22865305/7ce96a80-f161-11e6-9445-30b63e495425.png">

**Comment by kassambara** [comment]
Looks great!

**Comment by kassambara** [comment]
Impressive work @pbiecek , thank you!!!

**Comment by MarcinKosinski** [comment]
Looks nice, can this be closed?
