### ISSUE TITLE
Suggestion: smoothed trend in ggcoxdiagnostics()

### ISSUE THREAD

**Issue by pbiecek** [kassambara/survminer#119]
Right now plots with residuals are enriched with horizontal line (geom_hline)
But, by adding in addition an layer with geom_smooth() 
it will be easier to spot some problems with residuals (like quadratic relation).
The additional surve may be added with parameter sline (in the same spirit as for hline)

**Comment by kassambara** [comment]
fixed with the pull request #120

**Comment by kassambara** [comment]
Thanks:-)!
