### ISSUE TITLE
Suggestion: remove 'ncol = 1' in facet_wrap()/ggcoxdiagnostics()

### ISSUE THREAD

**Issue by pbiecek** [kassambara/survminer#121]
Right now for "score" residuals a panel is created for every covariate.
But since there is an parameter 'ncol=1' in the 'facet_wrap(~covariate, scales = "free", ncol = 1)'
the plot is hard to read for larger number of covariates (see below, and here we have only 6 covariates).

Suggestion: remove the 'ncol =1'.

<img width="683" alt="screen shot 2017-01-23 at 22 41 48" src="https://cloud.githubusercontent.com/assets/4624318/22223964/2f6c38cc-e1bd-11e6-9048-82f58e45fd24.png">

**Comment by kassambara** [comment]
fixed now!
