### ISSUE TITLE
Releasing survminer 0.2.5

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#129]
I received again the e-mail below from the maintainer of CRAN Windows binaries.
So, the plan is to prepare survminer 0.2.5 for submission this week.

(e-meail from Uwe Ligges)

Please see the ERROR under R-oldrelease (R-3.2.5):
https://cran.r-project.org/web/checks/check_results_survminer.html

Apparently you realy on a specific version of 'RTCGA.clinical' and do not declare this in the DESCRIPTION nor do you check for it.

Please fix and resubmit.

Best,
Uwe Ligges

**Comment by MarcinKosinski** [comment]
Good luck with that! A post on R-Bloggers from STDHA is a must

**Comment by MarcinKosinski** [comment]
I would merge #131 before that and completely rebuild the `pkgdown`.
I've also seen there is a possibility to include NEWS.md somehowe in the pkgdown-like sites :)

**Comment by MarcinKosinski** [comment]
So many improvements. Maybe lets call it ver 0.3.0?

**Comment by kassambara** [comment]
Yeah, we can go for 0.3.0

**Comment by MarcinKosinski** [comment]
The readme section can be extended with more functions - there only 3 at the moment 
https://github.com/kassambara/survminer#survminer-survival-analysis-and-visualization

**Comment by kassambara** [comment]
R CMD Check

<pre>
Examples with CPU or elapsed time > 5s
                     user system elapsed
ggcoxadjustedcurves 6.304  0.369   6.738
ggsurvplot          5.729  0.082   6.540
</pre>

**Comment by kassambara** [comment]
R CMD check

<pre>
* checking whether package 'survminer' can be installed ... OK
* checking installed package size ... NOTE
  installed size is  5.5Mb
  sub-directories of 1Mb or more:
    doc   5.4Mb
</pre>

How to fix this?

**Comment by kassambara** [comment]
I'm wondering if we can ignore this note for the submission to CRAN. We'll see...

<pre>
doc$ ls -lhtr
total 10960
-rw-rw-r--  1 kassambara  admin   1,5M 18 fév 09:49 Specifiying_weights_in_log-rank_comparisons.html
-rw-rw-r--  1 kassambara  admin   6,4K 18 fév 09:49 Specifiying_weights_in_log-rank_comparisons.Rmd
-rw-rw-r--  1 kassambara  admin   2,8K 18 fév 09:49 Specifiying_weights_in_log-rank_comparisons.R
-rw-rw-r--  1 kassambara  admin   1,8M 18 fév 09:49 Playing_with_fonts_and_texts.html
-rw-rw-r--  1 kassambara  admin   3,9K 18 fév 09:49 Playing_with_fonts_and_texts.Rmd
-rw-rw-r--  1 kassambara  admin   3,5K 18 fév 09:49 Playing_with_fonts_and_texts.R
-rw-rw-r--  1 kassambara  admin   2,0M 18 fév 09:49 Informative_Survival_Plots.html
-rw-rw-r--  1 kassambara  admin   8,0K 18 fév 09:49 Informative_Survival_Plots.Rmd
-rw-rw-r--  1 kassambara  admin   3,4K 18 fév 09:49 Informative_Survival_Plots.R
-rw-rw-r--  1 kassambara  admin   2,7K 18 fév 09:49 index.html
</pre>

**Comment by MarcinKosinski** [comment]
I would ignore this note. I've seen bigger abuse on CRAN : )

**Comment by kassambara** [comment]
R CMD Check:
<pre>
Examples with CPU or elapsed time > 5s
                     user system elapsed
ggcoxadjustedcurves 6.815  0.501   7.479
ggcoxdiagnostics    4.562  0.306   5.042
</pre>

**Comment by MarcinKosinski** [comment]
In my opinion this can be ignored for CRAN release.
And this depends on the computer you use. Maybe on CRAN they have faster
machines : )

2017-03-14 23:10 GMT+01:00 Alboukadel KASSAMBARA <notifications@github.com>:

**Comment by kassambara** [comment]
survminer 0.3 submitted now

**Comment by kassambara** [comment]
On CRAN now https://cran.r-project.org/package=survminer
Docs updated: http://www.sthda.com/english/rpkgs/survminer/

Thank you @MarcinKosinski  & @pbiecek for your impressive work in improving the package.

@pbiecek thank you in advance for uploading the cheatsheet on Rstudio:-)

**Comment by pbiecek** [comment]
The cheatsheet is sent. Once it will be on RStudio website you shall receive tweet to @sthda_en. Good package, happy that I could help somehow

**Comment by kassambara** [comment]
Thanks!!!
