### ISSUE TITLE
Suggestion: a new function ggcoxadjustedcurves to fix #67

### ISSUE THREAD

**Issue by pbiecek** [kassambara/survminer#133]
In #67  @markdanese proposed to add survival curves for cox model. 
Not curves for average values of variables but curves averages over the distribution of variables observed in the data (like here: https://cran.r-project.org/web/packages/survival/vignettes/adjcurve.pdf, or in Marks' code here:  https://gist.github.com/markdanese/d1ddfdb2f618373c719bdb444ca34be9)

Suggestion: add a ggcoxadjustedcurves() function, that will plot survival curve for the whole dataset (average over all individual curves) or for subsets generated by a given variable.

In addition, al individual curves may be also added to the plot.

Some examples:
For whole dataset

<img width="526" alt="screen shot 2017-02-01 at 23 39 12" src="https://cloud.githubusercontent.com/assets/4624318/22529428/a99551b2-e8d7-11e6-82ec-28ce6b72b4a7.png">

For selected variables

<img width="521" alt="screen shot 2017-02-01 at 23 25 35" src="https://cloud.githubusercontent.com/assets/4624318/22529396/93c260a0-e8d7-11e6-8169-b3cd53c61ee8.png">
<img width="524" alt="screen shot 2017-02-01 at 23 25 17" src="https://cloud.githubusercontent.com/assets/4624318/22529397/9522f41e-e8d7-11e6-9562-0f06432b6955.png">

btw: I am not familiar with data.table, so this function uses dplyr and tidyr

**Comment by kassambara** [comment]
R CMD check:

checking R code for possible problems ... NOTE
ggcoxadjustedcurves: no visible binding for global variable ‘time’
ggcoxadjustedcurves: no visible binding for global variable ‘value’
ggcoxadjustedcurves: no visible binding for global variable ‘.id’
Undefined global functions or variables:
  .id time value
Consider adding
  importFrom("stats", "time")
to your NAMESPACE file.

**Comment by kassambara** [comment]
In the survminer functions eval(fit$call$data) is commonly used to get the model data. This lead to repetitive issues, for example #125 & #9. 

It might be better, if we add an extra argument, say `data`,  so that user can provide the model data. 

If yes, then we should update `ggsurvplot()`, `ggcoxfunctional()` & `ggcoxadjustedcurves()`.  The R code to be added in these function would look like:  

```r
if(missing(data)){
    warning ("...warning message...")
   data <- eval(fit$call$data)
}
```

What do you think @pbiecek , @MarcinKosinski ?

**Comment by kassambara** [comment]
An error is generated with the R code below:  

```r
library(survival)
library(survminer)

fit <- coxph(Surv(time, status) ~ age + ph.ecog+sex, data =  lung)
ggcoxadjustedcurves(fit)
```

```warning
geom_path: Each group consists of only one observation. Do you need to adjust the group aesthetic?
Warning message:
Removed 185 rows containing missing values (geom_path). 
```


But, this works:

```r
fit <- coxph(Surv(time, status) ~ age + sex, data =  lung)
ggcoxadjustedcurves(fit)
```

**Comment by pbiecek** [comment]
Regarding the `eval(fit$call$data)`
I had an issue when trying to use load() function with Shiny. Then the data is loaded to an other environment and the ggsurv returns and error 'data not found'. 
I've checked these alternatives:
`all.vars(formula(fit$call)` - returns all variables from formula
`colnames(broom::augment(fit))` - returns all variables and mode
`broom::augment(fit)` - returns an extended dataset, for some functions it may be enough.

But I agree, that the best way is to add additional `data=` argument.
Maybe this is a place for .get_data() function.

**Comment by pbiecek** [comment]
Regarding NOTEs in CHECK, 
they are caused by non standard evaluation used in dplyr/tidyr.
To deal with them I've used a hack as suggested in http://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when (solution 2).

**Comment by pbiecek** [comment]
The problem with 
`fit <- coxph(Surv(time, status) ~ age + ph.ecog+sex, data =  lung)`
was caused by missing values. Now I've added na.rm=TRUE to each mean() function and both curves are calculated properly.

**Comment by kassambara** [comment]
oh, great!!!

**Comment by MarcinKosinski** [comment]
Good job with that function and with missing `data` solution.

Can we stick to one naming conventions for parameters? Instead of `plot_all` can we have `plot.all` or just `all`? The same with `split_vars`? It might be `split.vars` or just `split` / `vars`. Most of the parameters in functions from `survminer` don't use `_` as we stick to `.` convention which isn't bad for parameters names : )

**Comment by MarcinKosinski** [comment]
@pbiecek can you also consider updating this file https://github.com/kassambara/survminer/blob/master/_pkgdown.yml with every new functionality? This is the configuration for the package site http://www.sthda.com/english/rpkgs/survminer/

**Comment by pbiecek** [comment]
@MarcinKosinski updated var names are in 7f5d590642f6e1e6008e0564195a5303dd15dcac

**Comment by pbiecek** [comment]
regarding the convention for names
in the _pkgdown you have functions like 'surv_summary', 'surv_cutpoint', 'pairwise_survdiff', 'theme_classic2' so still some work to do to have clean names
