### ISSUE TITLE
Warning messages: 1: In if (value %in% columns) { :   the condition has length > 1

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#144]
Like here 
https://github.com/kassambara/survminer/issues/142#issuecomment-277445257

those lines are here https://github.com/kassambara/survminer/blob/master/R/utilities.R#L31

**Comment by kassambara** [comment]
I'll fix this in few minutes

**Comment by kassambara** [comment]
should be ok now:-)!
