### ISSUE TITLE
Error in survminer when using knitr in RMarkdown

### ISSUE THREAD

**Issue by BenCorden** [kassambara/survminer#146]
In Rmarkdwon, when I try to knit to either a HTML or PDF  it terminates when I call ggsurvplot and I get the following error message:

Error in methods::is(fit, "survfit") : object 'MADIT_survfit' not found Calls: <Anoymous> ... withVisible -> eval -> eval -> ggsurvplot -> <Anonymous>

When I evaluate the ggsurvplot chunk independently it works fine, producing the expected plot. 

I've tried updating all packages but no effect. 

### `session_info()`

````{R}
# please paste here the result of
devtools::session_info()
````

**Comment by kassambara** [comment]
The error is not reproducible using the Rmarkdown document hereafter.. 

However I changed `methods::is(fit, "survfit") ` by `inherits(fit, "survfit")` in the ggsurvplot() function.

Please install the latest version from github and let me know if it works now...

<pre>
---
title: "Survminer"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(survival)
library(survminer)

lung_fit<- survfit(Surv(time, status) ~ sex, data = lung)

# Drawing survival curves
ggsurvplot(lung_fit, data = lung)

```
</pre>

**Comment by BenCorden** [comment]
Yes - works now. Many thanks!
