### ISSUE TITLE
Error in ggsurvplot with a particular form of survfit

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#150]
(e-mail from a survminer user)

Dear Alboukadel, 

My name is Tuan Nguyen from Australia. I am a user of your survminer package. Can I please have your advice on the use of ggsurvplot. When I run the command

survobj = Surv(pbc$fu.days, pbc$status=="death")
km = survfit(survobj ~ pbc$drug)
ggsurvplot(km)

It gives me a graph with the y-axis (which looks ok), but there is no x-axis. I have tried with other datasets, and the same problem appeared. Sometimes, the program displays neither y-axis nor x-axis! I run the program on the OSX operating system. 

Could you give me some idea what went wrong? 

Regards, Tuan

**Comment by kassambara** [comment]
Please, make sure that you have the latest version of survminer:
    
    
```{r}
#  install the latest version from GitHub
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/survminer", build_vignettes = FALSE)
```
    
    
The R code below should works:  

```{r}
library(survival)
library(survminer)

obj = Surv(lung$time, lung$status==2)
km = survfit(obj ~ lung$sex)
ggsurvplot(km, data = lung)
```

![rplot](https://cloud.githubusercontent.com/assets/3313355/22872587/a756cb2e-f1ba-11e6-8969-0f421a9a5e3b.png)

If the problem persists, I would suggest the following (clean) format to compute survfit:

```r
# Data preparation
lung$status <- lung$status == 2

# survfit
km <- survfit( Surv(time, status) ~ sex, data = lung)
ggsurvfit(km, data = lung)
```
  
In your specific case, the R code would be:  
     
```r
# Data preparation
pbc$status <- pbc$status=="death"

# survfit
km <- survfit( Surv(fu.days, status) ~drug, data = pbc)
ggsurvplot(km, data = pbc)
```

Please, let me know if it works so that we can close this issue.

**Comment by Surdaster** [comment]
I tried the code given by Kassambara ; it gives :

Error in ggsurvplot(km, data = lung) : unused argument (data = lung)
