### ISSUE TITLE
creating theme_survminer()

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#151]
suggestions by @pbiecek : 

> many functions take graphical parameters like font.tickslab, font.x and so on. Maybe it will be cleaner to create theme_survminer() and pass these graphical parameters through the theme function?

The function theme_survminer() could be a simple wrapper of the function ggpubr::ggpar() [ [http://www.sthda.com/english/rpkgs/ggpubr/reference/ggpar.html](http://www.sthda.com/english/rpkgs/ggpubr/reference/ggpar.html) ], which can already handle many of these arguments: font.x, font.main, ....

**Comment by kassambara** [comment]
I'll create this function

**Comment by kassambara** [comment]
```r
# Fit survival curves
#++++++++++++++++++++++++++++++++++++
require("survival")
fit<- survfit(Surv(time, status) ~ sex, data = lung)

# Change font size, style and color
#++++++++++++++++++++++++++++++++++++
# Change font size, style and color at the same time
# Use font.x = 14, to change only font size; or use
# font.x = "bold", to change only font face.

library(survminer)
ggsurvplot(
   fit, data = lung,
   main = "Survival curve",
   submain = "Based on Kaplan-Meier estimates",
   caption = "created with survminer",

   ggtheme = theme_survminer(
     font.main = c(16, "bold", "darkblue"),
     font.submain = c(15, "bold.italic", "purple"),
     font.caption = c(14, "plain", "orange"),
     font.x = c(14, "bold.italic", "red"),
     font.y = c(14, "bold.italic", "darkred"),
     font.tickslab = c(12, "plain", "darkgreen")
   )
 )
```

![rplot](https://cloud.githubusercontent.com/assets/3313355/23102548/47deede8-f6ab-11e6-85c8-d1ef29c86cc5.png)

**Comment by pbiecek** [comment]
I thought about adding the theme with `+` operator (a bit more convinient).
Since `ggsurvplot` returns list of plots then right now one can extract the plot with [[1]]

```
ggsurvplot(
   fit, data = lung,
   main = "Survival curve",
   submain = "Based on Kaplan-Meier estimates",
   caption = "created with survminer")[[1]] +
theme_survminer(
     font.main = c(16, "bold", "darkblue"),
     font.submain = c(15, "bold.italic", "purple"),
     font.caption = c(14, "plain", "orange"),
     font.x = c(14, "bold.italic", "red"),
     font.y = c(14, "bold.italic", "darkred"),
     font.tickslab = c(12, "plain", "darkgreen")
   )
```
but you may consider adding an overloaded `+` operator for object of the class `ggsurvplot` 
which will add RHS to every element of `ggsurvplot` list.

**Comment by kassambara** [comment]
Suggestion to simplify `ggsurvplot()` function:
    
    
-**Removing the following graphical arguments (without breaking users old scripts )**:

    
    
```r
font.main = c(16, "plain", "black"), 
font.submain = c(15, "plain", "black"),
font.caption = c(15, "plain", "black"),
font.x = c(14, "plain", "black"), font.y = c(14, "plain", "black"),
font.tickslab = c(12, "plain", "black"),

font.risk.table.title = c(16, "plain", "black"), 
font.risk.table.subtitle = c(15, "plain", "black"),
font.risk.table.caption = c(15, "plain", "black"),
font.risk.table.x = c(14, "plain", "black"), font.risk.table.y =  c(14, "plain", "black"),
font.risk.table.tickslab = c(12, "plain", "black"),

font.ncensor.plot.title = c(16, "plain", "black"), 
font.ncensor.plot.subtitle = c(15, "plain", "black"),
font.ncensor.plot.caption = c(15, "plain", "black"),
font.ncensor.plot.x = c(14, "plain", "black"), 
font.ncensor.plot.y = c(14, "plain", "black"),
font.ncensor.plot.tickslab = c(12, "plain", "black")
```
   
   
These arguments can be replaced by `...` argument, which can be passed to the function `ggpubr::ggpar()`.
   
The function `ggpar()` can be used to customize the graphical parameters of one or multiple ggplots at once.
   
   
For example, users can customize ggsurvplots as follow.
   
   
1. To change the appearance of survival curves, risk.table and ncensor.plot at once:
  
  
```r
# Customizing during plot creation
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Use this
ggsurv <- ggsurvplot(fit, 
      ggtheme = theme_survminer(font.main, font.submain, ....))

# Or this (which doesn't break user old scripts. Arguments are passed to ggpar)
ggsurv <- ggsurvplot(fit,
        font.main, font.submain, font.x, ....)

# Customizing after plot creation
ggsurv <- ggsurvplot(fit)
ggpubr::ggpar(ggsurv, font.main, font.submain, font.caption, ...)

```
    
    
    
2. To change a specific component of ggsurvplot (e.g.: risk table), one can use this


```r
ggsurv <- ggsurvplot(fit, risk.table = TRUE)
ggsurv$table <- ggpubr::ggpar(ggsurv$table, font.main, font.submain, font.caption, ...)
print(ggsurv)
```
   
   
Regarding + operator for object of the class ggsurvplot, I tried the following code without success:


```{r}
#' @rdname theme_survminer
#' @method + ggsurvplot
#' @export
"+.ggsurvplot" <- function (e1, e2)
{
  e2name <- deparse(substitute(e2))
  if(inherits(e1, "ggsurvplot")){
    e1$plot <- ggplot2:::add_ggplot(e1$plot, e2, e2name)
    if(!is.null(e1$table)) e1$table <- ggplot2:::add_ggplot(e1$table, e2, e2name)
  }
  e1
}
```



The above code is inspired from the one used by hadley in ggplot2:


```r
"+.gg" <- function (e1, e2) 
{
    e2name <- deparse(substitute(e2))
    if (is.theme(e1)) 
        add_theme(e1, e2, e2name)
    else if (is.ggplot(e1)) 
        add_ggplot(e1, e2, e2name)
}
```

**Comment by kassambara** [comment]
Should work now, with "%+%" operator

```r
# Fit survival curves
require("survival")
fit<- survfit(Surv(time, status) ~ sex, data = lung)

# Basicsurvival curves
p <- ggsurvplot(fit, data = lung, risk.table = TRUE)
p

# Customizing the plots
p %+% theme_survminer(
     font.main = c(16, "bold", "darkblue"),
     font.submain = c(15, "bold.italic", "purple"),
     font.caption = c(14, "plain", "orange"),
     font.x = c(14, "bold.italic", "red"),
     font.y = c(14, "bold.italic", "darkred"),
     font.tickslab = c(12, "plain", "darkgreen")
)

```

**Comment by MarcinKosinski** [comment]
Outstanding job! Do you think this will work with the rest of survminer's functions or only with `ggsurvplot()`?
I can have a look at your change to apply this to the `ggcox..` functions

**Comment by kassambara** [comment]
I will update the %+% operator to handle the outputs of the other survminer functions. I will also update ggsurvplot to reduce the number of graphical arguments...

**Comment by pbiecek** [comment]
Regarding the problem with + operator
In addition to function definition the new operator shall be also registered in NAMESPACE as
S3method("+",ggsurvplot)
(as in https://github.com/tidyverse/ggplot2/blob/0d402da4a9338b9eab7caa3f99d1addd30ea5707/NAMESPACE)

**Comment by kassambara** [comment]
yes, this is already the case  https://github.com/kassambara/survminer/blob/master/NAMESPACE

**Comment by kassambara** [comment]
The warning message I obtained using the `+` operator is 

```
Warning message:
Incompatible methods ("+.ggsurvplot", "+.gg") for "+" 
```

But, using `%+%` works.

**Comment by kassambara** [comment]
Now the %+% operator works with one ggplot or any list of ggplots

```r
library(survival)
fit <- coxph(Surv(futime, fustat) ~ age + ecog.ps + rx, data=ovarian)
cox.zph.fit <- cox.zph(fit)
# plot all variables
p <- ggcoxzph(cox.zph.fit)

p %+% theme_survminer(
    font.main = c(16, "bold", "darkblue"),
    font.x = c(14, "bold.italic", "red"),
    font.y = c(14, "bold.italic", "darkred"),
    font.tickslab = c(12, "plain", "darkgreen")
  )
```
![rplot01](https://cloud.githubusercontent.com/assets/3313355/23105248/4fb7eaac-f6dc-11e6-9ca5-c985160d9645.png)

**Comment by kassambara** [comment]
the + operator seems to work with `labs()` but not with `theme()`

```r
p1+labs(y = "yyyyyyyyyyy", x ="xxxxxx", caption = "survvvvvvv")
```
![rplot02](https://cloud.githubusercontent.com/assets/3313355/23105401/da4d39c2-f6de-11e6-8899-4856b68e3bb8.png)

**Comment by pbiecek** [comment]
The problem with `+` operator was discussed here: http://r.789695.n4.nabble.com/quot-Incompatible-methods-quot-for-overloaded-operator-td4633362.html

So for A + B only two solutions will work. Either there is only one overloaded + (+.A or +.B) and it will be used, or there are two methods +.A and +.B but they point into the same object.

It is satisfied for ggsurv()+labs() since labs() returns an object of the class `labels` and there is no `+.labels`
But ggsurv() + theme() is equivalent to `gglist` + (`theme, gg`), there is no `+.theme` but there are different `+.gglist` and `+.gg`.

The simplest solution is to remove the class `gg` from the classes returned by `theme_survminer()`.

**Comment by kassambara** [comment]
Oh, thank you!!!!!!

**Comment by pbiecek** [comment]
I see that you have now `+.gglist`, but the `ggsurv()` returns object of the class `ggsurvplot()`, this needs to be somehow simplified ;-)

**Comment by kassambara** [comment]
As `ggsurvplot()`, `ggcoxzph()` and `ggcoxfunctional()`return a list of ggplots, we need to define a common class for the 3 functions...

This could be either gglist , ggsurv or survminer,....

**Comment by kassambara** [comment]
It works like a charm now

**Comment by kassambara** [comment]
I'll update the 3 functions to add the class `ggsurv`

**Comment by pbiecek** [comment]
+1
in future the `gglist` may collide with some other package, that creates lists of ggplots
`ggsurv` is short and unique

**Comment by kassambara** [comment]
The graphical parameters - font.main, font.x,  ... -, which can be passed  directly to the `ggsurvplot()` function are no longer documented in the ggsurvplot.R file... 

```r
ggsurvplot(
  fit,                     # survfit object with calculated statistics.
  data = lung,             # data used to fit survival curves.
  risk.table = TRUE,       # show risk table.
  pval = TRUE,             # show p-value of log-rank test.
  conf.int = TRUE,         # show confidence intervals for 
  # point estimates of survival curves.
  xlim = c(0,500),         # present narrower X axis, but not affect
  # survival estimates.
  xlab = "Time in days",   # customize X axis label.
  break.time.by = 100,     # break X axis in time intervals by 500.
  ggtheme = theme_light(), # customize plot and risk table with a theme.
  risk.table.y.text.col = T,# colour risk table text annotations.
  risk.table.y.text = FALSE,# show bars instead of names in text annotations
  # in legend of risk table.
  ncensor.plot = TRUE,      # plot the number of censored subjects at time t
  conf.int.style = "step",  # customize style of confidence intervals
  surv.median.line = "hv",  # add the median survival pointer.
  legend.labs = 
    c("Male", "Female"),    # change legend labels.
  palette = 
    c("#E7B800", "#2E9FDF"),# custom color palettes.
  main = "Survival curves",                       # specify the title of the plot
  submain = "Based on Kaplan-Meier estimates",    # the subtitle of the plot 
  caption = "created with survminer",             # the caption of the plot
  font.main = c(16, "bold", "darkblue"),          # font for titles of the plot, the table and censor part
  font.submain = c(15, "bold.italic", "purple"),  # font for subtitles in the plot, the table and censor part
  font.caption = c(14, "plain", "orange"),        # font for captions in the plot, the table and censor part
  font.x = c(14, "bold.italic", "red"),           # font for x axises in the plot, the table and censor part
  font.y = c(14, "bold.italic", "darkred"),       # font for y axises in the plot, the table and censor part
  font.tickslab = c(12, "plain", "darkgreen"),    # font for ticklabs in the plot, the table and censor part
  ########## risk table #########,
  risk.table.title = "Note the risk set sizes",          # the title of the risk table
  risk.table.subtitle = "and remember about censoring.", # the subtitle of the risk table
  risk.table.caption = "source code: website.com",       # the caption of the risk table
  risk.table.height = 0.35,                              # the height of the risk table
  ########## ncensor plot ######
  ncensor.plot.title = "Number of censorings",           # as above but for the censoring plot
  ncensor.plot.subtitle = "over the time.",
  ncensor.plot.caption = "data available at data.com",
  ncensor.plot.height = 0.35
)

```

Now, I think that it would be better to update the README and vignette files...

**Comment by MarcinKosinski** [comment]
`going to far with survival plots` .... : )

**Comment by kassambara** [comment]
Suggestion:
- `ggplot2::labs()`  for changing the title of survival curves, risk table and ncensor plots.
- `ggpubr::ggpar()` for changing the graphical parameters of one or list of ggplots

Examples:

```r

require("survival")
fit<- survfit(Surv(time, status) ~ sex, data = lung)

# Drawing survival curves
require("survminer")
ggsurv <- ggsurvplot(fit, data = lung, risk.table = TRUE)

# Uber platinum customized survival curves
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Survival curves
ggsurv$plot <- ggsurv$plot + labs(
  title = "Survival curves",                     # specify the title of the plot
  subtitle = "Based on Kaplan-Meier estimates",  # the subtitle of the plot 
  caption = "created with survminer"             # the caption of the plot
  )

#risk table 
ggsurv$table <- ggsurv$table + labs(
  title = "Note the risk set sizes",          # the title of the risk table
  subtitle = "and remember about censoring.", # the subtitle of the risk table
  caption = "source code: website.com"        # the caption of the risk table
  )

# ncensor plot 
ggsurv$ncensor.plot <- ggsurv$ncensor.plot + labs( 
  title = "Number of censorings", 
  subtitle = "over the time.",
  caption = "source code: website.com"
  )

# use ggpar to change the font of one or a list of ggplots at once
ggpubr::ggpar(ggsurv,
      font.title = c(16, "bold", "darkblue"),          # font for titles of the plot, the table and censor part
      font.subtitle = c(15, "bold.italic", "purple"),  # font for subtitles in the plot, the table and censor part
      font.caption = c(14, "plain", "orange"),        # font for captions in the plot, the table and censor part
      font.x = c(14, "bold.italic", "red"),           # font for x axises in the plot, the table and censor part
      font.y = c(14, "bold.italic", "darkred"),       # font for y axises in the plot, the table and censor part
      font.tickslab = c(12, "plain", "darkgreen"),    # font for ticklabs in the plot, the table and censor part
      legend = "top"
      )

```

**Comment by venkan** [comment]
@kassambara When I run `ggpubr:ggpar` from the above which you showed it gives an `Error` like following:

```
Error in `merge_element()`:
! Only elements of the same class can be merged
```

**Comment by asmlgkj** [comment]
it seems does not change when using theme_survminer. thanks a lot
> sessionInfo()
R version 4.2.1 
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 8

Matrix products: default


locale:
 [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=zh_CN.UTF-8        LC_COLLATE=zh_CN.UTF-8    
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8   
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] survminer_0.4.9 ggpubr_0.6.0    ggplot2_3.4.4   survival_3.5-5 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.12       pillar_1.9.0      compiler_4.2.1    tools_4.2.1      
 [5] lifecycle_1.0.4   tibble_3.2.1      gtable_0.3.4      lattice_0.21-8   
 [9] pkgconfig_2.0.3   rlang_1.1.3       Matrix_1.6-5      cli_3.6.2        
[13] commonmark_1.9.0  xfun_0.39         gridExtra_2.3     stringr_1.5.0    
[17] xml2_1.3.4        knitr_1.42        withr_3.0.0       dplyr_1.1.2      
[21] generics_0.1.3    vctrs_0.6.5       survMisc_0.5.6    gridtext_0.1.5   
[25] ggtext_0.1.2      grid_4.2.1        tidyselect_1.2.0  data.table_1.15.0
[29] glue_1.7.0        R6_2.5.1          KMsurv_0.1-5      rstatix_0.7.2    
[33] fansi_1.0.6       km.ci_0.5-6       carData_3.0-5     farver_2.1.1     
[37] tidyr_1.3.0       purrr_1.0.1       car_3.1-1         magrittr_2.0.3   
[41] scales_1.3.0      backports_1.4.1   splines_4.2.1     abind_1.4-5      
[45] xtable_1.8-4      colorspace_2.1-0  ggsignif_0.6.4    labeling_0.4.3   
[49] utf8_1.2.4        stringi_1.7.12    munsell_0.5.0     broom_1.0.4      
[53] markdown_1.6      zoo_1.8-12       
>
