### ISSUE TITLE
Cumulative number of censoring

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#155]
As mentioned at https://github.com/kassambara/survminer/issues/154#issuecomment-282840147,
the current version of `ggsurvplot()` creates the ncensor plot, based on raw timing. 

Additional arguments are needed to display the cumulative number of censored subjects as a table.

**Comment by kassambara** [comment]
With `ggsurvplot()`, one can now display either 

- the number of censoring using `ncensor.plot = TRUE` 
- or the cumulative number of censoring using `cumcensor = TRUE`


**Fit survival curves**:
<hr/>
    
```r
library(survival)
fit <- survfit( Surv(time, status) ~ sex, data = lung )
```

**Number of censoring as barplot**:  
<hr/>

```r
library(survminer)
ggsurvplot(fit, data = lung,
           risk.table = TRUE,
           cumevents = TRUE,
           ncensor.plot = TRUE,
           palette = "jco",
           risk.table.height = 0.2,
           cumevents.height = 0.2,
           ncensor.plot.height = 0.2
           )
```

![rplot04](https://cloud.githubusercontent.com/assets/3313355/23393357/97f031ce-fd82-11e6-9bdd-7b43b8fbc061.png)


**Cumulative number of censoring as table:**
<hr/>

```r
library(survminer)
ggsurvplot(fit, data = lung,
           risk.table = TRUE,
           cumevents = TRUE,
           cumcensor = TRUE,
           palette = "jco",
           risk.table.height = 0.2,
           cumevents.height = 0.2,
           ncensor.plot.height = 0.2
           )
```

![rplot05](https://cloud.githubusercontent.com/assets/3313355/23393397/d49cfae4-fd82-11e6-976a-51281678e6d4.png)

**Comment by Polperobis** [comment]
Bonjour Kassambara,
Is it possible to set the font size of the cumcensor tale ?
