### ISSUE TITLE
Cheat sheet

### ISSUE THREAD

**Issue by pbiecek** [kassambara/survminer#159]
What do you think about a one page/two pages cheat sheet in pdf 
that introduces selected functions from survminer?
Probably it could be done based on existing examples.

**Comment by kassambara** [comment]
I think that this is something that we should do and it will be very helpful.

I was also thinking about creating a catalogue of survminer plots with an interactive option to display the R code.  Something like this: http://shinyapps.org/apps/RGraphCompendium/index.php

**Comment by pbiecek** [comment]
It could looks more or less like that:
[survminerCheatsheet.pdf](https://github.com/kassambara/survminer/files/809075/survminerCheatsheet.pdf)

**Comment by kassambara** [comment]
Looks great!!!!

**Comment by pbiecek** [comment]
The second column may looks like in the attached pdf. 

For some reason the ggcoxzph() function is not working for me (will add an issue for that).

In the third column I am going to add forest plots and adjusted curves for cox model, but let me know if some other functions shall be presented there.

[survminerCheatsheet.pdf](https://github.com/kassambara/survminer/files/812157/survminerCheatsheet.pdf)

**Comment by kassambara** [comment]
Awesome work, thank you!

 ggcoxzph() examples should work now.

**Comment by MarcinKosinski** [comment]
I've just used this cheat-sheet to recall that we have `fun` argument : )
We can also have interactive flexdashboard with examples - http://rmarkdown.rstudio.com/flexdashboard/examples.html

**Comment by pbiecek** [comment]
Ok, the candidate onepage summary is here: https://github.com/pbiecek/survminer/blob/master/docs/survminer_cheatsheet.pdf
Let me know if you find something worth adding or changing. 

Actually I found it very involving/engaging.

**Comment by kassambara** [comment]
Perfect! I really like it!

A small change to be considered: 

 In the `Summary of Cox Model section`,  It's mentioned the function ggforest() from the `survival` package instead of  the `survminer` package.

**Comment by pbiecek** [comment]
Thanks, fixed in #163.

Playing with one page summaries in Illustrator is pretty fun. 
Initially I was planning 2 pages but I could not find topics for the second page.

If you think that such summary may be useful for factoextra package..., 
there is more nice plots to be presented.

**Comment by kassambara** [comment]
We'll share this  cheatsheet on R-bloggers after releasing survminer 0.3.

I absolutely think that a such beautiful cheatsheet for  factoextra would be  a great plus and highly appreciated by the growing users of the package.

**Comment by pbiecek** [comment]
QL, I am using factoextra in my Statistics II classes, so short overview will be helpful for my students as well.

**Comment by MarcinKosinski** [comment]
If this one pager could be done in  a more reproducible way (like a final pdf created with latex/rmarkdown) then I could provide some linguistic updates and code highlighting. We could also have better versioning then. 

In this version we still have a lot of white spaces - we could use that for adding titles to plots. But I think we could rather rearrange that horizontally instead of perpendicularly, to gain more space. We could also extend this text to cover the weighted log-rank tests that `survminer` supports. Also the text could be presented on a frame with a coloured background so that it can be easily distinguished from a code and code's results.

I'd say it's a draft version rather than ready-to-be-published on R-Bloggers cheat sheet.

**Comment by pbiecek** [comment]
It was created in Adobe Illustrator and the main reason was to have better control on layout and the .pdf/.ai is the source format for AI. I don't think that such control is possible from latex/markdown. You may edit descriptions in the pdf with Inkscape or AI or you can suggest changes to be applied. 

Regarding plots. For sure they may be enriched with titles, annotations different background, but my goal was to keep the R code as short as possible to present defaults. Since plots are in ggplot2 then they are customisable also in the standard ggplot2 way.

**Comment by kassambara** [comment]
Doing a well designed cheatsheet in a reproducible way seems to be a very difficult task.  Solutions include Adobe illustrator powerpoint/keynote.  At Rstudio, they use powerpoint or keynote. Templates are availbale at: https://www.rstudio.com/resources/cheatsheets/how-to-contribute-a-cheatsheet/

**Comment by pbiecek** [comment]
Actually, It's good idea to submit the cheatsheet to RStudio resource list (once it will be ready). 
@MarcinKosinski if you have some propositions how to update the descriptions let me know.
I do not see the horizontal layout. The standard design is to use narrow columns - it's easier to read. Newspapers are organised this way, websites (https://www.nytimes.com/), RStudio cheatsheets etc.

**Comment by kassambara** [comment]
Yes, we can submit to RStudio and share it on social media

**Comment by MarcinKosinski** [comment]
![image](https://cloud.githubusercontent.com/assets/6773454/23613550/2c95a776-0280-11e7-8a6b-08e7e4c776b1.jpeg)

I meant such a layout when I mentioned consideration about horizontal/vertical appearance.
Text can be read in one column from up to down as it is done in a regular newspaper. We have division from code, text and graphs. But this is just and idea to somehow organize this cheatsheet

**Comment by kassambara** [comment]
Hi @pbiecek, 

In the cheatsheet, survival curves section, last plot: you used `tun = "pct"` instead of `fun = "pct"`

**Comment by pbiecek** [comment]
Thanks! Fixed.
Btw: I am working right now with with competing risks objects generated with 
cuminc{cmprsk}.
The default plot for cuminc is in base R graphics. The ggplot2 version looks nicer. Is it a material for survmisc?

**Comment by kassambara** [comment]
Visualizing competing risks is in the scope of surminer. If you already a gg function to that, this is very welcomed.

**Comment by teigentler** [comment]
My adaption from Moore Applied Survival Anaylsis Using R, Figure 9.5

```
dataSet$DeathStatus <- factor(dataSet$DeathStatus,0:2,labels=c("censor","death from cSS","death from other causes"))

sf  <- survfit(Surv(as.numeric(dataSet$timeOS)/DaysPerYear, dataSet$DeathStatus, type="mstate") ~ 1)
tt <- sf$time
CIs <- sf$pstate
SSurv <- 1 - apply(CIs, 1, sum)
ci1 <- CIs[,1]
ci2 <- CIs[,2]
times <- tt/12

Rci2 <- 1 - ci2
ci1.ci2 <- ci2-ci1

compRisk  <- data.frame(ci1.ci2,times,ci1)
pl        <- ggplot(compRisk,aes(times,ci1.ci2)) + geom_area(aes(y=1,fill="Alive"),position="stack") +  geom_area(aes(fill="Death from\nother causes")) + geom_area(aes(y=ci1,fill="Death from\ncSS"))
pl        <- pl + theme_cowplot()
pl        <- pl + ylab("Probability patient has died")  + xlab("Years from cSCC diagnosis")
pl        <- pl + ylim(c(0,1)) + scale_x_continuous(breaks=seq(0,10,1))

pl        <- pl + scale_fill_jco()
pl$labels$fill <- ""
pl        <- pl + theme(legend.key.size = unit(2, 'lines'))
pl
```
![grafik](https://cloud.githubusercontent.com/assets/18628021/23846704/f0d46caa-07ce-11e7-9025-c1b52bbab822.png)

**Comment by kassambara** [comment]
Looks beautiful, thanks!!

**Comment by pbiecek** [comment]
@teigentler a pretty nice plot. I was thinking about a more direct translation of plots for cuminc{cmprsk}. They allow for group comparisons. But both types of plots may be useful.
Let's move the CR thread to https://github.com/kassambara/survminer/issues/168

Btw: I've just uploaded an eurostat vignette to https://www.rstudio.com/resources/cheatsheets/. It's quite easy and Garrett Grolemund is very helpful. What about sending the survminer vigniette there as well?

**Comment by kassambara** [comment]
I plan to submit survminer v0.3 to CRAN this week. 

It would be great if you can upload also the survminer cheatseet on rstudio, after the release of of v0.3

**Comment by pbiecek** [comment]
Sure!
