### ISSUE TITLE
Diagnostic plots for cox model

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#16]
There was one great functionality of `dx` function http://www.inside-r.org/packages/cran/survMisc/docs/dxPlot that produced diagnostic plots for cox models. Do you think it would be valuable to add such functionality to survminer?

````{R}
library(survMisc) # can be downloaded from CRAN from it's archives
data(bmt, package="KMsurv")
bmt <- within(bmt, {
   z1 <- z1 -28
   z2 <- z2- 28
   z3 <- z1*z2
   z4 <- as.double( group== 2 )
   z5 <- as.double( group== 3 )
   z6 <- z8
   z7 <- (z7 / 30) - 9
   z8 <- z10
})
c1 <- coxph(Surv(t2,d3) ~ z1+z2+z3+z4+z5+z6+z7+z8,
            method="breslow",
            data=bmt)
dx(c1, what="ph", file="vetDx.pdf")
```

**Comment by kassambara** [comment]
Yes of course!!

**Comment by MarcinKosinski** [comment]
I have no motivation for rewriting `dxPlot` but I thought about new `ggcoxdiagnostics`/`ggcoxdiagnostic` function that would present

1. deviance residuals VS linear predictions/combinations
2. martingale residuals VS linear predictions/combinations
3. deviance residuals VS observation index
4. martingale residuals VS observation index

[as this can be seen here on the page 4](https://github.com/AnitaSzewczyk/SurvivalAnalysis/blob/master/projekt12015.pdf) (code is [here](https://github.com/AnitaSzewczyk/SurvivalAnalysis/blob/master/projekt12015.Rmd)). This article (sadly only in polish, it was an university project) presents basic survival analysis with plots for which we already have functions (ggsurvplot, ggcoxfunctional ggcoxzph) but we do not have plots for model diagnostics. The residuals shouldn't be larger that 2/3 and the shouldn't lay on a pattern line - they should be random.

I think this additional function would provide a nice toolkit for Cox Proportional Hazards Survival Analysis, and after that we could prepare a short article to [R Journal](https://journal.r-project.org/) using the template from [`rticles`](https://cran.r-project.org/web/packages/rticles/index.html) package
https://github.com/AnitaSzewczyk/SurvivalAnalysis/blob/master/projekt12015.pdf

**Comment by kassambara** [comment]
sorry, didn't see this comment yesterday:-)!
I think that this would be great!

**Comment by MarcinKosinski** [comment]
Proposition in #44
