### ISSUE TITLE
Examples for ggcoxzph() fail with 'Each variable must be a 1d atomic vector or list.'

### ISSUE THREAD

**Issue by pbiecek** [kassambara/survminer#160]
### Expected behavior 

Following lines (from man page) will return a plot

```
library(survival)
fit <- coxph(Surv(futime, fustat) ~ age + ecog.ps + rx, data=ovarian)
cox.zph.fit <- cox.zph(fit)
ggcoxzph(cox.zph.fit)
```

### Actual behavior

The `ggcoxzph` returns and errror.
```
Error: Each variable must be a 1d atomic vector or list.
Problem variables: 'y'
```

### Steps to reproduce the problem

```
example(ggcoxzph)
```

### `session_info()`

````{R}
Session info ---------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Warsaw               
 date     2017-03-01                  

Packages -------------------------------------------------------------------
 package    * version    date       source                               
 assertthat   0.1        2013-12-06 CRAN (R 3.3.0)                       
 broom        0.4.2      2017-02-13 cran (@0.4.2)                        
 colorspace   1.3-1      2016-11-18 CRAN (R 3.3.2)                       
 data.table   1.10.0     2016-12-03 cran (@1.10.0)                       
 DBI          0.5-1      2016-09-10 cran (@0.5-1)                        
 devtools     1.12.0     2016-06-24 CRAN (R 3.3.0)                       
 digest       0.6.12     2017-01-27 cran (@0.6.12)                       
 dplyr        0.5.0      2016-06-24 CRAN (R 3.3.0)                       
 foreign      0.8-67     2016-09-13 CRAN (R 3.3.2)                       
 ggplot2    * 2.2.1.9000 2017-03-01 Github (hadley/ggplot2@fa8004e)      
 ggpubr     * 0.1.1.999  2017-02-26 Github (kassambara/ggpubr@7f8a829)   
 gridExtra    2.2.1      2016-02-29 CRAN (R 3.3.0)                       
 gtable       0.2.0      2016-02-26 CRAN (R 3.3.0)                       
 km.ci        0.5-2      2009-08-30 CRAN (R 3.3.0)                       
 KMsurv       0.1-5      2012-12-03 CRAN (R 3.3.0)                       
 knitr        1.15.1     2016-11-22 cran (@1.15.1)                       
 lattice      0.20-34    2016-09-06 CRAN (R 3.3.2)                       
 lazyeval     0.2.0      2016-06-12 CRAN (R 3.3.0)                       
 magrittr     1.5        2014-11-22 CRAN (R 3.3.0)                       
 Matrix       1.2-7.1    2016-09-01 CRAN (R 3.3.2)                       
 memoise      1.0.0      2016-01-29 CRAN (R 3.3.0)                       
 mnormt       1.5-5      2016-10-15 CRAN (R 3.3.0)                       
 munsell      0.4.3      2016-02-13 CRAN (R 3.3.0)                       
 nlme         3.1-128    2016-05-10 CRAN (R 3.3.2)                       
 plyr         1.8.4      2016-06-08 CRAN (R 3.3.0)                       
 psych        1.6.12     2017-01-08 cran (@1.6.12)                       
 R6           2.2.0      2016-10-05 cran (@2.2.0)                        
 Rcpp         0.12.9.2   2017-02-15 Github (RcppCore/Rcpp@d96fcc0)       
 reshape2     1.4.2      2016-10-22 cran (@1.4.2)                        
 scales       0.4.1      2016-11-09 cran (@0.4.1)                        
 stringi      1.1.2      2016-10-01 cran (@1.1.2)                        
 stringr      1.1.0      2016-08-19 CRAN (R 3.3.0)                       
 survival     2.40-1     2016-10-30 CRAN (R 3.3.0)                       
 survminer  * 0.3.0      2017-03-01 Github (kassambara/survminer@6b2da26)
 survMisc     0.5.4      2016-11-23 cran (@0.5.4)                        
 tibble       1.2        2016-08-26 cran (@1.2)                          
 tidyr        0.6.1      2017-01-10 cran (@0.6.1)                        
 withr        1.0.2      2016-06-20 CRAN (R 3.3.0)                       
 xtable       1.8-2      2016-02-05 CRAN (R 3.3.0)                       
 zoo          1.7-14     2016-12-16 cran (@1.7-14)
````

**Comment by kassambara** [comment]
It works on my computer:

<pre>
Session info --------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  fr_FR.UTF-8                 
 tz       Europe/Paris                
 date     2017-03-02                  

Packages ------------------------------------------------------------------------------------------------------------------
 package        * version   date       source                               
 assertthat       0.1       2013-12-06 CRAN (R 3.3.0)                       
 BH               1.62.0-1  2016-11-19 CRAN (R 3.3.2)                       
 broom            0.4.2     2017-02-13 CRAN (R 3.3.2)                       
 colorspace       1.3-2     2016-12-14 CRAN (R 3.3.2)                       
 data.table       1.10.4    2017-02-01 cran (@1.10.4)                       
 DBI              0.5-1     2016-09-10 CRAN (R 3.3.0)                       
 dichromat        2.0-0     2013-01-24 CRAN (R 3.3.0)                       
 digest           0.6.12    2017-01-27 cran (@0.6.12)                       
 dplyr            0.5.0     2016-06-24 CRAN (R 3.3.0)                       
 evaluate         0.10      2016-10-11 CRAN (R 3.3.0)                       
 exactRankTests   0.8-29    2017-03-01 cran (@0.8-29)                       
 foreign          0.8-67    2016-09-13 CRAN (R 3.3.2)                       
 ggplot2        * 2.2.1     2016-12-30 CRAN (R 3.3.2)                       
 ggpubr         * 0.1.1.999 2017-02-25 Github (kassambara/ggpubr@7f8a829)   
 ggrepel          0.6.5     2016-11-24 CRAN (R 3.3.2)                       
 ggsci            2.0       2016-11-21 CRAN (R 3.3.2)                       
 gridExtra        2.2.1     2016-02-29 CRAN (R 3.3.0)                       
 gtable           0.2.0     2016-02-26 CRAN (R 3.3.0)                       
 highr            0.6       2016-05-09 CRAN (R 3.3.0)                       
 km.ci            0.5-2     2009-08-30 CRAN (R 3.3.0)                       
 KMsurv           0.1-5     2012-12-03 CRAN (R 3.3.0)                       
 knitr            1.15.1    2016-11-22 CRAN (R 3.3.2)                       
 labeling         0.3       2014-08-23 CRAN (R 3.3.0)                       
 lattice          0.20-34   2016-09-06 CRAN (R 3.3.2)                       
 lazyeval         0.2.0     2016-06-12 CRAN (R 3.3.0)                       
 magrittr         1.5       2014-11-22 CRAN (R 3.3.0)                       
 markdown         0.7.7     2015-04-22 CRAN (R 3.3.0)                       
 MASS             7.3-45    2016-04-21 CRAN (R 3.3.2)                       
 Matrix           1.2-8     2017-01-20 CRAN (R 3.3.2)                       
 maxstat          0.7-24    2016-04-06 CRAN (R 3.3.0)                       
 mime             0.5       2016-07-07 CRAN (R 3.3.0)                       
 mnormt           1.5-5     2016-10-15 CRAN (R 3.3.0)                       
 munsell          0.4.3     2016-02-13 CRAN (R 3.3.0)                       
 mvtnorm          1.0-5     2016-02-02 CRAN (R 3.3.0)                       
 nlme             3.1-131   2017-02-06 CRAN (R 3.3.2)                       
 plyr             1.8.4     2016-06-08 CRAN (R 3.3.0)                       
 psych            1.6.12    2017-01-08 CRAN (R 3.3.2)                       
 R6               2.2.0     2016-10-05 CRAN (R 3.3.0)                       
 RColorBrewer     1.1-2     2014-12-07 CRAN (R 3.3.0)                       
 Rcpp             0.12.9    2017-01-14 CRAN (R 3.3.2)                       
 reshape2         1.4.2     2016-10-22 CRAN (R 3.3.0)                       
 scales           0.4.1     2016-11-09 CRAN (R 3.3.2)                       
 stringi          1.1.2     2016-10-01 CRAN (R 3.3.0)                       
 stringr          1.2.0     2017-02-18 cran (@1.2.0)                        
 survival       * 2.40-1    2016-10-30 CRAN (R 3.3.0)                       
 survminer      * 0.3.0     2017-03-01 Github (kassambara/survminer@841f07f)
 survMisc         0.5.4     2016-11-23 CRAN (R 3.3.2)                       
 tibble           1.2       2016-08-26 CRAN (R 3.3.0)                       
 tidyr            0.6.1     2017-01-10 CRAN (R 3.3.2)                       
 xtable           1.8-2     2016-02-05 CRAN (R 3.3.0)                       
 yaml             2.1.14    2016-11-12 CRAN (R 3.3.2)                       
 zoo              1.7-14    2016-12-16 CRAN (R 3.3.2) 
</pre>

**Comment by kassambara** [comment]
The main difference between your session info and mine, is that you have installed the latest the developmental version of ggplot2: ggplot2_2.2.1.9000


After installing the developmental version, It fails also for me with the same error : 

```
Each variable must be a 1d atomic vector or list.
Problem variables: 'y'
```

**Comment by kassambara** [comment]
fixed now. In ggcoxzph(), yhat, ylow and yup  were a one-dimension matrix, which seems to be a problem, in  ggplot2_2.2.1.9000,  when passed to geom_*  function

**Comment by pbiecek** [comment]
Tnanks!
