### ISSUE TITLE
Combining 2 cox regression varaibles in one graph

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#164]
(e-mail from  a user)

I recently came by your Survminer R package and find it great! Most modifications have I been able to do by myself, but I haven’t found a way to combine two cox regression models in the same graph and axis. Both models are categorical having 3 different factors (low risk, intermediate risk and high risk). They are encoded in the same dataset in different columns.

Is this possible to do with Survminer?

**Comment by pbiecek** [comment]
On one hand it should be not that hard to return a plot for cox model as a single layer and then add it to an existing ggplot2 object.
But it may easily mess the legend.

**Comment by kassambara** [comment]
I think that we can close this issue
