### ISSUE TITLE
ggcoxzph cannot be found as package survminer failed to load after a new installation of survminer 

### ISSUE THREAD

**Issue by xronggong** [kassambara/survminer#165]
### Expected behavior 
ggcoxzph(test.ph)
This should plot a graph graphical diagnostic

### Actual behavior
But it gives an error "Error: could not find function "ggcoxzph""

### Steps to reproduce the problem
library(survminer)
Loading required package: ggplot2
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘gtable’
Error: package ‘ggplot2’ could not be loaded
### `session_info()`
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] expm_0.999-1    optR_1.2.5      htmlTable_1.9   chron_2.3-50    zoo_1.7-14      Matrix_1.2-8   
[7] survival_2.40-1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9     lattice_0.20-34 digest_0.6.12   withr_1.0.2     grid_3.3.3      R6_2.2.0       
 [7] backports_1.0.5 magrittr_1.5    git2r_0.18.0    httr_1.2.1      stringi_1.1.2   curl_2.3       
[13] checkmate_1.8.2 devtools_1.12.0 splines_3.3.3   tools_3.3.3     stringr_1.2.0   htmlwidgets_0.8
[19] htmltools_0.3.5 memoise_1.0.0   knitr_1.15.1  
````{R}
# please paste here the result of
devtools::session_info()
Session info -----------------------------------------------------------------------------------------------
 setting  value                         
 version  R version 3.3.3 (2017-03-06)  
 system   x86_64, mingw32               
 ui       RStudio (1.0.136)             
 language (EN)                          
 collate  Chinese (Simplified)_China.936
 tz       Europe/Berlin                 
 date     2017-03-07                    

Packages ---------------------------------------------------------------------------------------------------
 package     * version date       source        
 backports     1.0.5   2017-01-18 CRAN (R 3.3.2)
 checkmate     1.8.2   2016-11-02 CRAN (R 3.3.2)
 chron       * 2.3-50  2017-02-20 CRAN (R 3.3.2)
 curl          2.3     2016-11-24 CRAN (R 3.3.2)
 devtools      1.12.0  2016-06-24 CRAN (R 3.3.2)
 digest        0.6.12  2017-01-27 CRAN (R 3.3.2)
 expm        * 0.999-1 2017-02-02 CRAN (R 3.3.2)
 git2r         0.18.0  2017-01-01 CRAN (R 3.3.2)
 htmlTable   * 1.9     2017-01-26 CRAN (R 3.3.2)
 htmltools     0.3.5   2016-03-21 CRAN (R 3.3.2)
 htmlwidgets   0.8     2016-11-09 CRAN (R 3.3.2)
 httr          1.2.1   2016-07-03 CRAN (R 3.3.2)
 knitr         1.15.1  2016-11-22 CRAN (R 3.3.2)
 lattice       0.20-34 2016-09-06 CRAN (R 3.3.3)
 magrittr      1.5     2014-11-22 CRAN (R 3.3.2)
 Matrix      * 1.2-8   2017-01-20 CRAN (R 3.3.3)
 memoise       1.0.0   2016-01-29 CRAN (R 3.3.2)
 optR        * 1.2.5   2016-11-29 CRAN (R 3.3.2)
 R6            2.2.0   2016-10-05 CRAN (R 3.3.2)
 Rcpp          0.12.9  2017-01-14 CRAN (R 3.3.2)
 stringi       1.1.2   2016-10-01 CRAN (R 3.3.2)
 stringr       1.2.0   2017-02-18 CRAN (R 3.3.2)
 survival    * 2.40-1  2016-10-30 CRAN (R 3.3.3)
 withr         1.0.2   2016-06-20 CRAN (R 3.3.2)
 zoo         * 1.7-14  2016-12-16 CRAN (R 3.3.2)
````

**Comment by kassambara** [comment]
Hi,

Have you tried to install the latest developmental version of survminer? using this:

```r
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/survminer", build_vignettes = FALSE)
```


If yes AND if it still fails,

then you are may be victim of install.packages.check.source options which cause R to try install package from sources if sources are newer than binary.



Please try the following steps:
  

**I- Install gtable first**
<h/>

```r
# Use this on windows
install.packages("gtable", type="win.binary") 

# Or use this on MAC OSX
install.packages("gtable", type="mac.binary") 
```
 
**II - Install survminer**
<hr/>

```r
if(!require(devtools)) install.packages("devtools")
devtools::instal_github("kassambara/survminer")
```

Please, let me know if it works, so that we can close this issue.

**Comment by xronggong** [comment]
Hi,

I have followed the steps I and II to reinstall the package but the problem
remains.
Could you look into it further?

Regards,


Met vriendelijke groet,
Xinrong Gong
Tel nr: 0646443662

**Comment by pbiecek** [comment]
@xronggong what is the output from
```
 install.packages("gtable")
 library("gtable")
```

**Comment by kassambara** [comment]
@xronggong, did you try this:

```r
 install.packages("gtable")
 library("gtable")
```
as suggested by @pbiecek

**Comment by xronggong** [comment]
See the output from the R console
> library("gtable")
> library(survminer)
Loading required package: ggplot2
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck
= vI[[j]]) :
  there is no package called ‘munsell’
Error: package ‘ggplot2’ could not be loaded

Met vriendelijke groet,
Xinrong Gong
Tel nr: 0646443662

**Comment by kassambara** [comment]
This issue is related to your R installation , but not related to survminer.

It seems that some ggplot2 dependencies are not installed.

Please, try to re-install/load ggplot2 and let us know if it works.

Start a new R session and type this:

```r
remove.packages(c("ggplot2", "gtable"))
install.packages("ggplot2", dependencies = TRUE)

library("ggplot2")
```

A similar issue has been posted on this forum: http://stackoverflow.com/questions/31717850/error-package-or-namespace-load-failed-for-ggplot2-and-for-data-table

**Comment by xronggong** [comment]
Hi, with your help I have reinstalled several package related to ggplot2
and now the survminer can be loaded without message. The problem has been
solved.

Thanks a lot.

Regards,
Xinrong Gong

Met vriendelijke groet,
Xinrong Gong

**Comment by kassambara** [comment]
Oh, great! so we can close this issue

**Comment by robyjos** [comment]
Hi Kassambara, 
I am unable to install survminer on the linux platform : R version 3.6.3 (2020-02-29), Platform: x86_64-pc-linux-gnu (64-bit). I get the following error messages.
ERROR: compilation failed for package ‘gridtext’
ERROR: dependency ‘gridtext’ is not available for package ‘ggtext’
ERROR: dependency ‘ggtext’ is not available for package ‘survminer’

I have tried all the fixes suggested in the thread above.

Regards
Roby

**Comment by lkowarski2** [comment]
@robyjos , I have the same problem when trying to install survminer on linux platform. Did you ever find a solution?  https://github.com/kassambara/survminer/issues/165#issuecomment-913899668
