### ISSUE TITLE
New feature: plots for competing risks

### ISSUE THREAD

**Issue by pbiecek** [kassambara/survminer#168]
Plots that handle multiple stat models:
- based on geom_area (as suggested by @teigentler)
- ggplot that replicates plot from cuminc{cmprsk} and handles grouping variables

Suggested name: ggcompetingrisks (fell free to prose something else in comments).

**Comment by kassambara** [comment]
ggcompetingrisks() sounds good for me.

**Comment by pbiecek** [comment]
Submitted as #169. CIC are implemented for `cuminc` objects and `survfitms` (as suggested by @teigentler)

Both types of plots support grouping variable as a separate facets.

<img width="1040" alt="screen shot 2017-03-14 at 00 29 21" src="https://cloud.githubusercontent.com/assets/4624318/23879818/d98dc61e-084f-11e7-8987-d670f4f187b5.png">
<img width="637" alt="screen shot 2017-03-13 at 22 15 23" src="https://cloud.githubusercontent.com/assets/4624318/23879819/dbc5e11e-084f-11e7-822a-4cdc3d264adc.png">

**Comment by kassambara** [comment]
Thank you for this outstanding work!!

**Comment by teigentler** [comment]
Perfect. Thank you!
