### ISSUE TITLE
Other tests than log-rank for testing survival curves and Log-rank test for trend

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#17]
There are more possibilities than log-rank test for comparing survival curves. One are more vulnerable for early differences and one are more vulnerable for late differences. There are few popular tests, check this : http://stats.stackexchange.com/a/172976/49793

Do you think this is possible to implement more comparing tests and allow user to specify the p-value of which test he would like to add to the survplot?

**Comment by kassambara** [comment]
I'll work on that!
Thanks!

**Comment by MarcinKosinski** [comment]
You could provide p-value value and the name of used test (above the value of p-value) :)

**Comment by kassambara** [comment]
Thank you in advance Marcin :-)!

**Comment by MarcinKosinski** [comment]
Related with #15 ?

**Comment by kassambara** [comment]
I think that it's useful to have also the option to add logrank test for trend!

**Comment by MarcinKosinski** [comment]
I've closed #15 since those topics were almost the same :)

**Comment by MarcinKosinski** [comment]
Will update a functionality for this tomorrow

**Comment by MarcinKosinski** [comment]
proposition for this functionality is in the #127

**Comment by MarcinKosinski** [comment]
Log-rank tests for trend moved to https://github.com/kassambara/survminer/issues/188

**Comment by rizmalik** [comment]
Hello
I think this is a related question...
Can anyone tell me if there is a way to compare the survival for 2 curves at give time points (1 year, 2 years etc) in Survminer?
Thanks
