### ISSUE TITLE
Y-axis intervals

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#170]
A comment from my blog http://disq.us/p/1gzd5wr

Thank you for such a detailed syntax and comments, very appreciated. Though, I wanted to change Y-axis intervals from default 0.25 to 0.20, but couldn't find how. Any way to achieve it in ggsurvplot?

Then <legend.labs=c("no chest="" pain",="" "chest="" pain")=""> didn't work either, I'm getting error message that I don't understand:

"Warning message:
In if (value %in% columns) { :
the condition has length > 1 and only the first element will be used"

Also Y-axis break could be handy, as well as an option for the Survival line width.

**Comment by kassambara** [comment]
New argument `break.y.by` added in `ggsurvplot()`.



```r
# Fit survival curves
require("survival")
fit<- survfit(Surv(time, status) ~ sex, data = lung)
  
# Basic survival curves
library(survminer)
ggsurvplot(fit, data = lung,
           legend.labs = c("Male", "female"),
           break.y.by = 0.2, # Y axis breaks
           size = 1.5 # line width
           )
```

**Comment by MarcinKosinski** [comment]
@kassambara you are amazingly fast : ) Thanks for this upgrade

**Comment by arunvv90** [comment]
It is not working in case of percentage is plotted in y axis
kmbcahv2ndplot <- ggsurvplot(kmbcahv2nd,
    size = 2, 
    fun = "pct",
    conf.int = TRUE,
    linetype = "strata", 
    surv.median.line = "hv", 
    ggtheme = theme_light(),
    xlab = "Time in Days",
    ylab = "Survival (%)",
    break.y.by = 20,
    
)
