### ISSUE TITLE
ggsurvplot: Setting x-axis in log scale when plotting the complementary log−log function 

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#171]
(e-mail from a user)

I have a quick question. When plotting the complementary log−log function (ggsurvplot(fit, fun = "cloglog") I would like to have the possibility to put the log scale on the x-axis (default in survival:::plot.survfit()).

**Comment by kassambara** [comment]
fixed now:

```r
require("survival")
require("survminer")
fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurvplot(fit, data = lung, fun = "cloglog")
```


![rplot03](https://cloud.githubusercontent.com/assets/3313355/24323205/b13dc804-1172-11e7-9254-df28d06254f6.png)

**Comment by fthielen** [comment]
Since one of the newer versions this plot is not rendering anymore and instead I get the following warning message for:

```
require("survival")
require("survminer")
fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurvplot(fit, data = lung, fun = "cloglog")


Warning messages:
1: Transformation introduced infinite values in continuous x-axis 
2: Transformation introduced infinite values in continuous x-axis 
```

**Comment by kassambara** [comment]
it works on my computer using the latest dev version of survminer

**Comment by fthielen** [comment]
I tried the same snippet on another computer (Mac) just now under survminer version 0.4.4, 0.4.5 and the dev version 0.4.5.999 and I get the same error message in all versions.

My RStudio version is 1.2.1335 and my R version is 3.6.1

**Comment by raheems** [comment]
The fun='loglog' is supposed to transform the x axis to a log(x) which does not happen.

**Comment by kurttaylor** [comment]
Following on from @raheems comment - the x-axis is not logged. How do we do this (example [here](https://www.researchgate.net/figure/Log-cumulative-Hazard-Plots-of-Overall-Survival-and-Progression-free-Survival-of-Eribulin_fig1_336707509))? @kassambara
