### ISSUE TITLE
Error with specifying legend position via a numeric vector

### ISSUE THREAD

**Issue by mluu921** [kassambara/survminer#173]
I'm having an issue applying a legend coordinate position using the 'legend' argument within theme_survminer. 

Although the documentation allows for specification of a legend position using a numeric vector - the newest development version of survminer only allows a character argument.

Error in match.arg(legend) : 'arg' should be one of “top”, “bottom”, “left”, “right”, “none”

I've tried with both the current development version of survminer as well as the current version on cran.

**Comment by kassambara** [comment]
fixed now, thanks
