### ISSUE TITLE
Warning Message From CRAN 

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#175]
(From CRAN)

submission survminer 0.3.0 

And this still fails under R-oldrelease.

I sent you two mails for the previous version that you should eitehr fix or declare proper version dependencies.

Please see
https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/survminer-00check.html

And submit a fixed version NOW.

Best,
Uwe Ligges

**Comment by kassambara** [comment]
I sent  an email.

Discussion with CRAN:


**Me:** I’m really sorry for this issue. I specified in the ‘suggests’ field that  the Bioconductor  packages RTCGA(>= 1.4.0) & RTCGA.clinical(>= 20151101.4.0) are required for survminer.


**CRAN:** 
Ah, these are suggested. In that case you would have to make sure that the version dependency is fullfilles before using the package.

**Me:** Would you be so kind to update the RTCGA & RTCGA.clinical packages on  R-oldrelease?

**CRAN:**
No, as the BioC version associated with R-3.2.5 is 3.2 which does not have these packages. So we simply do not ship survminer for R.3,2,x then?

**Comment by kassambara** [comment]
The error appears in the ggcoxdiagnostics() function and in the vignette file (Informative_Survival_Plots.Rmd). We should fix this and submit it now, otherwise survminer will be removed from CRAN.

@MarcinKosinski Would you please suggest a fix for this issue?

**Comment by kassambara** [comment]
A solution might be:

i) to  add the BRCAOV.survInfo dataset in the survminer package and 

ii) to provide an R script to extract this data set from RTCGA.clinical package with the option \donttest{} in  ggcoxdiagnostics()  example section and {r, eval = FALSE} in the vignette file.

What do you think?

**Comment by MarcinKosinski** [comment]
Do you know where I can check which versions of  RTCGA / RTCGA.clinical are on the Bioconductor?
I can only see that for 3.4 https://bioconductor.org/packages/release/bioc/html/RTCGA.html it is version 1.4.0 : /


In the error there is version 

````{R}
Welcome to the RTCGA (version: 1.0.2).
````

This is so old version : | where there were only few functions. Or we might remove RTCGA / RTCGA.clinical from survminer

**Comment by kassambara** [comment]
We don't need to remove RTCGA/RTCGA.clinical from the vignette file. Give me 2 mns to commit a modification of the vignette file.

However, to simplify the ggcoxdiagnostics() example section, It would be better to keep only the traditional example: http://www.sthda.com/english/rpkgs/survminer/reference/ggcoxdiagnostics.html

**Comment by MarcinKosinski** [comment]
Ok, let's simplify ggcoxdiagnostics.
I didn't like the idea to remove RTCGA/RTCGA.clinical so if you have
solution then please rescue those packages!

2017-03-20 10:03 GMT+01:00 Alboukadel KASSAMBARA <notifications@github.com>:

**Comment by kassambara** [comment]
should pass CRAN check now on oldrelease

**Comment by MarcinKosinski** [comment]
How can we have backward compatibility with the state of dependent packages
from last year where there were no survivalTCGA() function : |
this is a complete miss-understanding for me, where from that time
(04-2016) Bioconductor had 2 releases and RTCGA jumped from 1.02 to 1.2.0
and then to 1.4.0 : /

Maybe there will be a day in which RTCGA could be included in survminer
again. Thanks Alboukadel for your work and support.

2017-03-20 11:31 GMT+01:00 Alboukadel KASSAMBARA <notifications@github.com>:

**Comment by kassambara** [comment]
survminer 0.3.1 uploaded on CRAN now:-)!

**Comment by MarcinKosinski** [comment]
0.3.0 or 0.3.1 : ) ? https://cran.r-project.org/web/packages/survminer/index.html

**Comment by kassambara** [comment]
It's 0.3.1. I uploaded it but not yet available on CRAN. Should take 24-48h.
