### ISSUE TITLE
Change the shape of censored events

### ISSUE THREAD

**Issue by mingrisch** [kassambara/survminer#186]
### Expected behavior 

A question on stackoverflow raised the issue of changing the shape of censored events, e.g. from "+" to "|".
The horizontal bar of the "+" is often not aligned to the line in Kaplan Meier curves. I had this issue myself, and I would much appreciate such a solution - without breaking anything else.

**Comment by kassambara** [comment]
Thank you for pointing this out! I also added now a new argument `censor.size`. Default is 3.5.
