### ISSUE TITLE
Log-rank tests for trend

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#188]
Due to the email

> Dear Marcin and Alboukadel,
 
> I am a cancer researcher working on biomarkers and is currently eager to take advantage of R to perform more advanced and effective survival analyses. I was recently thrilled to discover the survminer package which I think is excellent; great work. I have one specific question regarding how to perform log rank test for trend? This is important to my research since biomarker data are often ordinal. I am a novice in R, and is unfortunately not able to find any R documentation for how to perform logrank test for trend in the survminer package, although I found an issue where the both of you touched upon it (“Other tests than log-rank for testing survival curves and Log-rank test for trend #17”), but was not able to find out whether the issue was solved or not. I would be sincerely grateful if you could suggest a solution to this since I really would like to start using this package for all my future survival analyses.

I am creating an issue for that (even though we had a long time ago an issue for that - https://github.com/kassambara/survminer/issues/17).

**Comment by kassambara** [comment]
The following example from the vignette (http://www.sthda.com/english/rpkgs/survminer/articles/Specifiying_weights_in_log-rank_comparisons.html) works:


```r
library("survival")
library(survminer)
data("kidney", package="KMsurv")
fit1 <- survfit(Surv(time=time, event=delta) ~ type, data=kidney)
ggsurvplot(fit1, data = kidney, pval = TRUE, log.rank.weights = "S1")
```
   
P-values from survMisc

```r
library(survMisc)
tenfit <- ten(Surv(time=time, event=delta) ~ type, data=kidney)
capture.output(comp(tenfit)) -> null_dev
attributes(tenfit)$lrt -> tests
tests
```

<pre>
                     Q         Var         Z     pNorm   
1             -3.96355     6.23675 -1.587104 0.1124892   
n              9.00000 38919.18761  0.045621 0.9636127   
sqrtN        -13.20293   433.84450 -0.633875 0.5261626   
S1            -2.46920     4.37254 -1.180837 0.2376674   
S2            -2.31343     4.20869 -1.127672 0.2594583   
FH_p=1_q=1    -1.02064     0.10661 -3.125846 0.0017729 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
</pre>
    
<span style = "color:green;">Observation: The pNorm column is present</span>

**But, the example below, using another dataset, doesn't work**:

```r
library(survival)
library(survminer)
data("larynx", package="KMsurv")
fit2 <- survfit(Surv(time, delta) ~ stage, data=larynx)
ggsurvplot(fit2, data = larynx, log.rank.weights = "S1", pval = TRUE)
```

Error message:
  
<pre style = "color:red;">
Error in round(tests$pNorm[tests$W == method], 4) : 
  argument non numérique pour une fonction mathématique
</pre>
  
  

P-values from survMisc

```r
library(survMisc)
tenfit <- ten(Surv(time, delta) ~ stage, data=larynx)
capture.output(comp(tenfit)) -> null_dev
attributes(tenfit)$lrt -> tests
tests
```

<pre>
           chiSq df     pChisq    
1          22.763  3 4.5252e-05 ***
n          23.177  3 3.7093e-05 ***
sqrtN      23.141  3 3.7746e-05 ***
S1         23.171  3 3.7199e-05 ***
S2         23.170  3 3.7213e-05 ***
FH_p=1_q=1 16.661  3 0.00082967 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
</pre>

<span style = "color:red;">Observation: The pNorm column is not present</span>

**Comment by MarcinKosinski** [comment]
So we have 2 issues now here : ) ?

**Comment by kassambara** [comment]
We can add the argument test.for.trend = FALSE/TRUE  in `surv_pvalue()` function used by `ggsurvplot`() to compute survival pvalues. I can d this

**Comment by kassambara** [comment]
I can do this if you're not working on it...

**Comment by MarcinKosinski** [comment]
Please feel free to work on that, I am having to much R recently.

**Comment by kassambara** [comment]
New option `test.for.trend` added in `ggsurvplot()` to perform a log-rank test for trend. logical value. Default is FALSE. If TRUE, returns the test for trend p-values.

**Comment by MarcinKosinski** [comment]
Thank you! Good job
