### ISSUE TITLE
custom p-value on the ggsurvplot

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#189]
One can specify `pval = TRUE/FALSE` in the `ggsurvplot` as a logical value.
Let also make this possible to be specified as a numeric value, that will be passed to the plot, so that user ca n pass any p-value to the final plot of the test that he needs (e.g. log-rank test as in #188 )

**Comment by kassambara** [comment]
Good suggestion!!

**Comment by kassambara** [comment]
I can activate this option in a minute...

**Comment by kassambara** [comment]
Should work now:

```r
require("survival")
require("survminer")
fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurvplot(fit, data = lung, pval = 0.1)
```

**Comment by MarcinKosinski** [comment]
OMG : P I've been working for last 30 minutes on that : D ok never ming.
What do you think about passing `pval` as a string also?

````{R}
ggsurvplot(fit, data = lung, pval = TRUE)
ggsurvplot(fit, data = lung, pval = 0.03)
ggsurvplot(fit, data = lung, pval = "The hot p-value is: 0.031")
```

**Comment by kassambara** [comment]
Oh sorry... A good idea for pval = character...  Wainting your pull request ...

Thanks:-)!

**Comment by MarcinKosinski** [comment]
PR is here - https://github.com/kassambara/survminer/pull/193 
This issue can be closed.

**Comment by kassambara** [comment]
Thanks @MarcinKosinski! I tested and it works like charm:-)
