### ISSUE TITLE
Specific p-value for each facet

### ISSUE THREAD

**Issue by jarbru** [kassambara/survminer#190]
Is there a possibility in the survminer package to generate specific p-values for each facet/subgroup?

**Comment by kassambara** [comment]
Interesting challenge :-)!  We'll work on this.

This blog post might help: https://www.r-bloggers.com/annotated-facets-with-ggplot2/

**Comment by jarbru** [comment]
Fantastic, highly appreciated!

**Comment by kassambara** [comment]
I wrote an R code to plot this:

![rplot06](https://cloud.githubusercontent.com/assets/3313355/25005431/41ecb0f0-2059-11e7-8e29-d0e77b40514a.png)
   
I think that, we need a new function, say `mggsurvplot()`,  to create a multi-panel survival curves.

The simplified format would look like this `mggsurvplot(fit, data,  groupby = "var1", ...)` or this  mggsurvplot(fit, data,  groupby = c("var1", "var2"), ...).

The `groupby` option will be used to create panels by one or two grouping variables.

`mggsurvplot()` should be a wrapper function, which applies the ggsurvplot() function to each of the data subsets grouped by the argument `groupby`.

some users might want also to display a specific risk table for each panel.

R code to reproduce the plot above:

```r
library(survival)
library(survminer)
library(tidyverse)

fit <- survfit( Surv(time, status) ~ sex + rx + adhere,
                 data = colon )

# Survival curves
ggsurv <- ggsurvplot(fit, data = colon, color = "sex", palette = "jco",
                     conf.int = TRUE, legend.title = "sex") %>%
  .$plot + facet_grid(rx ~ adhere, labeller = label_both)
   

# Create a nested data
nested_data <- colon %>% 
  group_by(rx, adhere) %>% 
  nest()

# Compute survdiff on each subset
# Helper function
surv_diff<- function(df){
  sdiff <- survdiff(Surv(time, status) ~ sex, data = df)
  pvalue <- pchisq(sdiff$chisq, length(sdiff$n) - 1, lower.tail = FALSE)
  pvalue
}

nested_data <- nested_data %>%
  mutate(pval = map_dbl(nested_data$data, surv_diff)) 

# Pvalues of each panel
pvals <- nested_data %>% select(rx, adhere, pval)
# Add pval coordinate
pvals <- pvals %>% 
  mutate(x = 1000, y = 0.25)

# Add pvalues to each panel
ggsurv2 <- ggsurv +
geom_text(data=pvals, aes(x=x, y=y,
label = paste('P-value:', format.pval(pval, digits=1))))

# final plot
ggsurv2
```

**Comment by kassambara** [comment]
To add a risk table on each panel:

1. Create a nested data
2. Map `survfit()` to each nested data --> Returns a list of fits
3. Map `ggsurvplot(..., risk.table = TRUE)` to each fit object --> Returns a list of ggsurvplots
4. Arrange ggsurvplots using `arrange_ggsurvplots()

The R code would look like this:

```r
library(survival)
library(survminer)
library(tidyverse)


# Nested data
nested_data <- colon %>% 
  group_by(rx, adhere) %>% 
  nest()

# Survfit on each subset
surv_fit <- function(df){
  survfit( Surv(time, status) ~ sex,
                 data = df )
}
nested_data <- nested_data %>%
  mutate(fit = map(nested_data$data, surv_fit)) 

## ggsurvplot on each subset
.ggsurvplot <- function(fit, data){
  ggsurvplot(fit, data, tables.theme = theme_cleantable(),
             ggtheme = theme_light(), palette = "jco",
             pval = TRUE, conf.int = TRUE, risk.table = TRUE)
}

nested_data <- nested_data %>%
  mutate(ggsurv = map2(nested_data$fit, nested_data$data, .ggsurvplot ))

#nested_data$ggsurv
arrange_ggsurvplots(nested_data$ggsurv, nrow = 3)
```

**Comment by fkgruber** [comment]
thanks for the workaround.  

Are you planning to adding this fix to your code so that we can get pvalues for each facet when we use the pval=T option?  Because that would be the ideal

**Comment by fkgruber** [comment]
also where is arrange_ggsurvplots?

thanks
Fred

**Comment by kassambara** [comment]
yes, the plan is to come with a simple solution with less typing.

arrange_ggsurvplots() is in survminer package.

**Comment by jarbru** [comment]
Workaround or not, this code really helps a lot when exploring, processing and reporting data using survival datasets with a large number of clinicopathological and molecular covariates. All further improvements to the survminer package are naturally highly appreciated, but it is already pretty fantastic. Great work!

**Comment by kassambara** [comment]
Oh great, I'm happy that the suggested code helps.

I think that, we need simple verbs to make thing easy for health scientists with non-advanced R programming background.

I'm wondering whether we should create a new `surv_fit()`  function , which can support a grouped data in addition to the traditional way of computing survfit.  `surv_fit()` should be a wrapper that applies survfit() to each subset, in the situation where the data is grouped by one or two variables. 

Simplified formats:  
   
```r
# Multiple Panel Survival Curves
#%%%%%%%%%%%%%%%%%%%%%%%

# Verbs
#...................................................
# Create grouped data sets by one or more variables
goupby(data, var1, ...)  

# Wrappers of survdiff() and survfit()
# Accept grouped data and output a list in this case
surv_diff(formula, data, subset, groupby) 
surv_fit(formula, data, subset, groupby)


#  Muliple panel survival curves
#...................................................
data %>%
  groupby(var1, var2) %>% # 1. Create subsets of data grouped by var1 and/or var2
  surv_fit(formula, .) %>%   #  2. Apply survfit to each subset --> list of fits
  ggsurvplot()            %>%  #  3. Aplply ggsurvplot to each fit  --> list of ggsurvplots
  arrange_ggsurvplots(ncol = 2) # 4. Optionally arrange ggsurvplots to create multi-panel surv curves


#  Muliple panel surv diff
data %>%
groupby() %>%
  surv_diff(formula, .) # ----> List of survdiffs
```

What do you think about that @MarcinKosinski  @pbiecek ?

Ps: the term "Multi-Panel Survival Curves" might not be the best appropriate term. Welcome to any suggestion.

**Comment by MarcinKosinski** [comment]
There isn't a better solution, since you pass the `fit` object to the `ggsurvplot`.
I don't see a way in which we could simply add `ggsurvplot(group.by = c("var1", "var2")` parameter.
So the `surv_fit` sound reasonable

**Comment by kassambara** [comment]
I'll work work on that to see if we can easily implement `ggsurvplot(group.by = c("var1", "var2"))` instead of creating a new function

**Comment by MarcinKosinski** [comment]
If you have a data from `fit` and `formula` from a fit, the it might be
even doable.

if (!is.null(group.by)) {
fit <-
fit$data %>%
 group_by(!!group.by) %>% # available from dplyr 0.6.0 - 11th May
 .surv_fit()
}

2017-04-20 15:48 GMT+02:00 Alboukadel KASSAMBARA <notifications@github.com>:

**Comment by kassambara** [comment]
Yes,  this should work. I'm modifying the `ggsurvplot()` so that it can handle the argument group.by

**Comment by kassambara** [comment]
see issue https://github.com/kassambara/survminer/issues/205
