### ISSUE TITLE
ggsurvplot fails when risk.table=T

### ISSUE THREAD

**Issue by statsbykd** [kassambara/survminer#192]
### Expected behavior 
Adding risk.table = TRUE would result in a risk table printed along with the KM curves.

### Actual behavior
Adding risk.table = TRUE results in failure to plot and error message provided below.  The problem seems to be associated with a failure in the package ggpubr which is listed in the error.

### Steps to reproduce the problem
fit <- survfit(Surv(time, status) ~ sex, data = lung)
ggsurvplot(fit, data = lung)
ggsurvplot(fit, data = lung,  risk.table = TRUE )

### error message received:
Error in ggpubr:::.labs(p, font.main = extra.params$font.risk.table.title,  : 
  unused arguments (submain = extra.params$risk.table.subtitle, caption = extra.params$risk.table.caption, font.submain = extra.params$font.risk.table.subtitle, font.caption = extra.params$font.risk.table.caption)

### `session_info()`
Session info --------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.3 (2017-03-06)
 system   i386, mingw32               
 ui       RStudio (0.99.903)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2017-04-14                  

Packages ------------------------------------------------------------------------------------------------------
 package      * version date       source        
 acepack        1.4.1   2016-10-29 CRAN (R 3.3.2)
 assertthat     0.1     2013-12-06 CRAN (R 3.3.2)
 backports      1.0.5   2017-01-18 CRAN (R 3.3.2)
 base64enc      0.1-3   2015-07-28 CRAN (R 3.3.2)
 broom          0.4.2   2017-02-13 CRAN (R 3.3.3)
 checkmate      1.8.2   2016-11-02 CRAN (R 3.3.2)
 class          7.3-14  2015-08-30 CRAN (R 3.3.3)
 cluster        2.0.5   2016-10-08 CRAN (R 3.3.3)
 cmprsk         2.2-7   2014-06-17 CRAN (R 3.3.3)
 codetools      0.2-15  2016-10-05 CRAN (R 3.3.3)
 colorspace     1.3-1   2016-11-18 CRAN (R 3.3.2)
 data.table     1.10.0  2016-12-03 CRAN (R 3.3.2)
 DBI            0.5-1   2016-09-10 CRAN (R 3.3.2)
 devtools     * 1.12.0  2016-06-24 CRAN (R 3.3.2)
 digest         0.6.10  2016-08-02 CRAN (R 3.3.2)
 dplyr          0.5.0   2016-06-24 CRAN (R 3.3.2)
 e1071          1.6-7   2015-08-05 CRAN (R 3.3.2)
 foreach      * 1.4.3   2015-10-13 CRAN (R 3.3.2)
 foreign        0.8-67  2016-09-13 CRAN (R 3.3.3)
 Formula      * 1.2-1   2015-04-07 CRAN (R 3.3.2)
 ggplot2      * 2.2.1   2016-12-30 CRAN (R 3.3.2)
 ggpubr       * 0.1.1   2016-12-05 CRAN (R 3.3.2)
 glmnet       * 2.0-5   2016-03-17 CRAN (R 3.3.2)
 gridExtra      2.2.1   2016-02-29 CRAN (R 3.3.2)
 gtable         0.2.0   2016-02-26 CRAN (R 3.3.2)
 Hmisc        * 4.0-2   2016-12-31 CRAN (R 3.3.2)
 htmlTable      1.9     2017-01-26 CRAN (R 3.3.1)
 htmltools      0.3.5   2016-03-21 CRAN (R 3.3.2)
 htmlwidgets    0.8     2016-11-09 CRAN (R 3.3.2)
 iterators      1.0.8   2015-10-13 CRAN (R 3.3.2)
 km.ci          0.5-2   2009-08-30 CRAN (R 3.3.2)
 KMsurv         0.1-5   2012-12-03 CRAN (R 3.3.2)
 knitr          1.15.1  2016-11-22 CRAN (R 3.3.2)
 labeling       0.3     2014-08-23 CRAN (R 3.3.2)
 lattice      * 0.20-34 2016-09-06 CRAN (R 3.3.3)
 latticeExtra   0.6-28  2016-02-09 CRAN (R 3.3.2)
 lazyeval       0.2.0   2016-06-12 CRAN (R 3.3.2)
 magrittr       1.5     2014-11-22 CRAN (R 3.3.2)
 MASS           7.3-45  2016-04-21 CRAN (R 3.3.3)
 Matrix       * 1.2-8   2017-01-20 CRAN (R 3.3.3)
 MatrixModels   0.4-1   2015-08-22 CRAN (R 3.3.2)
 memoise        1.0.0   2016-01-29 CRAN (R 3.3.2)
 mnormt         1.5-5   2016-10-15 CRAN (R 3.3.2)
 multcomp       1.4-6   2016-07-14 CRAN (R 3.3.2)
 munsell        0.4.3   2016-02-13 CRAN (R 3.3.2)
 mvtnorm        1.0-5   2016-02-02 CRAN (R 3.3.2)
 nlme           3.1-131 2017-02-06 CRAN (R 3.3.3)
 nnet           7.3-12  2016-02-02 CRAN (R 3.3.3)
 plyr           1.8.4   2016-06-08 CRAN (R 3.3.2)
 polspline      1.1.12  2015-07-14 CRAN (R 3.3.2)
 psych          1.6.12  2017-01-08 CRAN (R 3.3.2)
 quantreg       5.29    2016-09-04 CRAN (R 3.3.2)
 R6             2.2.0   2016-10-05 CRAN (R 3.3.2)
 RColorBrewer   1.1-2   2014-12-07 CRAN (R 3.3.2)
 Rcpp           0.12.8  2016-11-17 CRAN (R 3.3.2)
 readstata13  * 0.8.5   2016-09-09 CRAN (R 3.3.2)
 reshape2       1.4.2   2016-10-22 CRAN (R 3.3.2)
 rms          * 5.1-0   2017-01-01 CRAN (R 3.3.2)
 rpart          4.1-10  2015-06-29 CRAN (R 3.3.3)
 rstudioapi     0.6     2016-06-27 CRAN (R 3.3.2)
 sandwich       2.3-4   2015-09-24 CRAN (R 3.3.2)
 scales         0.4.1   2016-11-09 CRAN (R 3.3.2)
 SparseM      * 1.74    2016-11-10 CRAN (R 3.3.2)
 stringi        1.1.2   2016-10-01 CRAN (R 3.3.2)
 stringr        1.1.0   2016-08-19 CRAN (R 3.3.2)
 survey         3.31-5  2016-12-01 CRAN (R 3.3.2)
 survival     * 2.40-1  2016-10-30 CRAN (R 3.3.2)
 survminer    * 0.3.1   2017-03-21 CRAN (R 3.3.3)
 survMisc       0.5.4   2016-11-23 CRAN (R 3.3.2)
 tableone     * 0.7.3   2015-11-11 CRAN (R 3.3.2)
 TH.data        1.0-8   2017-01-23 CRAN (R 3.3.2)
 tibble         1.2     2016-08-26 CRAN (R 3.3.2)
 tidyr          0.6.1   2017-01-10 CRAN (R 3.3.2)
 withr          1.0.2   2016-06-20 CRAN (R 3.3.2)
 xtable         1.8-2   2016-02-05 CRAN (R 3.3.2)
 zoo            1.7-13  2016-05-03 CRAN (R 3.3.2)

**Comment by kassambara** [comment]
The latest version of survminer requires ggpubr ver>=0.1.2 to work properly.

It seems that you don't have the latest version (v0.1.2) of ggpubr installed .

We updated now survminer so that during the installation it will make sure that the user has ggpur v >= 0.1.2 installed

Please install the latest developmental version of survminer and ggpubr as follow:

```r
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/ggpubr")
devtools::install_github("kassambara/survminer", build_vignettes = FALSE)
```

**Comment by kassambara** [comment]
Hi @statsbykd,

Please, let me know if if this issue is fixed now, so that we can close it?

Thanks

**Comment by statsbykd** [comment]
Yes, thank you!
