### ISSUE TITLE
ggsurvplot(): Option to add 'all' patients' Survival Curves Needed

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#194]
(User request by e-mail)

- Plot survival curves of patients stratified by grouping variables
- Add on the same plot, the survival curves of 'all' patients.

A simple option to do this is needed.

related issue:  https://github.com/kassambara/survminer/issues/98

**Comment by kassambara** [comment]
New option added now in `ggsurvplot()` to add he survival curves of (all) pooled patients onto the main survival plot stratified by grouping variables.


- **Load required package and fit survival curves**:
  
```r
# Load required packages
library("survival")
library("survminer")

# Fit survival curves
fit <- surv_fit(Surv(time, status) ~ sex, data = lung)
```

- **Basic survival curves**:

```r
# Visualize survival curves
ggsurvplot(fit, data = lung, 
           risk.table = TRUE, pval = TRUE,
           surv.median.line = "hv", palette = "jco")
```

![rplot](https://cloud.githubusercontent.com/assets/3313355/25522325/cba9a8d4-2c02-11e7-92d9-11cf2a88c8d6.png)

- **Add survival curves of pooled patients**:

Use **add.all = TRUE** option
 
```r
# Add survival curves of pooled patients (Null model)
# Use add.all = TRUE option
ggsurvplot(fit, data = lung, 
           risk.table = TRUE, pval = TRUE,
           surv.median.line = "hv", palette = "jco", 
           add.all = TRUE)
```
![rplot07](https://cloud.githubusercontent.com/assets/3313355/25522407/084fff68-2c03-11e7-9483-e6485b9e40a6.png)

**Comment by lli1026** [comment]
when i use "add.all=TRUE", got a error message(Error in model.frame.default(formula = surv.object ~ strata.val, data = list( :  variable lengths differ (found for 'strata.val')), it works fine without "add.all", any ideas? Thanks,

**Comment by DeepblueLam** [comment]
> when i use "add.all=TRUE", got a error message(Error in model.frame.default(formula = surv.object ~ strata.val, data = list( : variable lengths differ (found for 'strata.val')), it works fine without "add.all", any ideas? Thanks,

i got the same error. how did you solve this?
