### ISSUE TITLE
ggsurvplot(): Plotting multiple surv objects on the same graph

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#195]
(User request by-email)

In oncology, we wish to plot time on treatment, progression free survival and overall survival on the same graph (and often also stratified by treatment assignment).

A simple solution to add multiple surv object on the same graph wanted.

The R code to generate this type of plot would look like this:

```r
ggsurvplot(c(PFS.fit, OS.fit), ...)
```

The plot would look like this:

![image002](https://cloud.githubusercontent.com/assets/3313355/25070120/5f1f5dc4-2295-11e7-8410-6688504a2121.jpg)

**Comment by kassambara** [comment]
New option `combine = TRUE` is now available in the `ggsurvplot()` function to combine a list survfit objects on the same plot. Alias of the *ggsurvplot_combine*() function.

## Load required packages 
     
  
```{r}
library("survival")
library("survminer")
```

## Create a demo data set
   
```{r}
set.seed(123)
d.demo <- data.frame(
  os.time = colon$time, 
  os.status = colon$status,
  pfs.time = sample(colon$time),
  pfs.status = colon$status,
  sex = colon$sex, rx = colon$rx, adhere = colon$adhere
)
```

## Ex1: Combine null models
 

- Compute two survival curves (PFS and OS), null models
   
```{r}
pfs <- survfit( Surv(pfs.time, pfs.status) ~ 1, data = d.demo)
os <- survfit( Surv(os.time, os.status) ~ 1, data = d.demo)
``` 
 
- Combine the two survival curves on one graph: 
   
```{r ggsurvplot-combine-null-models, fig.width=6, fig.height=6, fig.show='asis'}
fit <- list(PFS = pfs, OS = os)
ggsurvplot(fit, data = d.demo, combine = TRUE, # Combine curves
           risk.table = TRUE,                  # Add risk table
           conf.int = TRUE,                    # Add confidence interval
           conf.int.style = "step",            # CI style, use "step" or "ribbon"
           censor = FALSE,                     # Remove censor points
           tables.theme = theme_cleantable(),  # Clean risk table
           palette = "jco")
```

![rplot](https://cloud.githubusercontent.com/assets/3313355/25529139/265b78ac-2c21-11e7-9a63-a71dea9592ce.png)


    
## Ex2: Combine stratified curves
    
 
- Compute survival curves of patients stratified by treatment assignments (*rx*)
   
   
```{r}
pfs <- survfit( Surv(pfs.time, pfs.status) ~ rx, data = d.demo)
os <- survfit( Surv(os.time, os.status) ~ rx, data = d.demo)
```
    
   
- Combine the two survival curves: 
   
   
```{r ggsurvplot-combine-stratified-curves, fig.width=6, fig.height=6, fig.show='asis'}
fit <- list(PFS = pfs, OS = os)
ggsurvplot(fit, data = d.demo, combine = TRUE,     # Combine curves
          risk.table = TRUE, tables.height = 0.35, # Adjust tables height
          tables.theme = theme_cleantable(),       # Clean risk table
          censor = FALSE,                          # Remove censor points
          palette = "jco"
          )
```

![rplot08](https://cloud.githubusercontent.com/assets/3313355/25529234/8d9bc3dc-2c21-11e7-8a05-60ac3cc7a5c4.png)

**Comment by klausmiller** [comment]
Does this also work with ggflexsurvplot?

**Comment by fthielen** [comment]
I would like to do the same but with data from different sources. So my `data = d.demo` would actually need to be specified for two different data sources. (How) is this possible?

**Comment by nmolanog** [comment]
what if the two surv objects came from different data sets??

**Comment by nmolanog** [comment]
> I would like to do the same but with data from different sources. So my `data = d.demo` would actually need to be specified for two different data sources. (How) is this possible?

I am in the same situation also. I just had to create a merged data.frame from the different sources to achieve a work around

**Comment by smruti272mokal** [comment]
Thanks for the post! It was really helpful but can we show the median survival time with the use of surv.median.line which is available in ggsurvplot when we combine the graphs? I tried it but couldn't get the median survival line. Please suggest me an option for the same .

Thank you

**Comment by dimpapa85** [comment]
I want to do the same but combine an exponential survival curve with a Weibull in the same graph. Any idea how to do it?

**Comment by TinkaJ** [comment]
I am trying to combine 3 null models in one graph, but it doesn't work.

Ex1: Combine 3 null models
Compute two survival curves (PFS and OS), null models
pfs <- survfit( Surv(pfs.time, pfs.status) ~ 1, data = d.demo)
os <- survfit( Surv(os.time, os.status) ~ 1, data = d.demo)
third <- survfit( Surv(thi.time, thi.status) ~ 1, data = d.demo)

Combine three survival curves on one graph:
fit <- list(PFS = pfs, OS = os) of fit <- list(pfd, os, third) <- it seems there are only 2 arguments here?
