### ISSUE TITLE
ggsurvplot() and axes offset from the origin

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#196]
(User request by e-mail)

ggsurvplot follow the standard R/ggplot convention of having the axes offset from the origin (I have never understood why this is the case – since basic mathematics you always show x=y=0 as the origin). Normally I would get around this by using yaxs="i" in plot, and I believe there is a similar way with expand limits in ggplot, however when I do this, the axis disappears.
 
Normally it is a bit of an annoyance, but with Kaplan-Meier plots is actually quite critical – after all we want to see when survival hits y=0 – with the values offset and a large number of patients you aren’t sure if it has hit 0, or there is still someone left! Any advice would be great, and even better if the default in the package was changed at the next update, as those who would want it offset must be in a minority i.e. nobody. Also if someone isn’t fussy, they should get the more accurate version!

**Comment by kassambara** [comment]
This has been fixed now:

```r
library(survival)
library(survminer)

# Basic survival curves
fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurvplot(fit, data = lung, risk.table = TRUE,
           tables.theme = theme_cleantable())
```

![rplot09](https://cloud.githubusercontent.com/assets/3313355/25532216/e17dc080-2c2c-11e7-87d7-feda3b1642da.png)

**Comment by kassambara** [comment]
New argument `axes.offset` added.  logical value. Default is TRUE. If FALSE, set the plot axes to start at the origin.

**Comment by ShixiangWang** [comment]
Hello, @kassambara  How can I make sure the 100% in the figure ?

![image](https://user-images.githubusercontent.com/25057508/40904272-c664cb96-680c-11e8-912a-fdf810877f4e.png)

**Comment by akirosingh** [comment]
@ShixiangWang I was able to fix it by just increasing the y limits. ylim=c(0,1.01)

**Comment by ShixiangWang** [comment]
@akirosingh Thanks :)

**Comment by MBender1992** [comment]
Hello @kassambara,
How can I align the risk table so the number at risk for time 0 also starts at 0 and is not shifted to the right?

**Comment by corneliushennch** [comment]
> Hello @kassambara,
> How can I align the risk table so the number at risk for time 0 also starts at 0 and is not shifted to the right when setting `axes.offset = FALSE` ?

Hey, I ran in to the same problem. The alignment of the risk.table is completely shifted, once you use axis.offset = TRUE.
