### ISSUE TITLE
Separate "legend.title" or "main" for each ggsurvplot within lapply

### ISSUE THREAD

**Issue by megha20** [kassambara/survminer#197]
library(survminer)
library(survival)
f1 <- Surv(futime, fustat) ~ resid.ds
f2 <- Surv(futime, fustat) ~ age
f <- list(f1, f2)

s <- lapply(f, function(x) do.call(survfit, list(formula = x, data = ovarian)))
lapply(s, function(x) do.call(ggsurvplot, list(fit = x, legend.title = names(f)))

The above code will generate two survival curves both with legend.title f1.
I want to them to have separate title, f1 and f2 respectively.

**Comment by kassambara** [comment]
The following solution should work.

First, install the latest developmental version of survminer:

```r
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/survminer", build_vignettes = FALSE)
````

Then, try this:

```r

library(survminer)
library(survival)
if(!require(purrr)) install.packages("purrr")
library(purrr)

# Create a list of formulas
data(colon)
f1 <- Surv(time, status) ~ sex
f2 <- Surv(time, status) ~ rx
formulas <- list(f1, f2)



# Map/apply survfit to each formula
# ====> use purrr::map()
fits <- purrr::map(formulas, survfit, data = colon )

# Map/apply ggsurvplot to two lists: fits and legend.titles
# ===> use purrr::map2()
legend.titles <- list("sex", "rx")
.ggsurvplot <- function(fit, legend.title, ...){
  ggsurvplot(fit, legend.title = legend.title, ...)
}

ggsurvs <- purrr::map2(fits,  legend.titles,
                       .ggsurvplot, data = colon )
ggsurvs

# Arrange multiple ggsurvplots on the same page (if needed)
arrange_ggsurvplots(ggsurvs)
```

**Comment by megha20** [comment]
It works fine..... except for a minor glitch... you added an extra "s" to fit and legend.title while applying map2.

Thanks a ton

**Comment by kassambara** [comment]
Oh great!!

**Comment by kassambara** [comment]
The function `ggsurvplot()` can take a list of survfit objects and produces a list of ggsurvplots, see issue https://github.com/kassambara/survminer/issues/204
