### ISSUE TITLE
Warning: replacing previous import ‘ggplot2::%+%’ by ‘survminer::%+%’ when loading 

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#200]
### Expected behavior 

One use a `survminer` as a dependent/imported package in his package without warnings.

### Actual behavior

I get the following `warning` during the CHECK

> Warning: replacing previous import ‘ggplot2::%+%’ by ‘survminer::%+%’ when loading 'RTCGA'

for all 3 platforms at Bioconductor 
http://bioconductor.org/checkResults/release/bioc-LATEST/RTCGA/

### Question

Is the `%+%` actually a good idea to be used in the survminer and ggplot2? This issue is similiar to the #199  and I think can be resolved with changing the name from `%+%` to something like `%++%`. 

`';..;'`

**Comment by kassambara** [comment]
I will change the  %+% to  %++%

**Comment by MarcinKosinski** [comment]
By the way, in which places this operator was used?

**Comment by kassambara** [comment]
fixed now:-)!
