### ISSUE TITLE
New Error when pval = TRUE in ggsurvplot

### ISSUE THREAD

**Issue by emilelatour** [kassambara/survminer#203]
### Expected behavior 

I am trying to make plots with pvalues showing. This functionality worked before. I recently updated to the new version of R (v3.4) and wonder if this may be causing the problem.

### Actual behavior

Here is the text of the error that I am getting, I will include a reproducible example below.

`Error in survdiff.fit(y, groups, strata.keep, rho) : 
  object 'Csurvdiff2' not found`

### Steps to reproduce the problem

````{R}
library(survival) 
library(survminer)

fit <- survfit(Surv(time, status) ~ sex, data = lung)

ggsurvplot(fit, data = lung)               # this produces a plot
ggsurvplot(fit, data = lung, pval = TRUE)  # this gives an error
````

### `session_info()`

````{R}
Session info --------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, mingw32             
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2017-04-27                  

Packages ------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package        * version      date       source                               
 acepack          1.4.1        2016-10-29 CRAN (R 3.3.1)                       
 assertthat       0.2.0        2017-04-11 CRAN (R 3.3.3)                       
 backports        1.0.5        2017-01-18 CRAN (R 3.3.2)                       
 base64enc        0.1-3        2015-07-28 CRAN (R 3.3.0)                       
 BiocInstaller  * 1.22.3       2016-06-26 Bioconductor                         
 broom            0.4.2        2017-02-13 CRAN (R 3.3.2)                       
 cellranger       1.1.0        2016-07-27 CRAN (R 3.3.1)                       
 checkmate        1.8.2        2016-11-02 CRAN (R 3.3.2)                       
 cluster          2.0.6        2017-03-10 CRAN (R 3.4.0)                       
 cmprsk           2.2-7        2014-06-17 CRAN (R 3.3.2)                       
 colorspace       1.3-2        2016-12-14 CRAN (R 3.3.2)                       
 curl             2.6          2017-04-27 CRAN (R 3.4.0)                       
 data.table       1.10.4       2017-02-01 CRAN (R 3.3.2)                       
 DBI              0.6-1        2017-04-01 CRAN (R 3.3.3)                       
 devtools       * 1.12.0       2016-06-24 CRAN (R 3.3.2)                       
 digest           0.6.12       2017-01-27 CRAN (R 3.3.2)                       
 dplyr          * 0.5.0        2016-06-24 CRAN (R 3.3.3)                       
 evaluate         0.10         2016-10-11 CRAN (R 3.3.1)                       
 forcats          0.2.0        2017-01-23 CRAN (R 3.3.2)                       
 foreign          0.8-68       2017-04-24 CRAN (R 3.4.0)                       
 Formula        * 1.2-1        2015-04-07 CRAN (R 3.3.0)                       
 ggplot2        * 2.2.1        2016-12-30 CRAN (R 3.3.2)                       
 ggpubr         * 0.1.2.999    2017-04-28 Github (kassambara/ggpubr@00c2938)   
 ggthemes       * 3.4.0        2017-02-19 CRAN (R 3.3.3)                       
 git2r            0.18.0       2017-01-01 CRAN (R 3.3.2)                       
 gridExtra        2.2.1        2016-02-29 CRAN (R 3.3.0)                       
 gtable           0.2.0        2016-02-26 CRAN (R 3.3.0)                       
 haven            1.0.0        2016-09-23 CRAN (R 3.3.2)                       
 highr            0.6          2016-05-09 CRAN (R 3.3.0)                       
 Hmisc          * 4.0-2        2016-12-31 CRAN (R 3.3.2)                       
 hms              0.3          2016-11-22 CRAN (R 3.3.2)                       
 htmlTable        1.9          2017-01-26 CRAN (R 3.3.2)                       
 htmltools        0.3.5        2016-03-21 CRAN (R 3.3.0)                       
 htmlwidgets      0.8          2016-11-09 CRAN (R 3.3.2)                       
 httr             1.2.1        2016-07-03 CRAN (R 3.3.1)                       
 janitor        * 0.2.1        2016-10-31 CRAN (R 3.3.3)                       
 jsonlite         1.4          2017-04-08 CRAN (R 3.3.3)                       
 km.ci            0.5-2        2009-08-30 CRAN (R 3.3.0)                       
 KMsurv           0.1-5        2012-12-03 CRAN (R 3.3.2)                       
 knitr          * 1.15.1       2016-11-22 CRAN (R 3.3.2)                       
 labeling         0.3          2014-08-23 CRAN (R 3.3.0)                       
 lattice        * 0.20-35      2017-03-25 CRAN (R 3.3.3)                       
 latticeExtra     0.6-28       2016-02-09 CRAN (R 3.3.1)                       
 lazyeval         0.2.0        2016-06-12 CRAN (R 3.3.0)                       
 lubridate        1.6.0        2016-09-13 CRAN (R 3.3.1)                       
 magrittr         1.5          2014-11-22 CRAN (R 3.3.2)                       
 Matrix           1.2-9        2017-03-14 CRAN (R 3.4.0)                       
 memoise          1.1.0        2017-04-21 CRAN (R 3.4.0)                       
 mnormt           1.5-5        2016-10-15 CRAN (R 3.3.1)                       
 modelr           0.1.0        2016-08-31 CRAN (R 3.3.1)                       
 munsell          0.4.3        2016-02-13 CRAN (R 3.3.0)                       
 nlme             3.1-131      2017-02-06 CRAN (R 3.3.2)                       
 nnet             7.3-12       2016-02-02 CRAN (R 3.4.0)                       
 plyr             1.8.4        2016-06-08 CRAN (R 3.3.1)                       
 psych            1.7.3.21     2017-03-22 CRAN (R 3.3.2)                       
 purrr          * 0.2.2        2016-06-18 CRAN (R 3.3.1)                       
 R6               2.2.0        2016-10-05 CRAN (R 3.3.1)                       
 RColorBrewer     1.1-2        2014-12-07 CRAN (R 3.3.0)                       
 Rcpp             0.12.10.2    2017-04-27 Github (RcppCore/Rcpp@feb4d7a)       
 readr          * 1.1.0        2017-03-22 CRAN (R 3.3.3)                       
 readxl         * 1.0.0        2017-04-18 CRAN (R 3.4.0)                       
 reshape2         1.4.2        2016-10-22 CRAN (R 3.3.1)                       
 rmarkdown        1.5          2017-04-26 CRAN (R 3.4.0)                       
 rpart            4.1-11       2017-03-13 CRAN (R 3.4.0)                       
 rprojroot        1.2          2017-01-16 CRAN (R 3.3.2)                       
 rstudioapi       0.6          2016-06-27 CRAN (R 3.3.1)                       
 RTCGA          * 1.2.5        2017-04-28 Bioconductor (R 3.4.0)               
 RTCGA.clinical * 20151101.2.2 2017-04-28 Bioconductor (R 3.4.0)               
 rvest            0.3.2        2016-06-17 CRAN (R 3.3.1)                       
 scales         * 0.4.1.9000   2016-11-15 Github (hadley/scales@89c2a2f)       
 stringi          1.1.5        2017-04-07 CRAN (R 3.3.3)                       
 stringr        * 1.2.0        2017-02-18 CRAN (R 3.3.3)                       
 survey           3.31-5       2016-12-01 CRAN (R 3.3.2)                       
 survival       * 2.41-3       2017-04-04 CRAN (R 3.3.3)                       
 survminer      * 0.3.1.999    2017-04-28 Github (kassambara/survminer@d2cc839)
 survMisc         0.5.4        2016-11-23 CRAN (R 3.3.3)                       
 tableone       * 0.7.3        2015-11-11 CRAN (R 3.3.2)                       
 tibble         * 1.3.0        2017-04-01 CRAN (R 3.3.3)                       
 tidyr          * 0.6.1.9000   2017-04-28 Github (hadley/tidyr@1e051d3)        
 tidyverse      * 1.1.1        2017-01-27 CRAN (R 3.4.0)                       
 viridis          0.4.0        2017-03-27 CRAN (R 3.3.3)                       
 viridisLite      0.2.0        2017-03-24 CRAN (R 3.3.3)                       
 withr            1.0.2        2016-06-20 CRAN (R 3.3.1)                       
 XML              3.98-1.6     2017-03-30 CRAN (R 3.3.3)                       
 xml2             1.1.1        2017-01-24 CRAN (R 3.3.2)                       
 xtable           1.8-2        2016-02-05 CRAN (R 3.3.1)                       
 yaml             2.1.14       2016-11-12 CRAN (R 3.3.2)                       
 zoo              1.8-0        2017-04-12 CRAN (R 3.3.3)   
````

**Comment by kassambara** [comment]
Hi, this might be related with your R version.... The source of error is the `survdiff()` function [in the `survival`  package].

This error is not reproducible with my session:

<pre>
Session info -----------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  fr_FR.UTF-8                 
 tz       Europe/Paris                
 date     2017-04-28                  

Packages ---------------------------------------------------------------------------------------------------------------------------
 package        * version   date       source                               
 assertthat       0.1       2013-12-06 CRAN (R 3.3.0)                       
 BH               1.62.0-1  2016-11-19 CRAN (R 3.3.2)                       
 broom            0.4.2     2017-02-13 CRAN (R 3.3.2)                       
 cmprsk           2.2-7     2014-06-17 CRAN (R 3.3.0)                       
 colorspace       1.3-2     2016-12-14 CRAN (R 3.3.2)                       
 data.table       1.10.4    2017-02-01 cran (@1.10.4)                       
 DBI              0.6       2017-03-09 cran (@0.6)                          
 dichromat        2.0-0     2013-01-24 CRAN (R 3.3.0)                       
 digest           0.6.12    2017-01-27 cran (@0.6.12)                       
 dplyr            0.5.0     2016-06-24 CRAN (R 3.3.0)                       
 evaluate         0.10      2016-10-11 CRAN (R 3.3.0)                       
 exactRankTests   0.8-29    2017-03-01 cran (@0.8-29)                       
 foreign          0.8-67    2016-09-13 CRAN (R 3.3.2)                       
 ggplot2        * 2.2.1     2016-12-30 CRAN (R 3.3.2)                       
 ggpubr         * 0.1.2.999 2017-04-26 Github (kassambara/ggpubr@00c2938)   
 ggrepel          0.6.5     2016-11-24 CRAN (R 3.3.2)                       
 ggsci            2.4       2017-03-08 cran (@2.4)                          
 gridExtra        2.2.1     2016-02-29 CRAN (R 3.3.0)                       
 gtable           0.2.0     2016-02-26 CRAN (R 3.3.0)                       
 highr            0.6       2016-05-09 CRAN (R 3.3.0)                       
 km.ci            0.5-2     2009-08-30 CRAN (R 3.3.0)                       
 KMsurv           0.1-5     2012-12-03 CRAN (R 3.3.0)                       
 knitr            1.15.1    2016-11-22 CRAN (R 3.3.2)                       
 labeling         0.3       2014-08-23 CRAN (R 3.3.0)                       
 lattice          0.20-34   2016-09-06 CRAN (R 3.3.2)                       
 lazyeval         0.2.0     2016-06-12 CRAN (R 3.3.0)                       
 magrittr         1.5       2014-11-22 CRAN (R 3.3.0)                       
 markdown         0.7.7     2015-04-22 CRAN (R 3.3.0)                       
 MASS             7.3-45    2016-04-21 CRAN (R 3.3.2)                       
 Matrix           1.2-8     2017-01-20 CRAN (R 3.3.2)                       
 maxstat          0.7-25    2017-03-02 cran (@0.7-25)                       
 mime             0.5       2016-07-07 CRAN (R 3.3.0)                       
 mnormt           1.5-5     2016-10-15 CRAN (R 3.3.0)                       
 munsell          0.4.3     2016-02-13 CRAN (R 3.3.0)                       
 mvtnorm          1.0-6     2017-03-02 CRAN (R 3.3.2)                       
 nlme             3.1-131   2017-02-06 CRAN (R 3.3.2)                       
 plyr             1.8.4     2016-06-08 CRAN (R 3.3.0)                       
 psych            1.6.12    2017-01-08 CRAN (R 3.3.2)                       
 purrr            0.2.2     2016-06-18 CRAN (R 3.3.0)                       
 R6               2.2.0     2016-10-05 CRAN (R 3.3.0)                       
 RColorBrewer     1.1-2     2014-12-07 CRAN (R 3.3.0)                       
 Rcpp             0.12.10   2017-03-19 cran (@0.12.10)                      
 reshape2         1.4.2     2016-10-22 CRAN (R 3.3.0)                       
 scales           0.4.1     2016-11-09 CRAN (R 3.3.2)                       
 stringi          1.1.2     2016-10-01 CRAN (R 3.3.0)                       
 stringr          1.2.0     2017-02-18 cran (@1.2.0)                        
 survival       * 2.41-3    2017-04-04 CRAN (R 3.3.2)                       
 survminer      * 0.3.1.999 2017-04-28 Github (kassambara/survminer@d2cc839)
 survMisc         0.5.4     2016-11-23 CRAN (R 3.3.2)                       
 tibble           1.3.0     2017-04-01 cran (@1.3.0)                        
 tidyr            0.6.1     2017-01-10 CRAN (R 3.3.2)                       
 xtable           1.8-2     2016-02-05 CRAN (R 3.3.0)                       
 yaml             2.1.14    2016-11-12 CRAN (R 3.3.2)                       
 zoo              1.7-14    2016-12-16 CRAN (R 3.3.2)         
</pre>

**Comment by emilelatour** [comment]
I can confirm that it does seem to be due to the new version of R. I was able to ask R Studio to use the R-3.3.3 install and things worked correctly. I'm okay for now, but a good thing to be aware of in the future.

Thanks!

**Comment by kassambara** [comment]
Oh great!! so we can close this issue..

**Comment by asmagen** [comment]
so how can I use this function?
