### ISSUE TITLE
Facet survival curves into multiple panels

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#205]

**Comment by kassambara** [comment]
New option `facet.by` added now in `ggsurvplot()` to draw multi-panel survival curves of a data set grouped by one or two variables. Alias of the `ggsurvplot_facet()` function.


## Load required packages

```{r}
library(survival)
library(survminer)
```
## Compute survival curves
    
    
```{r}
fit1 <- survfit( Surv(time, status) ~ sex, data = colon )

fit2 <- survfit( Surv(time, status) ~ sex + rx, data = colon )
```

## Facet by one grouping variables
    
Facet by the treatment assignment `rx`


```{r}
# Faceting fit 1
ggsurvplot(fit1, colon, facet.by = "rx", 
              palette = "jco", pval = TRUE)
```
       
![rplot11](https://cloud.githubusercontent.com/assets/3313355/25542208/db700994-2c51-11e7-92b1-c99e3a9ad79d.png)

```{r}
# Faceting fit 2
ggsurvplot(fit2, colon, facet.by = "adhere", 
           palette = "jco", pval = TRUE)
```

![rplot16](https://cloud.githubusercontent.com/assets/3313355/25542248/0a4ca88a-2c52-11e7-9a0b-88234b42ffdc.png)


## Facet by two grouping variables
       

```{r}
ggsurvplot(fit1, colon, facet.by = c("rx", "adhere"),
           palette = "jco", pval = TRUE)
```

![rplot17](https://cloud.githubusercontent.com/assets/3313355/25542300/383640a8-2c52-11e7-8a69-5e7b640bab47.png)

**Comment by jiajiaybyb** [comment]
I realized ggsurvplot_facet does not plot the survival lines all the way to 100%, is there a solution for this? Ideally I would like to have facet panels, with corresponding p values and survival tables in the output. Any recommend method for this? Thanks a lot!

**Comment by Yatros** [comment]
Hello,

Is it possible to add capability to ggsurvplot_facet() so that it accepts as input not only survfit objects, but also a list of survfit objects?

Something similar to what surv_fit() already does with survival formulas.

Thank you very much,

Best Regards,
