### ISSUE TITLE
Legend missing when legend position is other than top

### ISSUE THREAD

**Issue by Swechhya** [kassambara/survminer#208]
Hi,

Thank you so much for this amazing package. I am facing an issue with legends position when the risk table is outside the plot. When the risk table is inside the plot the legends seem to work perfectly. 

I have the following code:
 
```
library(survminer)
  library(survival)
  fit<- survfit(Surv(time, status) ~ sex, data = lung )
  ggsurvplot(fit, data = lung, risk.table = TRUE,
                  risk.table.pos = "out",  legend = "right")

```
The plot the I get is as follows:
![image](https://cloud.githubusercontent.com/assets/6251412/25607248/61066bd2-2f33-11e7-9918-5ec0381b99e9.png)

The same happens if I choose legend as` legend =  "bottom"` and  `legend = "left"`

But for cases when the  `risk.table.pos = "in"`  instead of   `risk.table.pos = "out"` the legends seem to be working perfectly fine.

**Comment by kassambara** [comment]
Fixed now!

Thank you for pointing this out.
