### ISSUE TITLE
issue with pairwise_survdiff

### ISSUE THREAD

**Issue by amartin44** [kassambara/survminer#209]
### Expected behavior 
I am hoping to run pairwise_survdiff to compare three different levels of the factor of interest in my survival curve. To do so, I set up the command as it is written in the manual:
post.diff <- pairwise_survdiff(Surv(time,delta)~pop,data = data,rho = 0, p.adjust.method = "hochberg")
...where 'delta' is the event status and 'pop' is the factor with which I want to determine if significant differences in survivorship exist across levels. 
### Actual behavior
The command runs without a warning message, but the results are empty/meaningless:

> post.diff

	Pairwise comparisons using Log-Rank test 

data:  data and pop 

<0 x 0 matrix>

P value adjustment method: hochberg

### `session_info()`

````{R}
# please paste here the result of
devtools::session_info()
````

**Comment by kassambara** [comment]
This issue has been already fixed in the current developmental version.

Please install the latest version as follow:

```r
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/survminer", build_vignettes = FALSE)
```
It should work after installation.

Please let me know...

**Comment by amartin44** [comment]
Thanks,


I was able to install the correct version and obtain results. However, when I run the analysis to determine which of the three levels of my factor are different in the survival analysis, the p-value is exactly the same for comparing one of my levels (Michigan) to the other two (Champlain & Connecticut), and this seems like it isn't just a coincidence. This is true even if I change the p.adjust.method. Have you seen this issue before?

                     Champlain Connecticut
Connecticut    0.714             -
Michigan         0.042          0.042

P value adjustment method: hochberg


Thank you very much in advance for your time,

--
Alexander Martinez
PhD Student, Ecology and Evolutionary Biology
Purdue University, Biological Sciences
Office: Lily G-365
Office Phone: (765)-496-6191
mart1139@purdue.edu


________________________________

**Comment by kassambara** [comment]
I think that this is just a coincidence... 

```r
library(survival)
pairwise_survdiff(Surv(time, status) ~ rx, data = colon, p.adjust.method = "BH")

pairwise_survdiff(Surv(time, status) ~ rx, data = colon, p.adjust.method = "bonferroni")
```
