### ISSUE TITLE
Columns/Rows mislabeled in pairwise_survdiff display

### ISSUE THREAD

**Issue by mriffle** [kassambara/survminer#212]
Greetings,

Here is a survival plot I made using survminer:

![rplot01](https://cloud.githubusercontent.com/assets/4825678/25976551/aedb1388-366a-11e7-9a96-a3da0c636717.png)

However, when calculating and showing the pair-wise log-rank p-values:

> fitc <- pairwise_survdiff(Surv(force, event) ~ sample, data = chip_data, p.adjust.method="none")
> fitc

	Pairwise comparisons using Log-Rank test 

data:  chip_data and sample 

           Kinetochore Spc110-407 Spc72-AID
Spc110-407 0.946       -          -        
Spc72-AID  0.041       0.094      -        
Wild Type  <2e-16      <2e-16     <2e-16   

P value adjustment method: none 

It looks as though the labels in the table are incorrect. Judging by the image of the graph, the final row labeled "Wild Type" in this output, should actually be the "Kinetochore", which would have very significant p-values when compared to the other conditions. Judging by the reported p-values, it looks as though other rows and/or columns may be mislabeled as well.

# please paste here the result of
> devtools::session_info()
Session info -------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, mingw32             
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2017-05-11                  

Packages -----------------------------------------------------------------------------------------------------------------
 package    * version   date       source                               
 assertthat   0.2.0     2017-04-11 CRAN (R 3.4.0)                       
 broom        0.4.2     2017-02-13 CRAN (R 3.4.0)                       
 cmprsk       2.2-7     2014-06-17 CRAN (R 3.4.0)                       
 colorspace   1.3-2     2016-12-14 CRAN (R 3.4.0)                       
 data.table   1.10.4    2017-02-01 CRAN (R 3.4.0)                       
 DBI          0.6-1     2017-04-01 CRAN (R 3.4.0)                       
 devtools     1.12.0    2016-12-05 CRAN (R 3.4.0)                       
 digest       0.6.12    2017-01-27 CRAN (R 3.4.0)                       
 dplyr        0.5.0     2016-06-24 CRAN (R 3.4.0)                       
 foreign      0.8-67    2016-09-13 CRAN (R 3.4.0)                       
 ggplot2    * 2.2.1     2016-12-30 CRAN (R 3.4.0)                       
 ggpubr     * 0.1.2     2017-03-14 CRAN (R 3.4.0)                       
 gridExtra    2.2.1     2016-02-29 CRAN (R 3.4.0)                       
 gtable       0.2.0     2016-02-26 CRAN (R 3.4.0)                       
 km.ci        0.5-2     2009-08-30 CRAN (R 3.4.0)                       
 KMsurv       0.1-5     2012-12-03 CRAN (R 3.4.0)                       
 knitr        1.15.1    2016-11-22 CRAN (R 3.4.0)                       
 lattice      0.20-35   2017-03-25 CRAN (R 3.4.0)                       
 lazyeval     0.2.0     2016-06-12 CRAN (R 3.4.0)                       
 magrittr     1.5       2014-11-22 CRAN (R 3.4.0)                       
 Matrix       1.2-9     2017-03-14 CRAN (R 3.4.0)                       
 memoise      1.1.0     2017-04-21 CRAN (R 3.4.0)                       
 mnormt       1.5-5     2016-10-15 CRAN (R 3.4.0)                       
 munsell      0.4.3     2016-02-13 CRAN (R 3.4.0)                       
 nlme         3.1-131   2017-02-06 CRAN (R 3.4.0)                       
 plyr         1.8.4     2016-06-08 CRAN (R 3.4.0)                       
 psych        1.7.5     2017-05-03 CRAN (R 3.4.0)                       
 purrr        0.2.2     2016-06-18 CRAN (R 3.4.0)                       
 R6           2.2.0     2016-10-05 CRAN (R 3.4.0)                       
 Rcpp         0.12.10   2017-03-19 CRAN (R 3.4.0)                       
 reshape2     1.4.2     2016-10-22 CRAN (R 3.4.0)                       
 rstudioapi   0.6       2016-06-27 CRAN (R 3.4.0)                       
 scales       0.4.1     2016-11-09 CRAN (R 3.4.0)                       
 stringi      1.1.5     2017-04-07 CRAN (R 3.4.0)                       
 stringr      1.2.0     2017-02-18 CRAN (R 3.4.0)                       
 survival   * 2.41-3    2017-04-04 CRAN (R 3.4.0)                       
 survminer  * 0.3.1.999 2017-05-05 Github (kassambara/survminer@7b7d9fe)
 survMisc     0.5.4     2016-11-23 CRAN (R 3.4.0)                       
 tibble       1.3.0     2017-04-01 CRAN (R 3.4.0)                       
 tidyr        0.6.2     2017-05-04 CRAN (R 3.4.0)                       
 withr        1.0.2     2016-06-20 CRAN (R 3.4.0)                       
 xtable       1.8-2     2016-02-05 CRAN (R 3.4.0)                       
 zoo          1.8-0     2017-04-12 CRAN (R 3.4.0) 
````

**Comment by kassambara** [comment]
Fixed now, thanks!

**Comment by mriffle** [comment]
Great, thanks!
