### ISSUE TITLE
Round the weighted survival estimates in the risk table

### ISSUE THREAD

**Issue by josephuses** [kassambara/survminer#214]
I was trying to reproduce the plot in p. 311 of Berglund, Heeringa, and West's Applied Survey Data Analysis. The data is available online at their website, which I linked here. How can I round off the survival estimates in the risk table? Can we have something like risk.table.decimal.place which defaults to a whole number?

```
library(tidyverse)
library(survival)
library(survminer)
ncsr <- read_sas("~/ncsr_analysis_ex_c1_c10_2011.sas7bdat")
colnames(ncsr) <- tolower(names(ncsr))
fit <- survfit(Surv(ageonsetmde,mde)~racecat, data = ncsr, weights = ncsrwtsh)
ggsurvplot(fit, data = ncsr, 
           ggtheme = theme_bw(), 
           linetype = "strata", 
           risk.table = TRUE, 
           risk.table.col = "strata", 
           legend.labs = c("Other", "Hispanic", "Black", "White"), 
           risk.table.fontsize = 2.75, 
           risk.table.height = 0.275, 
           break.time.by = 20, risk.table.y.text.col = T, 
           risk.table.y.text = FALSE) 
```
![survival](https://cloud.githubusercontent.com/assets/3108869/26043768/7c70fa10-3972-11e7-909b-f68ac92cfa48.png)

**Comment by kassambara** [comment]
Would you please give the direct link to the "ncsr_analysis_ex_c1_c10_2011.sas7bdat" file, so that we can reproduce your example...

Thanks!

**Comment by kassambara** [comment]
Ok, I  can found the data in a different post: https://github.com/kassambara/survminer/issues/215

**Comment by kassambara** [comment]
Thank you or pointing this out.

Now, the default behaviour of `ggsurvplot()` is to round the number at risk using the option `digits = 0`

**Comment by josephuses** [comment]
Thank you! This solves my issue for this particular case. However, note that setting `decimal.place` to any other whole number does not give the desired number of decimal places.

**Comment by kassambara** [comment]
This option is not externaly available. The default is to systematically round the number at risk.
