### ISSUE TITLE
Make ggsurvplot work with the survey package

### ISSUE THREAD

**Issue by josephuses** [kassambara/survminer#215]
I am thinking along the line of printing the design-adjusted weighted survival estimates in the risk table. I would like to do something like the following:

```
library(tidyverse)
library(survey)
library(survminer)
ncsr <- read_sas("~/ncsr_analysis_ex_c1_c10_2011.sas7bdat")
colnames(ncsr) <- tolower(names(ncsr))
ncsrsvyp1 <- svydesign(strata=~sestrat, id=~seclustr, weights = ~ncsrwtsh, data=ncsr, nest = TRUE)
ncsrsfit <- svykm(Surv(ageonsetmde,mde)~strata(racecat), data = ncsr, design=ncsrsvyp1)
ggsurvplot(ncsrfit, design = ncsrsvyp1, 
           ggtheme = theme_bw(), 
           linetype = "strata", 
           risk.table = TRUE, 
           risk.table.col = "strata", 
           legend.labs = c("Other", "Hispanic", "Black", "White"), 
           risk.table.fontsize = 2.75, 
           risk.table.height = 0.275, 
           break.time.by = 20, risk.table.y.text.col = T, 
           risk.table.y.text = FALSE)
```

I used the data from Berglund, Heeringa, and West's Applied Survey Data Analysis [here](http://www.isr.umich.edu/src/smp/asda/ASDA%20Analysis%20Examples%20Data%20Sets%20Stata%20and%20SAS%20Format.zip).

**Comment by kassambara** [comment]
I'm not very familiar with the `survey` package. However, we  recently implemented the function `ggsurvplot_df()`, which is an extension to ggsurvplot() to plot survival curves from any data frame containing the summary of survival curves as returned by the `survminer::surv_summary()` function.

This function, might be useful for a user who wants to use ggsurvplot for visualizing survival curves computed by another method/package different to the standard `survfit.formula` function. In this case, the user has just to provide the data frame containing the summary of the survival analysis.

**Comment by josephuses** [comment]
The `survey` package comes as the recommended package for our course in survey sampling. However, it seems that its `svykm` function produces a svykmlist data that contains lists of only `surv` and `time`. I compared the results with those from the `survival` package and can't see any discrepancies. I have decided to just stick with the `survival` package since it seems able to provide what I need at the moment.

**Comment by kassambara** [comment]
Ok great! 

I have also quickly inspect  the `svykm()` function. It seems to be like the standard `survfit()` but with only `surv` and `time` as output.  Additionally,  with the `svykm()` function, it's not easy to access to the detailed summary of the survival curves, including: the confidence limits, the number at risk, the number of censoring, etc

So, I think that we can close this issue
