### ISSUE TITLE
ggsurvplot break.time.by and start.time

### ISSUE THREAD

**Issue by m001360** [kassambara/survminer#218]
### Expected behavior 
Wanting to make a Kaplan-Meier curve for data on an alternate timescale (specifically on age).  We aren't interested in looking at the effect until the age of 40, so we use the start.time=40 option.  The plot should have # at risk at age 40, 50, 60, 70, 80, 90, 100 (eg 7 timepoints).

### Actual behavior
Error results and no object is created.  Instead I get an error about 11 rows, which would make sense if the function was only expecting start time at 0 (eg 0 to 100 by 10's is 11 points to mark on the plot).  Note - for some reason this error does NOT exist if I use a 2-level X variable, an age 40 start time, and the break.time.by argument; then it runs fine.

### Steps to reproduce the problem
Error without covariates:
> sfit1 <- survfit(Surv(age.at.sx.yrs, age.at.sx.yrs+time.to.lastfu.yrs, death)~1, data=xxx, start.time=40)
> plotkm <- ggsurvplot(sfit1, legend.title="", surv.scale="percent", 
                      censor=TRUE, pval=FALSE, xlim=c(40,100), break.time.by=10,
                      ylab="Deaths, %", xlab="Age", 
                      risk.table=T, risk.table.title="Number at Risk",
                      risk.table.height=0.18, linetype=1, color="black",
                      risk.table.col="black", 
                      risk.table.y.text.col=F, pval.coord = c(1, 0.4), pval.size = 7)
Error in data.frame(strata = .clean_strata(as.factor(.strata)), time = summary(fit,  : 
  arguments imply differing number of rows: 11, 7

No error with a 2-level covariate:
> sfit1 <- survfit(Surv(age.at.sx.yrs, age.at.sx.yrs+time.to.lastfu.yrs, death)~sex, data=xxx, start.time=40)
> plotkm <- ggsurvplot(sfit1, legend.title="", surv.scale="percent", 
                      censor=TRUE, pval=FALSE, xlim=c(40,100), break.time.by=10,
                      ylab="Deaths, %", xlab="Age", 
                      risk.table=T, risk.table.title="Number at Risk",
                      risk.table.height=0.18, linetype=1:2, color="black",
                      risk.table.col="black", legend.labs=c("Female", "Male"),
                      risk.table.y.text.col=F, pval.coord = c(1, 0.4), pval.size = 7)

### `session_info()`

````{R}
# please paste here the result of
devtools::session_info()
````

> devtools::session_info()
Session info -----------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2017-05-16                  

Packages ---------------------------------------------------------------------------------------------------------------------------------------------
 package    * version date       source        
 arsenal    * 0.2.3   2017-03-10 local         
 assertthat   0.1     2013-12-06 CRAN (R 3.2.3)
 broom        0.4.1   2016-06-24 CRAN (R 3.2.3)
 codetools    0.2-15  2016-10-05 CRAN (R 3.2.3)
 colorspace   1.2-7   2016-10-11 CRAN (R 3.2.3)
 DBI          0.4-1   2016-05-08 CRAN (R 3.2.3)
 devtools     1.12.0  2016-06-24 CRAN (R 3.2.3)
 digest       0.6.10  2016-08-02 CRAN (R 3.2.3)
 dplyr        0.5.0   2016-06-24 CRAN (R 3.2.3)
 foreach    * 1.4.3   2015-10-13 CRAN (R 3.2.3)
 foreign      0.8-67  2016-09-13 CRAN (R 3.2.3)
 gam        * 1.14    2016-09-10 CRAN (R 3.2.3)
 ggplot2    * 2.1.0   2016-03-01 CRAN (R 3.2.3)
 gridExtra    2.2.1   2016-02-29 CRAN (R 3.2.3)
 gtable       0.2.0   2016-02-26 CRAN (R 3.2.3)
 highr        0.6     2016-05-09 CRAN (R 3.2.3)
 iterators    1.0.8   2015-10-13 CRAN (R 3.2.3)
 knitr      * 1.14    2016-08-13 CRAN (R 3.2.3)
 labeling     0.3     2014-08-23 CRAN (R 3.2.3)
 lattice      0.20-34 2016-09-06 CRAN (R 3.2.3)
 magrittr     1.5     2014-11-22 CRAN (R 3.2.3)
 Matrix       1.2-7.1 2016-09-01 CRAN (R 3.2.3)
 memoise      1.0.0   2016-01-29 CRAN (R 3.2.3)
 mnormt       1.5-5   2016-10-15 CRAN (R 3.2.3)
 munsell      0.4.3   2016-02-13 CRAN (R 3.2.3)
 nlme         3.1-128 2016-05-10 CRAN (R 3.2.3)
 plyr         1.8.4   2016-06-08 CRAN (R 3.2.3)
 psych        1.6.9   2016-09-17 CRAN (R 3.2.3)
 R6           2.1.3   2016-08-19 CRAN (R 3.2.3)
 Rcpp         0.12.7  2016-09-05 CRAN (R 3.2.3)
 reshape2     1.4.1   2014-12-06 CRAN (R 3.2.3)
 rlocal     * 4.1.0   2017-04-21 local         
 scales       0.4.0   2016-02-26 CRAN (R 3.2.3)
 stringi      1.1.2   2016-10-01 CRAN (R 3.2.3)
 stringr      1.1.0   2016-08-19 CRAN (R 3.2.3)
 survival   * 2.40-2  2016-11-30 local         
 survminer  * 0.2.4   2016-12-11 CRAN (R 3.2.3)
 tibble       1.2     2016-08-26 CRAN (R 3.2.3)
 tidyr        0.6.0   2016-08-12 CRAN (R 3.2.3)
 withr        1.0.2   2016-06-20 CRAN (R 3.2.3)

**Comment by kassambara** [comment]
please could you provide a reproducible example with a demo data set?
Thanks

**Comment by m001360** [comment]
Constructed dataset:  Attached.  [forbugreport_v2.xlsx](https://github.com/kassambara/survminer/files/1005851/forbugreport_v2.xlsx)

Three pieces of code for constructed dataset (you'll need to fix the dataset call):

require(knitr)
xxx <- sas.get("insert_your_own_pathname_here", "forbugreport_v2")

# N at risk plot
require(survminer)

# Version 1 - Overall plot, breaking X axis time by 10 year intervals, doesnt work.
# Create a survfit object
sfit1 <- survfit(Surv(age.at.sx.yrs.randnorm.25.15, age.at.sx.yrs.randnorm.25.15+time.to.lastfu.yrs.rand, death.round.randuni)~1, data=xxx, start.time=40)
plotkm1 <- ggsurvplot(sfit1, legend.title="", surv.scale="percent", 
                     censor=TRUE, pval=FALSE, xlim=c(40,100), break.time.by=10,
                     ylab="Deaths, %", xlab="Age", 
                     risk.table=T, risk.table.title="Number at Risk",
                     risk.table.height=0.18, linetype=1, color="black",
                     risk.table.col="black", 
                     risk.table.y.text.col=F, pval.coord = c(1, 0.4), pval.size = 7)

# Some polish for the plot appearance
# Removed from bug report submission version for failing to get theme_survminer to work...
# Error: could not find function "theme_survminer"

# Some polish for the N at risk appearance
plotkm1$table <- plotkm1$table + theme(axis.line=element_blank(), axis.title = element_blank(), 
                                     axis.text.x = element_blank(), axis.ticks = element_blank() )
# Display plot
print(plotkm1)


# Version 2 - Overall plot, not trying to break X axis time by 10 year intervals, works.
sfit2 <- survfit(Surv(age.at.sx.yrs.randnorm.25.15, age.at.sx.yrs.randnorm.25.15+time.to.lastfu.yrs.rand, death.round.randuni)~1, data=xxx, start.time=40)
plotkm2 <- ggsurvplot(sfit2, legend.title="", surv.scale="percent", 
                     censor=TRUE, pval=FALSE, xlim=c(40,100), 
                     ylab="Deaths, %", xlab="Age", 
                     risk.table=T, risk.table.title="Number at Risk",
                     risk.table.height=0.18, linetype=1, color="black",
                     risk.table.col="black", 
                     risk.table.y.text.col=F, pval.coord = c(1, 0.4), pval.size = 7)  #break.time.by=10,

# Some polish for the plot appearance
# Removed from bug report submission version for failing to get theme_survminer to work...
# Error: could not find function "theme_survminer"

# Some polish for the N at risk appearance
plotkm2$table <- plotkm2$table + theme(axis.line=element_blank(), axis.title = element_blank(), 
                                     axis.text.x = element_blank(), axis.ticks = element_blank() )
# Display plot
print(plotkm2)


# Version 3 - Plot by sex, breaking X axis time by 10 year intervals, works.
# Create a survfit object
sfit3 <- survfit(Surv(age.at.sx.yrs.randnorm.25.15, age.at.sx.yrs.randnorm.25.15+time.to.lastfu.yrs.rand, death.round.randuni)~sex.round.randuni, data=xxx, start.time=40)
plotkm3 <- ggsurvplot(sfit3, legend.title="", surv.scale="percent", 
                     censor=TRUE, pval=FALSE, xlim=c(40,100), break.time.by=10,
                     ylab="Deaths, %", xlab="Age", 
                     risk.table=T, risk.table.title="Number at Risk",
                     risk.table.height=0.18, linetype=1:2, color="black",
                     risk.table.col="black", legend.labs=c("Female", "Male"),
                     risk.table.y.text.col=F, pval.coord = c(1, 0.4), pval.size = 7)

# Some polish for the plot appearance
# Removed from bug report submission version for failing to get theme_survminer to work...
# Error: could not find function "theme_survminer"

# Some polish for the N at risk appearance
plotkm3$table <- plotkm3$table + theme(axis.line=element_blank(), axis.title = element_blank(), 
                                     axis.text.x = element_blank(), axis.ticks = element_blank()
)
# Display plot
print(plotkm3)

**Comment by kassambara** [comment]
Fixed now, thanks!

kindly confirm that it works for you.

**Comment by m001360** [comment]
It did indeed, thank you!

**Comment by kassambara** [comment]
So we can close this issue. Thank you!

**Comment by Juhu39** [comment]
Please see issue #361. The number at risk table is zero for t=0 (which is incorrect), when start.time is specified. Thank you!
