### ISSUE TITLE
Unwanted line (? X-axis tick) in risk table when using theme_cleantable() with strata labels

### ISSUE THREAD

**Issue by BenCorden** [kassambara/survminer#225]
I'm customising a risk table with theme_cleantable() but I' want to have strata labels. When I do this, there is an unwanted horizontal line adjacent to the labels. How can I remove this? See code below to reproduce:

### This re-produces the issue:
fit <- survfit( Surv(time, status) ~ sex, data = lung )
ggsurvplot(fit, data = lung,
           risk.table = TRUE,
           tables.theme = theme_cleantable(), # clean theme for tables
           )

### The horizontal line does not appear if I remove strata labels (hide the tables y axis text)
ggsurvplot(fit, data = lung,
           risk.table = TRUE,
           tables.theme = theme_cleantable(), # clean theme for tables
           tables.y.text = FALSE # hide tables y axis text 
            )

### `session_info()`

````{R}
# please paste here the result of
devtools::session_info()
````
Session info ----------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  English_United Kingdom.1252 
 tz       Europe/London               
 date     2017-06-06

**Comment by kassambara** [comment]
fixed now, thanks
