### ISSUE TITLE
Error trying to access survdiff formula even if pval F/numeric/character

### ISSUE THREAD

**Issue by mwiesweg** [kassambara/survminer#228]
I kept getting
"Error in eval(expr, envir, enclos) : object 'surv' not found"
when calling ggsurvplot with a fit created by code
"survfit(surv[logicalVector] ~ data[logicalVector, factorId])"
in a function. Apparently, it is trying to do something with language snippets of variables ("surv") which are not available in the function's environment.

Anyway, if ggsurvplot is expected to dig into survfit, it may throw errors in such cases.
But, it does so even if pval is given (F, numeric or character).
I traced that down to surv_pvalue.R, 185:
 fit.ext <- .extract.survfit(fit, data)
and inside this to utilities.R: 386
 data.formula <- stats::get_all_vars(.formula, data = data)

The problem is that this call is made even in a context where the pvalue should not be computed!

Version: current git

**Comment by kassambara** [comment]
Hi,
From reading this code `survfit(surv[logicalVector] ~ data[logicalVector, factorId])`,  It seems that you're not using `survfit()` properly.

I would also recommend to avoid data manipulation inside `survfit()`.

If you want survminer to work properly, consider using `survfit()` as follow:

```r
# Fit survival curves
require("survival")
fit<- survfit(Surv(time, status) ~ sex, data = lung)

# Basic survival curves
library(survminer)
ggsurvplot(fit, data = lung)
````

If you want to fit survival curves on a subset of your data, see the example below:


```r
# Fit survival curves
require("survival")
fit<- survfit(Surv(time, status) ~ sex, data = lung[logicalVector, ])

# Basic survival curves
library(survminer)
ggsurvplot(fit, data = lung[logicalVector, ])
````

If it still fails, then provide a reproducible example with the lung data.


Thanks

**Comment by kassambara** [comment]
hi @mwiesweg,

Please let us know if it works or not...

With regards,

**Comment by mwiesweg** [comment]
I think I managed to find (with experience I gathered from fighting with other ggplot2-related problems) a working solution to pass the formula, which is programmatically generated, to survfit such that R and survminer can extract the proper variables as if typed verbatim:

  # construct formula, given column labels for time and event indicator
  survFormula <- as.formula(paste0("Surv(",survivalFields[[1]],",",survivalFields[[2]],") ~ ",factorId))
  
  # do some non-standard evaluation acrobatics to make survfit think is was called with the formula typed
  fitFunc <- function() {
    eval(substitute(
      expr = {
        survfit(survFormula, data = data[logicalVector])
      },
      env = parent.frame()
    ))
  }
  fit <- fitFunc()
