### ISSUE TITLE
remove horizontal lines html tags from the README

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#230]
### Expected behavior 

having `<hr/>` tags would add horizontal tag to the output md file - this is properly visible in the RStudio viewer
<img width="747" alt="proper_readme" src="https://user-images.githubusercontent.com/6773454/27260337-c791386c-5429-11e7-9a2a-6a85b85423f5.PNG">

### Actual behavior

The GitHub viewer does not recognize the `newline` after the `<hr/>` tag so the listing doesn't show properly
<img width="405" alt="readme_remove_hr" src="https://user-images.githubusercontent.com/6773454/27260342-e3ce2e9a-5429-11e7-92d2-9c24812de836.PNG">

**Comment by kassambara** [comment]
fixed now, thanks
