### ISSUE TITLE
y label for risk table

### ISSUE THREAD

**Issue by dnzmarcio** [kassambara/survminer#236]
Hi, 

It would convenient if the y label for the risk table could be edit instead of just being extracted from the legend title. If the legend title has a length too big then y label is not well displayed in the risk table. If we can edit the y label for the risk table then we could just make it blank.

Thank you!

**Comment by kassambara** [comment]
Hi,

As `ggsurvplot()`  is based on ggplot2, it's possible to use ggplot2 verbs for editing the output of `ggsurvplot()`.

For example, it's possible to do this:

```r
library(survival)
library(survminer)
fit<- survfit(Surv(time, status) ~ sex, data = lung)
# Hide y.text
ggsurvplot(fit, data = lung, risk.table = TRUE,
           tables.col = "strata", 
           tables.y.text = FALSE  
           )
```

![rplot](https://user-images.githubusercontent.com/3313355/27511200-59ceef0e-591f-11e7-9245-b5f69dfcc2b5.png)


But  also this:

```r
# Blank y text
ggsurv <- ggsurvplot(fit, data = lung, risk.table = TRUE,
                     tables.col = "strata", tables.theme = theme_cleantable())
ggsurv$table <- ggsurv$table + 
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
    )

ggsurv
```

![rplot06](https://user-images.githubusercontent.com/3313355/27511208-8bc73f2a-591f-11e7-8384-a4b18ca1407a.png)

**Comment by dnzmarcio** [comment]
Thank you for your prompt reply.

Your examples are slighlty different from my suggestion. Let me ilustrate that, 
```
library(survival)
library(survminer)
fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurv <- ggsurvplot(fit, risk.table = TRUE, tables.y.text = FALSE)
risk.table.ylab <- "Sex"
ggsurv$table <- ggsurv$table + labs(y = risk.table.ylab)
ggsurv
```
The argument risk.table.ylab would be an additional argument of the function ggsurvplot. 
Then, the function ggsurvplot would have another option (it has already a lot ) of customization. 

It is not an essential feature, though. As you said, I can edit using ggplot verbs.

**Comment by fushen11** [comment]
Hi Could you please illustrate how to customize the y labs of risk table ? I am struggling with this issue and I could either remove the y labs for risk table or extract from the legend.
