### ISSUE TITLE
Hide axis tick labels on one axis only

### ISSUE THREAD

**Issue by mwiesweg** [kassambara/survminer#238]
Is there a way to hide the tick labels on one axis only?
ggpar() has tickslab, but that is global for both axis.
The standard procedure in ggplot2 is
... + theme(axis.text.y = element_blank())
but that seems to be ignored/overridden somewhere inside ggsurvplot, at least, has no effect for me.

Running survminer git from last week, ggplot2 2.2.1. from git.

Thanks

**Comment by kassambara** [comment]
Hi,

The R code below works on my computer:

```r
require("survival")
fit<- survfit(Surv(time, status) ~ sex, data = lung)

library(survminer)
ggsurv <-ggsurvplot(fit, risk.table = TRUE)
ggsurv$plot <- ggsurv$plot + theme(axis.text.y = element_blank())
ggsurv
```

Focus on axis.text.y of the main survival plot:

![rplot](https://user-images.githubusercontent.com/3313355/27540622-19d7bd8c-5a81-11e7-8abc-2dbb2dbc0850.png)


This works also:

```r
# Apply changes on both main plot and the risk table
ggsurv %++% theme(axis.text.y = element_blank())
```

![rplot07](https://user-images.githubusercontent.com/3313355/27540697-67ec9542-5a81-11e7-86bc-d4db87df9ec8.png)

**Comment by mwiesweg** [comment]
Thanks, yes it works. 
My problem was that I tried to add it to the theme passed as the ggtheme parameter before calling ggsurvplot. Adding afterwards works fine.
