### ISSUE TITLE
Font  family not getting applied to risk table and p-value in ggsurvplot

### ISSUE THREAD

**Issue by Swechhya** [kassambara/survminer#245]
I tried changing the font family for ggsurvplot using the following code:

```
library(survival)
library(survminer)
fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurvplot(fit, risk.table = TRUE,  risk.table.pos = "in", pval = TRUE, ggtheme = theme_classic2(base_family = "Courier New"))
```

I got the following plot :
![image](https://user-images.githubusercontent.com/6251412/29015487-d2d2d550-7b6b-11e7-8b74-b79104eec9fe.png)

As you can see in the plot, font family gets applied to all the plot parameters except the risk table and p-value. Is there a way to resolve the issue?

Thank you!

**Comment by kassambara** [comment]
Fixed now, thanks!

 The elements in the risk table are text elements not theme elements.  

To change the font family, specify the arguments:

-  ggtheme (for theme elements),
- and font.family  (for text element in the tables),

as follow:

```r
library(survival)
library(survminer)

# Fit survival curves
fit<- survfit(Surv(time, status) ~ sex, data = lung)

# Visualize
ggsurvplot(fit, 
           risk.table = TRUE,          
           risk.table.pos = "in",      
           pval = TRUE,                
           ggtheme = theme_classic2(base_family = "Courier New"),
           font.family = "Courier New" 
           )
```

**Comment by Swechhya** [comment]
I tried using the code you provided. There still seems to be problem with the font family getting applied to the elements in the risk table and the p-value. The font family for these elements are still the default font instead of _"Courier New"_

**Comment by kassambara** [comment]
It works for me. Please, make sure that you have installed the latest developmental version.

**Comment by Swechhya** [comment]
With the latest development version this is the plot that I am getting:
![image](https://user-images.githubusercontent.com/6251412/29025349-e720303e-7b93-11e7-82e2-9c4aa95ca3b8.png)
As you can see, the risk table now has the _"Courier New"_ as the font family but the p-value  text still has the default font.

**Comment by kassambara** [comment]
Oh sorry, I thought that you were taking about the risk table.

The issue is now fixed for the p-value. Please re-install. It should work. Thanks

**Comment by Swechhya** [comment]
Thank you for the fix. It works perfectly now.
