### ISSUE TITLE
How to adjust the risk table title position?

### ISSUE THREAD

**Issue by gas128** [kassambara/survminer#246]
I would like to create a Kaplan-Meier plot with a number at risk table using survminer. However I could not adjust the position of the title of risk table.

That is my code: 

library(survminer)  

library(survival)  

fit<- survfit(Surv(time, status) ~ sex, data = lung)  

ggsurvplot(fit, data = lung, risk.table = TRUE, pval = TRUE, conf.int = TRUE, tables.theme = theme_cleantable())

I want to change figure letf to figure right:

**Comment by kassambara** [comment]
This should work:

```r
library(survival)
library(survminer)

fit<- survfit(Surv(time, status) ~ sex, data = lung)

ggsurv <- ggsurvplot(fit, data = lung, risk.table = TRUE,
                     pval = TRUE, conf.int = TRUE, 
                     tables.theme = theme_cleantable())
# Adjdjust plot title
ggsurv$table <- ggsurv$table + theme(plot.title = element_text(hjust = 1))

print(ggsurv)
```

**Comment by gas128** [comment]
![image](https://user-images.githubusercontent.com/31363243/29738984-154fe3f2-8a65-11e7-9b46-e80477aebf87.png)
Sorry, what I mean is change figure left to figure right. 
Please help me to adjust the risk table title align to the y-lab.

**Comment by kassambara** [comment]
Hi,

Just play with the argument hjust. Please Try this:

```r
ggsurv$table <- ggsurv$table + theme(plot.title = element_text(hjust = -0.2))

print(ggsurv)
```

Kindly confirm that it works.

**Comment by gas128** [comment]
It dose some work, like this
![17 08 26 1355_2](https://user-images.githubusercontent.com/31363243/29739021-68d16db0-8a66-11e7-97a0-aa4e8a45bded.png)

However, if I try this,
ggsurv$table <- ggsurv$table + theme(plot.title = element_text(hjust = -0.4))
![17 08 26 1358_3](https://user-images.githubusercontent.com/31363243/29739032-a2e36814-8a66-11e7-8b1b-18b247c777fc.png)

How could I draw it like this?
![17 08 26 1359_4](https://user-images.githubusercontent.com/31363243/29739040-c9d5584c-8a66-11e7-8697-f5666278219d.png)

Thank you!

**Comment by kassambara** [comment]
Ok, I can see know.

You need to play with plot.margin and hjust:

1. Increase the margin of the main survival curves
2. Increase the margin of the survival table  and adjust the title

```r
# 1. Survival plot, adjust margin
#:::::::::::::::::::::::::::::::::::::::::::::
# plot.margin = c(top, right, bottom, left)
ggsurv$plot <- ggsurv$plot + 
  theme(
    plot.margin = unit(c(5.5, 5.5, 5.5, 50), "points"))

# 2. Risk table
#:::::::::::::::::::::::::::::::::::::::::::::
# Adjdjust plot title
# plot.margin = c(top, right, bottom, left)
ggsurv$table <- ggsurv$table + 
  theme(
    plot.title = element_text(hjust = -0.7),
    plot.margin = unit(c(5.5, 5.5, 5.5, 50), "points"))

print(ggsurv)
```

![rplot](https://user-images.githubusercontent.com/3313355/29739371-a55b7214-8a3c-11e7-9df7-80fddf3293ec.png)

**Comment by gas128** [comment]
Thank you very much!
