### ISSUE TITLE
change size of legend

### ISSUE THREAD

**Issue by Phil-T** [kassambara/survminer#247]
I'm trying to change the size of the font and characters inside the legend, and I can't. Is this possible?
````

**Comment by kassambara** [comment]
The R script below should work.

Fit and plot survival curves:

```{r}
library(survival)
library(survminer)

fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurv <- ggsurvplot(fit, data = lung, 
                     risk.table = TRUE, tables.theme = clean_theme())
```


Two ways to change legend text appearance.

**1)** ggplot2 standard way:
   
```{r}
ggsurv$plot <- ggsurv$plot + theme(legend.text = element_text(size = 14, color = "black", face = "bold"))
ggsurv
```
  
**2)** [ggpubr](https://github.com/kassambara/ggpubr) way. Use ggpar() to change easily the graphical parameters of any ggplots. Want to learn more? Read this: http://www.sthda.com/english/articles/24-ggpubr-publication-ready-plots/82-ggplot2-easy-way-to-change-graphical-parameters/

```{r}
ggpubr::ggpar(ggsurv,
              font.legend = list(size = 14, color = "black", face = "bold"))
```

![rplot](https://user-images.githubusercontent.com/3313355/29998349-0588cdde-9029-11e7-9795-0f3095b1878f.png)

**Comment by Phil-T** [comment]
This worked perfectly. Thank you.
