### ISSUE TITLE
Survival curves for black and white figures

### ISSUE THREAD

**Issue by shamav523** [kassambara/survminer#249]
Hello,

The survminer package is beautiful but I was wondering if there was a way to make it more black and white friendly. I like the use of the tick marks in the risk table, but these are matched to the color of the lines. I know there is an option to use linetype but with a lot of censored data (like mine) it's difficult to see linetype.

I have a few suggestions: 
-instead of tick marks, use numbers that can be defined in a separate legend for the plot. Currently, there is one legend used for both the plot and the tick marks (crude example attached, with the number 4 illustrating the example), or use a, b, c, to not confuse the years on the x-axis

![image](https://user-images.githubusercontent.com/31516466/30119709-9f0953c0-92f4-11e7-9b8f-938a9558eae8.png)

-Another option could be to  create a separate legend for the risk table that can utilize abbreviated terms while the full terms are present in the plot legend. The legend contains long terms so it is not figure-friendly to include them as the risk table text. For example, I can define complete terms in the plot legend with the abbreviations mentioned (Luminal A (LuA)...etc) and then set up the risk table to only use the shortened version for the risk table text (LuA).

![image](https://user-images.githubusercontent.com/31516466/30119889-41aff962-92f5-11e7-9de6-fa1ff08a9a73.png)

Thank you!

**Comment by kassambara** [comment]
Thank you for this well presented issue.

I'm not sure it's really necessary to create additional arguments in ggsurvplot().

Recall that ggsurvplot() returns a list of ggplots: list(plot, table). Therefore ggplot2 verbs can be used to customize each component of ggsurvplot() as you want.

```{r}
library(survival)
library(survminer)

fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurv <- ggsurvplot(fit, data = lung, 
                     risk.table = TRUE, tables.theme = clean_theme())
```
   
**Problem 1**: You want to change particularly the y axis text of the risk table.
**Solution 1**: Use ggplot2 verbs: scale_y_discrete(). A warning will be generated saying that we have already use scale for 'y', but don't worry about this. Simply ignore it.
   
   
```{r}
ggsurv$table <- ggsurv$table +
  scale_y_discrete(breaks = c("sex=1", "sex=2"), 
                   labels = rev(c("A", "B") ))
ggsurv
```
![rplot](https://user-images.githubusercontent.com/3313355/30121779-e4cd36f0-932c-11e7-802b-7ac12177188f.png)


**Problem 2**: You want to abbreviate legends in the risk table.
**Solution 2**: As solution 1

 
```{r}
ggsurv$table <- ggsurv$table +
  scale_y_discrete(breaks = c("sex=1", "sex=2"), 
                   labels = rev(c("S1", "S2") ))
ggsurv
```

![rplot14](https://user-images.githubusercontent.com/3313355/30121810-fa7bb74c-932c-11e7-8b11-a7c6e83e891f.png)

**Comment by shamav523** [comment]
Ah I didn't think to use scale_y_discrete! Thank you!
