### ISSUE TITLE
Black dots in risk table and problems with risktable height

### ISSUE THREAD

**Issue by Feli-Anna** [kassambara/survminer#25]
Hi there,

as I switched to a new laptop, I am now working with the updated version of survminer. I have two problems with the new version:

1.) I have black dots in my risk table (in the line of M1a and M1c). I am simply using the same code as with the last version, but they always show up if I add the risk table. It would be great to know how I can fix this!
This is my command from before:
`ggsurvplot(KMfit,pval=TRUE, risk.table=TRUE,risk.table.col = "strata", font.main = c(16, "plain", "black"), font.x = c(16, "plain", "black"), font.y = c(16, "plain", "black"), font.legend = c(14,"plain","black"),main="IVM Stage specific survival",legend="top",  legend.title="IVM status",legend.labs=c("M1a", "M1b", "M1c"))`

![ivm](https://cloud.githubusercontent.com/assets/17987328/13924582/3eb0a334-ef85-11e5-9ac7-9ceac172055f.jpeg)

2.) I have to define the risk.table.height each time now when I use the ggsurvplot command. Before, I could simply run it for 2-3 groups and the default size was fine. Now I get something like in the picture below.
Why is this not working anymore?

![jittered](https://cloud.githubusercontent.com/assets/17987328/13924834/1f3e3cb8-ef86-11e5-88d5-63994c811ced.jpeg)
Thank you
Feli

**Comment by kassambara** [comment]
Hi,

Thank you for reporting this issue. Points are removed from risk.table now.

Please install the latest version from GitHub and try this:  
 
```r
# Fit (complexe) survival curves
#++++++++++++++++++++++++++++++++++++
library(survminer)
require("survival")
fit2 <- survfit( Surv(time, status) ~ rx + adhere,
                data = colon )

# Visualize
#++++++++++++++++++++++++++++++++++++
ggsurvplot(fit2, pval = TRUE,
          risk.table = TRUE,
          risk.table.col = "strata",
          ggtheme = theme_bw())
```
Best Regards,
A. KASSAMBARA
