### ISSUE TITLE
Inconsistency between the font sizes in ggsurvplot

### ISSUE THREAD

**Issue by Swechhya** [kassambara/survminer#251]
I tried setting the font sizes for different parameters in ggsurvplot using the following code:

   ```
 library(survival)
    library(survminer)
    fit<- survfit(Surv(time, status) ~ sex, data = lung)
    ggsurvplot(fit, risk.table = TRUE,  risk.table.pos = "in", pval = TRUE,
               risk.table.fontsize = 5, pval.size = 5,
               font.x = 5, font.y = 5)
    
```
I get the following plot:
![image](https://user-images.githubusercontent.com/6251412/30467128-369fff10-9a00-11e7-899c-711e615ef93b.png)

I have set the font size for all the parameters as 5, but in the plot the p- value and risk table text appear larger than the axis labels.

**Comment by kassambara** [comment]
Yes, we are aware that, with ggplot2, there are an inconsistency between the font size of theme elements (axis labels, titles) and the font size of geom elements (geom_text).

With the following example, the axis title is almost invisible:

```r
library(ggplot2)

ggplot(mtcars, aes(mpg, wt))+
  geom_text(size = 5, label = rownames(mtcars))+
  theme(axis.title = element_text(size = 5)) # Change axis title font size
```
![rplot](https://user-images.githubusercontent.com/3313355/31212119-d435dad0-a99e-11e7-829a-ee7509c461cd.png)

In ggsurvplot(), the risk table is created using geom_text. ggsurvplot() inherits this inconsistency from ggplot2.   So, just increase the value of font.x and font.y to have a readable axis titles.
