### ISSUE TITLE
Custom fontsizes for risk table and legend position

### ISSUE THREAD

**Issue by jarbru** [kassambara/survminer#255]
Hi, 
I often need to make figures with multiple survival plots (1x2, 2x2, 2x3, 2x4 etc) for presentations and supplementaries for papers and reports. However, using survminer, I have trouble getting the fonts etc. to scale correctly. Notably, I have been trying customize the fontsizes for the risk table title and digits, but have been unable to find the correct code (I have tried to use f.ex. risk.table.title.size = c(8), risk.table.title.fontsize = c(8) and font.risk.table.title = c(8)). Is there an easy solution that eludes me?

Also, for these matrices of survival plots, it is often best to have common legend. How to position a common legend anywhere in the multiplot-figure? Can it be done using the arrange_ggsurvplots-function or is a more complex solution necessary?

  
Best regards,
Jarle Bruun

**Comment by kassambara** [comment]
As you might know, ggsurvplot() creates a list of ggplots with the following names:  
   
   
- plot: correponding to survival curves
- table: corresponding to the risk table

If you want to change graphical parameters, you can use ggplot verbs. Note also that, the function ggpar() [in ggpubr] provides an easy way to go: http://www.sthda.com/english/articles/24-ggpubr-publication-ready-plots/82-ggplot2-easy-way-to-change-graphical-parameters/


```{r}
# Create plots
library(survival)
library(survminer)
data(lung)
fit <- survfit(Surv(time, status) ~ sex, data = lung)
ggsurv <- ggsurvplot(fit, risk.table = TRUE,
                     tables.theme = clean_theme())

# Customize risk table title using ggplot verbs
ggsurv$table <- ggsurv$table +
  theme(plot.title = element_text(size = 10, color = "green", face = "bold"))

# Or Customize risk table title size using ggpar
ggsurv$table <- ggpubr::ggpar(ggsurv$table,
                              font.title = list(size = 10, color = "blue", face = "italic"))
# Print the plot
ggsurv

```

![rplot](https://user-images.githubusercontent.com/3313355/31271008-d89a8ed4-aa86-11e7-9962-f4a3cc2ac48f.png)


For arranged ggsurvplots with common legend, I dont have yet a ready to use solution. So, let's keep this issue open.

**Comment by jarbru** [comment]
Hi again, 

thank you so much for helping me out with this; I am unfortunately not very well versed in R, yet. Unfortunately, I do not see how I can use this code to reduce the fontsize of the Number at risk-digits, only the title. I have tried to find the parameters, without success. I manage to reduce the size of the tickslab beneath the Number at risk-digits (see new illustration attached). Is there an easy solution that eludes me?

Also, if you manage to implement functionality to arbitrarily place a common legend on a multiplot, that would be great. However, in the meantime, this can also be done in Adobe Illustrator.

Best regards,
Jarle
<img width="1280" alt="screen shot 2017-10-19 at 08 45 40" src="https://user-images.githubusercontent.com/13796113/31757879-3a45abae-b4ab-11e7-9a04-c35474358046.png">

**Comment by kassambara** [comment]
Concerning the risk table font size, specify the argument `fontsize` in `ggsurvplot()`:

```r
library(survminer)
library(survival)
data(lung)
fit <- survfit(Surv(time, status) ~ sex, data = lung)
ggsurvplot(fit, risk.table = TRUE, fontsize = 3)
```

**Comment by jarbru** [comment]
Thanks! I can´t believe I did not try that. I appreciate you taking time to also help out on basic issues like this.
<img width="1280" alt="screen shot 2017-10-19 at 18 55 56" src="https://user-images.githubusercontent.com/13796113/31783751-ae6efdce-b4ff-11e7-9cf3-f7990b3a92db.png">
