### ISSUE TITLE
Error when trying to load survminer in r

### ISSUE THREAD

**Issue by DenaFrancis** [kassambara/survminer#259]
### Expected behavior 
I am having a lot of trouble loading survminer into R once I install it. I have tried to restart R and I have re-installed R. I have the latest version (3.4.2. )

### Actual behavior
when I try to load the package it gives me this error:
Error: package or namespace load failed for ‘survminer’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘km.ci’

Any answers would be much appreciated...

**Comment by kassambara** [comment]
This might be related to the latest version of R. 

Does it work after installing the  `km.ci` package?

**Comment by DenaFrancis** [comment]
Thanks, I will try this...

**Comment by DenaFrancis** [comment]
Yes, it worked. Thanks!
