### ISSUE TITLE
Curve thickness - ggadjustedcurves

### ISSUE THREAD

**Issue by MaximilianTscharre** [kassambara/survminer#267]
I'm relatively new to R and sometimes still stumble over problems, which  I just cannot solve.

Until recently I used survminer 0.3.0  and had no problem adapting the curve thickness

Example data from the internet:
ggcoxadjustedcurves(res.cox, data = lung,
                   variable  = lung[, "sex"],   # Variable of interest
                   legend.title = "Sex",        # Change legend title
                   palette = "npg",             # nature publishing group color palettes
                   curv.size = 2                # Change line size
                   )

After updating to the latest version (survminer 0.4.1), is there an easy way to change the thickness of my curves?

ggadjustedcurves(versuch,                                    
                 data = df,                                  
                 method = "average",                     
                 variable = "trop",                         
                 palette = "npg",                             
                 title= "Adjusted survival",             
                 font.title=c(16, "bold"),                    
                 legend.title = "Trop",
                 font.legend = c(14, "bold"),
                 legend = c(0.2,0.2),                       
                 ylab = "Adjusted survival rate",           
                 xlab ="Follow-up in years",
                 xlim=c(0,10),                                
                 ylim=c(0,1),
                 font.y = c(14, "bold"),                   
                 font.x = c(14,"bold"),
                 font.tickslab = c(12, "bold"),
                 curv.size=3)      --> no changes whatsoever, also different spelling
       

     
Thank you in advance,
Max

**Comment by JasonHwa881026** [comment]
I have exactly the same problem as yours

**Comment by kassambara** [comment]
New argument `size` added now.

Please use the argument `size` instead of curve.size, thanks.

**Comment by JasonHwa881026** [comment]
Thanks for reply!
Well, I still can not adjust the curve thickness after using argument `size`. Do I need to update survminer package?

**Comment by kassambara** [comment]
yes, you need to install the latest developmental version: devtools::install_github("kassambara/survminer")

**Comment by JasonHwa881026** [comment]
thanks a lot!
I have already changed the curve size.
Thank you again very much! I mean it, because actually the curve size has beset me for about 10days.
I really appreciated it!

**Comment by ClauMD** [comment]
Hi I have a problem,  surv.scale =  "percent",  is not working with ggadjustedcurves

ggadjustedcurves(model, data=df, variable="PS", surv.scale =  "percent", xlim=c(0,5))

**Comment by reuchguang** [comment]
Hi, I was using your package `ggadjustedcurves` for a project and I stumbled on the following error when I tried to produce adjusted (averaged) curves per a grouping variable using the `variable=dataframe[,"grouping variable"]` option in the function. Please help me as I am really stumped! 

`error in `[.data.frame` (x, order(x, na.last = na.last, decreasing = decreasing)) : undefined colums selected` 

Thank you!
