### ISSUE TITLE
log x axis ONLY in ggsurvplot 

### ISSUE THREAD

**Issue by lameiraadriano** [kassambara/survminer#270]
How to log scale the x-axis ONLY in ggsurvplot (not fun=cloglog)?
Thank you in advance!

**Comment by MarcinKosinski** [comment]
@lameiraadriano 

having a simple plot

```{R}
library(survival)
require("survival")
fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurvplot(fit, data = lung)
```

you can't simply add `scale_x_log10()` as the plot starts at point X = 0, and log(0) is infinity.

Instead you can directly change your data using `log(x+1)` transformation that avoids infinity issues

```{R}
library(survival)
require("survival")
fit<- survfit(Surv(log(1+time), status) ~ sex, data = lung)
ggsurvplot(fit, data = lung)
```


@kassambara I think this can be closed (I can't do it as I'm not a collaborator on this repository.

**Comment by kassambara** [comment]
Thank you @MarcinKosinski. Your solution is simpler than what I have planed to do.
