### ISSUE TITLE
Please indicate in the docs that tables.theme is incremental to ggtheme

### ISSUE THREAD

**Issue by mwiesweg** [kassambara/survminer#273]
The effective theme used for the tables is
```R
ggtheme + tables.theme
```
It took me some time to figure that out. The docs are absolutely silent about that ("function, ggplot2 theme name...")
In addition, theme_cleantable is not a complete theme. That means when you specifiy
```R
ggtheme = my_custom_theme,
tables.theme = theme_cleantable()
```
you effectively inherit e.g. the panel grid from the ggtheme. A sufficient solution is:
```R
ggtheme = my_custom_theme,
tables.theme = theme_survminer() + theme_cleantable
```
Please indicate that in the docs!

survminer from github from today.
Thanks for survminer.

**Comment by kassambara** [comment]
I will take your suggestion into account, thanks.

**Comment by kassambara** [comment]
doc updated
