### ISSUE TITLE
confidence interval ribbon malfunction

### ISSUE THREAD

**Issue by wp07** [kassambara/survminer#275]
### Expected behavior 
Expect default function of cont.int = TRUE to be geom_ribbon.

### Actual behavior
Glitch which is causing CI internal shading to initially malfunction (see attached) by not giving ribbon.I believe this was supposed to be addressed in the 0.4.1 release (which I am using) but is persisting for me. Moreover, the problem is eliminated which use of the autoplot function as well as the conf.int.style = "step" so I there there is something malfunctioning with the default coding here.

### Steps to reproduce the problem
Reinstalled newest version of R
Uninstalled and reinstalled survminer package (0.4.1)
Successfully graphed with other functions such as autoplot to isolate problem
![screen shot 2018-01-01 at 12 05 50 am](https://user-images.githubusercontent.com/34994700/34465712-8b8fb6ba-ee87-11e7-9a52-d7a25b900fc1.png)
![screen shot 2018-01-01 at 12 06 05 am](https://user-images.githubusercontent.com/34994700/34465715-96b46464-ee87-11e7-91ae-654188e02566.png)

### `session_info()`

library(survival)
library(ranger)
library(ggplot2)
library(dplyr)
library(ggfortify)
library(readxl)
library(survminer)
library(rms)

fit <- survfit(Surv(time, event) ~group, data = wtsa)

ggsurvplot(
  fit, 
  data = wtsa,
  size = 1,
  palette = c("blue", "red"),
  xlab = "Years",
  #risk.table = TRUE,
  xlim = c(0:8),
  break.time.by = 2,
  break.y.by = 0.2,
  ylab = "Survival",
  conf.int = TRUE,
  conf.int.style = "ribbon",
  conf.int.alpha = 0.2,
  censor = FALSE,
  legend = c(0.2, 0.5),
  legend.title = "",
  legend.labs = c("All", "other"),
  ggtheme = theme_classic2())

**Comment by kassambara** [comment]
fixed now, thanks.

**Comment by wp07** [comment]
thanks!
