### ISSUE TITLE
can't change legend position with ggsurvplot and add points such as median in the plot

### ISSUE THREAD

**Issue by leirhyh** [kassambara/survminer#277]
### Expected behavior 
I should be able to place the legend in any position
### Actual behavior
Whatever I change the position of the legend,  the legend stay at the top.
### Steps to reproduce the problem
my code is as follows:
### `session_info()`

````{R}
fit2 <- survfit(Surv(DAY, EVENT) ~ EQTYPE, data = allsur1st)
pfit2 <- ggsurvplot(fit2,  main ="Survival curve with survminer", surv.median.line="none",
                    conf.int =TRUE, palette = c("orange", "skyblue", "#33cc99"), 
                    risk.table =FALSE, pval = FALSE,
                    xlim = c(0,600), xlab = "Time in days", ggtheme = theme_bw(),
                    legend = "bottom", legend.title = "Equipment Type", legend.labs = c("SDAG", "THC", "TRIP")
                     )
pfit2 + theme_survminer(
  font.main=c(16, "bold", "black"),
  font.x=c(14, "bold", "black"),
  font.y=c(14, "bold", "black"),
  font.tickslab=c(12, "plain", "black")
)
````

Is any way that I can add point to the plot with annotation?

**Comment by kassambara** [comment]
Hi, make sure that you have the latest version of survminer or install it as follow: `devtools::install_github("kassambara/survminer")`

This works for me: 

```{r}
library(survminer)
library(survival)
data(lung)
fit <- survfit(Surv(time, status) ~sex, data = lung)

p <- ggsurvplot(
  fit, risk.table = TRUE, legend = "bottom", 
  ggtheme = theme_bw()
  )
p

```

![ggsurvplot-with-bottom-legend](https://user-images.githubusercontent.com/3313355/34778429-9989810e-f61d-11e7-958e-e59056c42811.png)

To easily customize the plots, use the `ggpar()` helper functions:

```{r}
ggpar(p, font.main=c(16, "bold", "black") )
```
