### ISSUE TITLE
solution to long strata names in risk table legend

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#28]
If one considers this graph

````{R}
library(RTCGA.mutations)
library(dplyr)
library(survminer)
mutationsTCGA(BRCA.mutations, OV.mutations) %>%
 	filter(Hugo_Symbol == 'TP53') %>%
 	filter(substr(bcr_patient_barcode, 14, 15) == "01") %>% # cancer tissue
 	mutate(bcr_patient_barcode = substr(bcr_patient_barcode, 1, 12)) ->
	BRCA_OV.mutations
 
library(RTCGA.clinical)
survivalTCGA(
	BRCA.clinical,
	OV.clinical,
	extract.cols = "admin.disease_code"
	) %>%
 	dplyr::rename(disease = admin.disease_code) -> BRCA_OV.clinical

BRCA_OV.clinical %>%
 	left_join(
 		BRCA_OV.mutations,
 		by = "bcr_patient_barcode"
 		) %>%
 	mutate(TP53 = ifelse(!is.na(Variant_Classification), "Mut","WILDorNOINFO")) ->
	BRCA_OV.clinical_mutations
 
BRCA_OV.clinical_mutations %>%
	select(times, patient.vital_status, disease, TP53) -> BRCA_OV.2plot

kmTCGA(
	BRCA_OV.2plot,
	explanatory.names = c("TP53", "disease"),
	break.time.by = 400,
	xlim = c(0,2000)
	) -> km_plot
print(km_plot)
````

 ![rtcga km](http://rtcga.github.io/RTCGA/figure/source/Visualizations/unnamed-chunk-6-1.png) 
produced by `ggsurvplot` function, then one can notices that sometimes survival ruves are not very transparent because of the long names of stratas in the legend of risk table.

Do you think it would be possible to have coloured squares instead of names in the labels of risk table? And then the names of stratas could be coloured in regular legend above the survival-plot where there is more place ?

The example solution could look like this (poorly I had only 1 colour :P). This way the more spaced is designed for survival plot 

![img_5632](https://cloud.githubusercontent.com/assets/6773454/13984323/acf1b68c-f0f5-11e5-92b5-29597e013df4.JPG)

**Comment by MarcinKosinski** [comment]
@kassambara Do you by chance have any suggestion :)?

**Comment by kassambara** [comment]
It should work now:-)!

Note that, in ggsurvplot(), long strata names problem is detected when nchar > 5. But, may be we can set this to ~10.

```r
library("survminer")
require("survival")
fit2 <- survfit( Surv(time, status) ~ rx + adhere,
                data = colon )

ggsurvplot(fit2, pval = TRUE,
          break.time.by = 400,
          risk.table = TRUE,
          risk.table.col = "strata",
          risk.table.height = 0.5, # Useful when you have multiple groups
          palette = "Dark2", ggtheme = theme_bw())
```

![rplot01](https://cloud.githubusercontent.com/assets/3313355/14047229/e542110a-f2a6-11e5-8c1e-1e89f97cb173.jpeg)

**Comment by MarcinKosinski** [comment]
Amazing! 
Survival plots have never been so informative and well organized :)
Thank you!

**Comment by kassambara** [comment]
Thank you for this sweet comment:-)!
Best,
AK

**Comment by MarcinKosinski** [comment]
`Survival plots have never been so informative and well organized` like a title for a good blog post for r-bloggers about new feature :)

> long strata names problem is detected when nchar > 5. But, may be we can set this to ~10.

Does it mean it is being made automatically without user knowledge? Maybe it could be additional parameter: `trim.strata.names = TRUE` set to `TRUE` by defalut?

**Comment by MarcinKosinski** [comment]
@kassambara thanks for last commit :) What do you think about https://github.com/kassambara/survminer/issues/28#issuecomment-201754272 ?

**Comment by kassambara** [comment]
That's a good suggestion @MarcinKosinski!

Now, a new logical argument added in ggsurvplot: *risk.table.y.text*.  Default is TRUE. If FALSE, risk table y axis tick labels will be hidden.

```r
library(survival)
library(survminer)

fit2 <- survfit( Surv(time, status) ~ rx + adhere,
                data = colon )

#1. Default plot
ggsurvplot(fit2, pval = TRUE,
          risk.table = TRUE,
          risk.table.height = 0.5)

# 2. Hide risk table y axis texts
ggsurvplot(fit2, pval = TRUE,
          risk.table = TRUE,
          risk.table.height = 0.5,
          risk.table.y.text = FALSE)
```

1. **Default plot**: 

![rplot06](https://cloud.githubusercontent.com/assets/3313355/14077342/de784650-f4ea-11e5-90e3-1c38f992d885.png)

2. **Hide risk table y axis texts**
![rplot07](https://cloud.githubusercontent.com/assets/3313355/14077354/fc54d9c2-f4ea-11e5-9a6b-4ba89e6ea08f.png)

**Comment by MarcinKosinski** [comment]
Great. So we can close this issue :) You can Update NEWS with new parameter and You should really think about new post on R-bloggers about new functionalities in ggsurvplot :)

**Comment by kassambara** [comment]
NEWS updated! a new blog post and new CRAN version will be soon released:-)!

**Comment by shamav523** [comment]
This is a fantastic package and I use it all the time! I just ran into an issue though. Could there be an option to use numbers instead of the tick marks? The tick marks rely on color to tell curves apart and I need to generate a black and white figure. Another option could be to be able to create a separate legend for the risk table that can utilize abbreviated terms while the full terms are present in the plot legend. Thank you!

**Comment by MarcinKosinski** [comment]
Looks Like an idea for a new issue. @shamav523 can you open 2 new issues in this repo, so That we Keep remembering About this stuff? Thanks in the advance.

Marcin Kosinski

Dnia 31.08.2017 o godz. 18:13 shamav523 <notifications@github.com> napisał(a):
