### ISSUE TITLE
Conflict between ggplot legend options, and ggsurvplot().

### ISSUE THREAD

**Issue by PhonePong** [kassambara/survminer#281]
### Expected behavior 
Ability to modify/ add legend items after plot creation.
### Actual behavior
Creates second legend with duplicate entries.
### Steps to reproduce the problem
Ok, so say we are interested in the Kaplan-Meier estimate of only patients who died with cancer recurrence.
```R
# Use only uncensored subject data (those who died with recurrence)
colon.new <- merge(aggregate(time ~ id, data = colon, max), aggregate(status ~ id, data = colon, max))
colon.new <- colon.new[!(colon.new$status %in% 1), ]

# Create Kaplan-Maier estimate
colon.kaplan <- survfit(Surv(time) ~ 1, data = colon.new)

# Plot KM estimate
ggsurv.km <- ggsurvplot(colon.kaplan, legend = "right", legend.title = "LEGEND", legend.labs = c("Kaplan-Meier"), fun = 'event', ggtheme = theme_gray(), conf.int = TRUE, linetype = c(1), palette = "strata", censor = FALSE)
km.plot <- ggsurv.km + ggtitle("DEATH WITH RECURRENCE") + labs(subtitle = "(The Uncensored Data)", x ="TIME", y = "CDF")
```
Legend w/ Kaplan-Meier Item                                                                                                                 |
:-------------------------------------------------------------------------------------------------------------------------------:|
![Kaplan-Meier estimate](https://user-images.githubusercontent.com/12503205/34913686-f1089ac6-f8d1-11e7-88e2-1c64838e10e9.png)

Then, we might be interested in comparing Cox proportional hazard estimate as well.
```R
# Create Cox Proportional Hazard estimate
colon.coxPH <- survfit(coxph(Surv(time) ~ 1, data = colon.new))

# List both KM and coxPH estimates for overlay comparison
both.fits <- list(Kaplan = colon.kaplan, Cox = colon.coxPH)

# Plot KM estimate , combine = TRUE
ggsurv.both <- ggsurvplot(both.fits, legend = "right", legend.title = "LEGEND", legend.labs = c("Kaplan-Meier", "Cox PH"), linetype = c(1, 2), combine = TRUE, fun = 'event', ggtheme = theme_gray(), conf.int = TRUE, palette = "strata", censor = FALSE)
nonParametric.plot <- ggsurv.both + ggtitle("DEATH WITH RECURRENCE") + labs(subtitle = "(The Uncensored Data)", x ="TIME", y = "CDF")
```
Legend w/ both KM, and Cox Items                                                                                                                 |
:-------------------------------------------------------------------------------------------------------------------------------:|
![KM and Cox Overlay](https://user-images.githubusercontent.com/12503205/34913695-6f49d120-f8d2-11e7-8a40-51a0624b45bf.png)

Finally, we decide to see how a parametric distribution fit might look with the data. The extra legend item is added according to the example @ http://t-redactyl.io/blog/2016/03/creating-plots-in-r-using-ggplot2-part-9-function-plots.html and @ https://stackoverflow.com/questions/19950219/using-legend-with-stat-function-in-ggplot2

```R
library("fitdistrplus")

# Fit weibull distribution
colon.time <- colon.new$time
weib.fit <- fitdist(colon.time, distr = "weibull", method = "mle")

# > weib.fit
# Fitting of the distribution ' weibull ' by maximum likelihood 
# Parameters:
#   estimate Std. Error
# shape    7.241311  0.2588041
# scale 2517.689836 17.8897868

# Plot all, and add to legend
plot.all <- nonParametric.plot$plot + stat_function(fun = pweibull, size = 2, args = list(weib.fit$estimate[1], weib.fit$estimate[2]), aes(colour = "Weibull")) + scale_colour_manual(values = c("blue"))
```
However, when we try to draw the plot, ggplot complains there are not enough entries in the manual adjustment, because of the 2 previous survival fits/ plot.
```R
# > plot.all
# Error: Insufficient values in manual scale. 3 needed but only 1 provided.
```
So we go ahead and add 2 extra color items despite the fact we specified palette() in the call to ggsurvplot().
```R
# Plot all, and add to legend
plot.all <- nonParametric.plot$plot + stat_function(fun = pweibull, size = 1, args = list(weib.fit$estimate[1], weib.fit$estimate[2]), aes(colour = "Weibull")) + scale_colour_manual(values = c("green", "red","blue"))
```
 
Conflicting Legend Output                                                                                                                 |
:-------------------------------------------------------------------------------------------------------------------------------:|
![Chart showing bad legend](https://user-images.githubusercontent.com/12503205/34913766-1314c75a-f8d4-11e7-9545-db6f1b5083b5.png)

### `session_info()`

````{R}
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] fitdistrplus_1.0-9 bindrcpp_0.2       MASS_7.3-47       
 [4] scales_0.5.0       stringr_1.2.0      taRifx_1.0.6      
 [7] RCurl_1.95-4.8     bitops_1.0-6       XML_3.98-1.9      
[10] gridExtra_2.3      data.table_1.10.4  survminer_0.4.1.99
[13] survMisc_0.5.4     survival_2.41-3    ggpubr_0.1.6      
[16] magrittr_1.5       ggplot2_2.2.1      xlsx_0.5.7        
[19] xlsxjars_0.6.1     rJava_0.9-8       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11     pillar_1.0.1     compiler_3.4.0   plyr_1.8.4      
 [5] bindr_0.1        tools_3.4.0      digest_0.6.12    tibble_1.4.1    
 [9] nlme_3.1-131     gtable_0.2.0     lattice_0.20-35  pkgconfig_2.0.1 
[13] rlang_0.1.6      Matrix_1.2-9     psych_1.7.5      cmprsk_2.2-7    
[17] parallel_3.4.0   knitr_1.16       dplyr_0.7.4      glue_1.2.0      
[21] R6_2.2.2         KMsurv_0.1-5     km.ci_0.5-2      foreign_0.8-67  
[25] tidyr_0.7.2      purrr_0.2.4      reshape2_1.4.2   splines_3.4.0   
[29] assertthat_0.2.0 mnormt_1.5-5     xtable_1.8-2     colorspace_1.3-2
[33] labeling_0.3     stringi_1.1.5    lazyeval_0.2.0   munsell_0.4.3   
[37] broom_0.4.3      zoo_1.8-0
````
#279, #277, #276,  #278

**Comment by PhonePong** [comment]
It seems that if users wanted to use the full functionality of ggplot2 with ggsurvplot(), you would have to wrap all of ggplot's functionality into the ggsurvplot() call. Would it be easier/ more maintainable to somehow separate the plotting functionality from ggsurvplot? Just an idea for possible improvement. As an example, see this package: https://github.com/sachsmc/ggkm

**Comment by kassambara** [comment]
Hi,

Thank you again for this clear explanation of the issue.

First of all, note that, "strata" color palette is not supported in ggsurvplot.  Allowed values for the argument `palette` include "hue" (default),  "grey" for grey color palettes; brewer palettes e.g. "RdBu", "Blues", ...; or custom color palette e.g. c("blue", "red"); and scientific journal palettes from ggsci R package, e.g.: "npg", "aaas", "lancet", "jco", "ucscgb", "uchicago", "simpsons" and "rickandmorty"

I will use palette = "jco" in the following  R code.


If I understood your workflow, you are trying to do this: 
   
```{r}
create_two_ggplot_curves() + # km & cox fits : ggsurvplot(..., combine = TRUE)
  change_color_palette_by_taking_colors_from_jco_palette() +
  weibull_distribution()+
  change_color_palette_by_taking_only_one_color()  # blue color
```
    
There is no conflict here between ggplot() and ggsurvplot() legends.  From the best of my knoweledge, what you're trying to do is just not possible in the ggplot world: at the end of your ggplot workflow, you have three combined curves. So, if you want to customize the colors legend, then you need to provide three colors not only one blue color.  
   
   
So the code and the plot should look like as follow:   
  
```r
# Use only uncensored subject data (those who died with recurrence)
colon.new <- merge(aggregate(time ~ id, data = colon, max), aggregate(status ~ id, data = colon, max))
colon.new <- colon.new[!(colon.new$status %in% 1), ]

# 1. Km and cox fits
colon.kaplan <- survfit(Surv(time) ~ 1, data = colon.new)
colon.coxPH <- survfit(coxph(Surv(time) ~ 1, data = colon.new))

both.fits <- list(Kaplan = colon.kaplan, Cox = colon.coxPH)

ggsurv.both <- ggsurvplot(both.fits, legend = "right", legend.title = "LEGEND",
                          legend.labs = c("Kaplan-Meier", "Cox PH"), 
                          linetype = c(1, 2), combine = TRUE, fun = 'event', 
                          ggtheme = theme_gray(), conf.int = TRUE, 
                          palette = "jco", censor = FALSE)

nonParametric.plot <- ggsurv.both + 
  ggtitle("DEATH WITH RECURRENCE") + 
  labs(subtitle = "(The Uncensored Data)", x ="TIME", y = "CDF")

# 2. Fit weibull distribution
library("fitdistrplus")
colon.time <- colon.new$time
weib.fit <- fitdist(colon.time, distr = "weibull", method = "mle")


plot.all <- nonParametric.plot$plot + 
  stat_function(fun = pweibull, size = 2, args = list(weib.fit$estimate[1], weib.fit$estimate[2]), aes(colour = "Weibull")) 
```

![plot1](https://user-images.githubusercontent.com/3313355/34914498-4d2e207c-f914-11e7-86c8-a89e971e7988.png)



It can be seen that there are two legends in the plot.   Note that, the upper legend is for the curve line colors and the lower one is for the linetype aesthetic and the confidence band fill presents in the km and cox fits (but not in the weibull). As you might know, to remove legends for a specific aesthetic, it's possible to use this: 
   
```{r}
plot.all <- plot.all + guides(fill = FALSE, linetype = FALSE)
plot.all
```

![plot2](https://user-images.githubusercontent.com/3313355/34914504-634d0bac-f914-11e7-9cc6-54ba8bc7292d.png)
   

If you want to customize legend colors, ggplot requires three colors for the three line colors and two fill colors for the two confidence bands:
   
```{r}
plot.all + 
  scale_colour_manual(values = c("red", "green", "blue")) +
  scale_fill_manual(values = c("red", "green")) +
  guides(fill = FALSE, linetype = FALSE) # hide fill and linetype legends
```

![plot3](https://user-images.githubusercontent.com/3313355/34914537-ebf48066-f914-11e7-8bab-c01cea5f69c0.png)
   

You'll be warned that scale for 'colour' and 'fill' are already present. This is because we have already used palette = "jco" in the `ggsurvplot()` function to set curve line and fill colors. You can simply ignore this warning. However, if you want to avoid it, just don't use the option `palette` and stay with ggplot standard verbs (scale_colour_manual & scale_fill_manual).

**Comment by PhonePong** [comment]
OK...
First of all thank you very much for your prompt response (again)!
I would have answered sooner, except I've been LOST FOR HOURS discovering/ experimenting with ggplot's legend options.

Let me state that what I was trying to achieve is the look that occurs when the background of the legend  matches the confidence band color, and the linetype/ color match the line on the plot (all in one legend). I was not aware that ggplot separates the legend in the way you demonstrated above. 

So, I have another example in case other users might run into the same misunderstanding:
```R
# generate random weibull data
random.weib1 <- as.data.frame(rweibull(45, shape = .5, scale = 1))
names(random.weib1) <- "dat1"
random.weib2 <- as.data.frame(rweibull(45, shape = 1.5, scale = 1))
names(random.weib2) <- "dat2"

# fit Kaplan-Meier Estimate
weib1.kaplan <- survfit(Surv(dat1) ~ 1, data = random.weib1)
weib2.kaplan <- survfit(Surv(dat2) ~ 1, data = random.weib2)

# list both kaplan estimates
both.fits <- list(Kaplan.1 = weib1.kaplan, Kaplan.2 = weib2.kaplan)

# fit weibull distribution
weib.fit1 <- fitdist(random.weib1$dat1, distr = "weibull", method = "mle")
weib.fit2 <- fitdist(random.weib2$dat2, distr = "weibull", method = "mle")

# plot both
ggsurv.both <- ggsurvplot(both.fits, 
                          legend = "right",
                          legend.labs = c("Random 1", "Random 2"),
                          linetype = c(2, 3),  
                          conf.int = TRUE,
                          combine = TRUE,
                          palette = "jco",
                          fun = 'event', 
                          ggtheme = theme_gray(), 
                          censor = FALSE)

all.plot <- ggsurv.both + 
  ggtitle("A LOT OF LEGENDS!") + 
  labs(subtitle = "but where's the size legend?...", x ="TIME", y = "CDF")+
  stat_function(fun = pweibull,
                size = 2,
                args = list(weib.fit1$estimate[1],
                            weib.fit1$estimate[2]),
                aes(color = "Weibull Fit 1")) +
  stat_function(fun = pweibull,
                size = 1,
                args = list(weib.fit2$estimate[1],
                            weib.fit2$estimate[2]),
                aes(color = "Weibull Fit 2")) + 
  guides(color = guide_legend(title = "COLOR LEGEND"),
         fill = guide_legend(title = "FILL LEGEND"),
         linetype = guide_legend(title = "LINETYPE LEGEND"),
         size = guide_legend(title = "SIZE LEGEND")) +
  coord_cartesian(xlim = c(0, 4))

``` 
Many Legends                                                                                                                 |
:-------------------------------------------------------------------------------------------------------------------------------:|
![Chart Showing Many Legends](https://user-images.githubusercontent.com/12503205/34922498-aecb913a-f95e-11e7-9ff6-b95d6bec83b0.png)

So here, its clear to see that the color, linetype, and fill have been specified with the linetype and palette() options from the ggsurvplot() call (as you stated).  However, 1) note that there is no size legend, although I specified size in the stat_functions, and 2) what happens if I want to change/ add linetypes of the stat_functions?
```R
# plot both
ggsurv.both <- ggsurvplot(both.fits, 
                          legend = "right",
                          legend.labs = c("Random 1", "Random 2"),
                          linetype = c(2, 3),  
                          conf.int = TRUE,
                          combine = TRUE,
                          palette = "jco",
                          fun = 'event', 
                          ggtheme = theme_gray(), 
                          censor = FALSE)

all.plot <- ggsurv.both + 
  ggtitle("A LOT OF LEGENDS!") + 
  labs(subtitle = "but where's the size legend?...", x ="TIME", y = "CDF")+
  stat_function(fun = pweibull,
                size = 2,
                args = list(weib.fit1$estimate[1],
                            weib.fit1$estimate[2]),
                aes(color = "Weibull Fit 1")) +
  stat_function(fun = pweibull,
                size = 1,
                args = list(weib.fit2$estimate[1],
                            weib.fit2$estimate[2]),
                aes(color = "Weibull Fit 2")) + 
  guides(color = guide_legend(title = "COLOR LEGEND"),
         fill = guide_legend(title = "FILL LEGEND"),
         linetype = guide_legend(title = "LINETYPE LEGEND"),
         size = guide_legend(title = "SIZE LEGEND")) +
  coord_cartesian(xlim = c(0, 4)) +
scale_linetype_manual(values = c("dotted", "dashed") # <----------- Try to add linetypes here
``` 
It gives a warning,
````{R}
Scale for 'linetype' is already present. Adding another scale for
'linetype', which will replace the existing scale.
````
and changes the line types specified in ggsurvplot. Ok, so then I'll comment out the ggsurvplot linetype option, and change the scale_linetype_manual call:
```R
# plot both
ggsurv.both <- ggsurvplot(both.fits, 
                          legend = "right",
                          legend.labs = c("Random 1", "Random 2"),
                          #linetype = c(2, 3),         # <---------------------- Commented This
                          conf.int = TRUE,
                          combine = TRUE,
                          palette = "jco",
                          fun = 'event', 
                          ggtheme = theme_gray(), 
                          censor = FALSE)

all.plot <- ggsurv.both + 
  ggtitle("A LOT OF LEGENDS!") + 
  labs(subtitle = "but where's the size legend?...", x ="TIME", y = "CDF")+
  stat_function(fun = pweibull,
                size = 2,
                args = list(weib.fit1$estimate[1],
                            weib.fit1$estimate[2]),
                aes(color = "Weibull Fit 1")) +
  stat_function(fun = pweibull,
                size = 1,
                args = list(weib.fit2$estimate[1],
                            weib.fit2$estimate[2]),
                aes(color = "Weibull Fit 2")) + 
  guides(color = guide_legend(title = "COLOR LEGEND"),
         fill = guide_legend(title = "FILL LEGEND"),
         linetype = guide_legend(title = "LINETYPE LEGEND"),
         size = guide_legend(title = "SIZE LEGEND")) +
  coord_cartesian(xlim = c(0, 4)) +
scale_linetype_manual(values = c("dotted", "dashed", "dotdash","solid")#<--Try all linetypes here
``` 
linetype Legend Disappears!                                                                                                                 |
:-------------------------------------------------------------------------------------------------------------------------------:|
![Legend disappears](https://user-images.githubusercontent.com/12503205/34922865-61a50288-f963-11e7-9ca1-61c76c070003.png)

Here, we can see that the linetype legend has disappeared, AND that no linetypes have been specified. Also there is still no size legend, and note that the size of the line items in the COLOR legend are size = 2.

To recap, I would love to display the background color of confidence intervals, the linetype, and colors of lines (possibly other options like shapes) all in one legend. It appears in order to do this, I would have to use `overide.aes = list(...)` inside of `guide_legend(...)` in one of the legend `guides(...)` (i.e. ` guides(color = guide_legend(override.aes(...)))` ...WHEW!).

The problem seems to be if I would like to edit the legend, which guide should I choose? Is it the case to have complete control over the legend, I should leave the legend options blank in the call to ggsurvplot()? What is the best approach?

I've found solutions to similar problems at these links (the first being close to what I want to achieve:
* https://stackoverflow.com/questions/37140266/how-to-merge-color-line-style-and-shape-legends-in-ggplot
* https://stackoverflow.com/questions/19950219/using-legend-with-stat-function-in-ggplot2
* https://stackoverflow.com/questions/26480886/combine-legend-for-several-stat-function-lines-and-raw-data-points
* https://stackoverflow.com/questions/28872875/ggplot2-applying-width-of-line-to-the-legend-key
* https://stackoverflow.com/questions/14604435/turning-off-some-legends-in-a-ggplot
* http://ggplot2.tidyverse.org/reference/guides.html

At this point, while I think the problem is more focused, it seems like it is not exactly a `ggsurvplot(...)` problem so much as it is a use case (combined with all the ggplot legend options, it is quite confusing).

If you think this is the case, feel free to close the issue (perhaps label it as features/ userland?).

Thanks ahead for your time and consideration!
-jim

**Comment by kassambara** [comment]
For me, this is a ggplot problem (not ggsurvplot)

Let's start by a simple example:  


```{r}
library(survival)
library(survminer)

data("lung")
fit <- survfit(Surv(time, status) ~ sex, data = lung)
```

1) **linetype** argument documentation in ggsurvplot(): Allowed values includes i) "strata" for changing linetypes by strata (i.e. groups); ii) a numeric vector (e.g., c(1, 2)) or a character vector c("solid", "dashed").


Change linetype by strata and then scale it manually: 

```{r}
ggsurv <- ggsurvplot(fit, linetype = "strata")

ggsurv$plot + scale_linetype_manual(values = c("solid", "dotdash"))
```
      
      
as strata (group) is a discrete variable, it is not advised to use `size = "strata"` in ggsurvplot(). But, in the following example, we'll do it for demonstration purpose; because you want to have size in the legend.
    
2) **size** aesthetic in the legend:
    
    
In order to have weibull fit 1/2 color in the legend, you used `aes(color = "Weibull Fit 1")` and `aes(color = "Weibull Fit 2")`.   
   
So, if you want to have size aesthetic in the legend, you need to use the same philosophy: `aes(color = "Weibull Fit 1", size = "Weibull Fit 1")` and so on... This phylosophy holds true for any other ggplot aesthetics.


Your final code and plot should look like this: 



```{r}
library(fitdistrplus)
# generate random weibull data
random.weib1 <- as.data.frame(rweibull(45, shape = .5, scale = 1))
names(random.weib1) <- "dat1"
random.weib2 <- as.data.frame(rweibull(45, shape = 1.5, scale = 1))
names(random.weib2) <- "dat2"

# fit Kaplan-Meier Estimate
weib1.kaplan <- survfit(Surv(dat1) ~ 1, data = random.weib1)
weib2.kaplan <- survfit(Surv(dat2) ~ 1, data = random.weib2)

# list both kaplan estimates
both.fits <- list(Kaplan.1 = weib1.kaplan, Kaplan.2 = weib2.kaplan)

# fit weibull distribution
weib.fit1 <- fitdist(random.weib1$dat1, distr = "weibull", method = "mle")
weib.fit2 <- fitdist(random.weib2$dat2, distr = "weibull", method = "mle")

# plot both
ggsurv.both <- ggsurvplot(both.fits, 
                          legend = "right",
                          legend.labs = c("Random 1", "Random 2"),
                          linetype = "strata",  # <<<==========================
                          size = "strata", # <<<==========================
                          conf.int = TRUE,
                          combine = TRUE,
                          palette = "jco",
                          fun = 'event', 
                          ggtheme = theme_gray(), 
                          censor = FALSE)

all.plot <- ggsurv.both$plot +  # <<<==========================
  ggtitle("A LOT OF LEGENDS!") + 
  labs( x ="TIME", y = "CDF")+
  stat_function(fun = pweibull,
                args = list(weib.fit1$estimate[1],
                            weib.fit1$estimate[2]),
                aes(color = "Weibull Fit 1", size = "Weibull Fit 1", linetype = "Weibull Fit 1")) +
  stat_function(fun = pweibull,
                args = list(weib.fit2$estimate[1],
                            weib.fit2$estimate[2]),
                aes(color = "Weibull Fit 2", size = "Weibull Fit 2", linetype = "Weibull Fit 2")) + 
  guides(color = guide_legend(title = "COLOR LEGEND"),
         fill = guide_legend(title = "FILL LEGEND"),
         linetype = guide_legend(title = "LINETYPE LEGEND"),
         size = guide_legend(title = "SIZE LEGEND")) +
  coord_cartesian(xlim = c(0, 4))


all.plot + 
  scale_linetype_manual(values = c("dotted", "dashed", "dotdash","solid")) +
                          scale_size_manual(values = c(1,1.3, 1.5, 2))
```

![rplot](https://user-images.githubusercontent.com/3313355/34933826-a70f54ca-f9d8-11e7-85ce-f6d37683314a.png)

**Comment by PhonePong** [comment]
Wow! So many options, and I'd say definitely a ggplot thing.

Thanks a ton for your prompt input. I will close this issue, and follow up later with my attempt at using `override.aes(...)`, and merging these legends into one to create the desired result.

-jim
