### ISSUE TITLE
Merging survival curves on a KM fit model

### ISSUE THREAD

**Issue by qalid7** [kassambara/survminer#282]
First of all, many thanks for this absolutely wonderful package! I use it pretty much on a daily basis!

I've seen the two related issues (https://github.com/kassambara/survminer/issues/97, https://github.com/kassambara/survminer/issues/226), and have also tried the useful pairwise_survdiff.R function.

However, my suggestion/request is simpler. How can I merge survival curves within the same fit?

For example, merge the three groups (red, purple and green) in the below fit (into one group/curve) and see how the separation would look like against the cyan group - does that make sense?  

Basically, how to produce the survival curves presented as shown in (https://github.com/kassambara/survminer/issues/97)? 

Working on TCGA Lung, I can tell this would be a formidable tool especially when we combine 2+ variables on a KM fit.

PS. I realize sex shouldn't be used in surv_cutpoint, this is just a quick reproducible example. 

```
data(lung)
cut <- surv_cutpoint(lung, time = "time", event = "status", minprop = 0.2,
                             variables = c("ph.ecog", "ph.karno", "pat.karno", "sex"))
cat <- surv_categorize(cut)
fit <- survfit(Surv(time, status) ~ ph.ecog+sex, data = cat)
ggsurvplot(fit, data = cat, risk.table = TRUE, pval=TRUE)
```

![image](https://user-images.githubusercontent.com/35524818/35037356-318e5faa-fb6f-11e7-96d3-5d9c6a08c7d0.png)

Thanks a lot!

**Comment by kassambara** [comment]
Hi,

The easiest way to go is to create a new grouping variable into the `cat` data frame. 

For example:

```r
library(dplyr)

data(lung)
cut <- surv_cutpoint(lung, time = "time", event = "status", minprop = 0.2,
                     variables = c("ph.ecog", "ph.karno", "pat.karno", "sex"))

cat <- surv_categorize(cut)
cat <- cat %>%
  mutate(custom.grps = ifelse(ph.ecog == "low" & sex == "high", 1, 0))

fit <- survfit(Surv(time, status) ~ custom.grps, data = cat)
ggsurvplot(fit, data = cat, risk.table = TRUE, pval=TRUE)

```

![rplot](https://user-images.githubusercontent.com/3313355/35181313-cefa68cc-fdbf-11e7-8d51-bf0936422c65.png)

**Comment by qalid7** [comment]
Wonderful! Thanks.
