### ISSUE TITLE
Change the position of the p value (pval) on the plot

### ISSUE THREAD

**Issue by ejoffe19** [kassambara/survminer#303]
### `session_info()`

````{R}
# please paste here the result of
devtools::session_info()
````

**Comment by ejoffe19** [comment]
Hi,

First off, great package. Thank you !!!
Is there a way to control the coordinates of the pval and move it closer to the 0,0 point ?

**Comment by kassambara** [comment]
Hi,

You can specify the argument `pal.coord`  as follow:

```r
library(survminer)
library(survival)

fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurvplot(
  fit, risk.table = TRUE, ggtheme = theme_bw(),
  pval = TRUE, pval.coord = c(0, 0.03)
  )
```

![rplot25](https://user-images.githubusercontent.com/3313355/42003607-9c4b94b2-7a6c-11e8-9593-ed2d2736a0a0.png)


Read more at: http://www.sthda.com/english/rpkgs/survminer/reference/ggsurvplot.html
