### ISSUE TITLE
issue template

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#31]
@kassambara  Have you considered adding an issue template?
https://github.com/RTCGA/RTCGA/blob/master/ISSUE_TEMPLATE.md
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by MarcinKosinski** [comment]
@kassambara that's good idea for future contributors or potential users with users' requests.

Possible options to this issue
a) YES
b) NO

**Comment by kassambara** [comment]
a:-)!
