### ISSUE TITLE
question about risk table in survival analysis 

### ISSUE THREAD

**Issue by Siahrood** [kassambara/survminer#319]
I have tried to read some of your code about survival analysis and apply them, but the case is theme were not applying to risk table. And following are my codes and result by R . Would you please take a look and advise me about my problem ? 

ggsurvplot(kmsurvival, data = Data, 
           surv.median.line = "hv",       # add the median survival pointer.
           xlim = c(0,Max),  
           break.time.by =breakt,
           ggtheme = theme_light(),
           conf.int = TRUE,
           censor=TRUE, 
           tables.height = 0.15 ,
           tables.theme = theme_cleantable(),
           risk.table.y.text.col = T,     # colour risk table text annotations.
           risk.table.y.text = FALSE,     # show bars instead of names in text annotations
           palette = "#2E9FDF",
           xlab="Mileage",risk.table = TRUE,
           title = "                         Survival curve based on Kaplan-Meier estimates",
           risk.table.col = "strata",lienetype = "strata",
           legend.title = paste(part1, part2) , 
           font.legend = c(14, "bold.italic", "red"),
           font.title = c(16, "bold", "darkblue"),
           font.main = c(16, "bold", "darkblue"),          # font for titles of the plot, the table and censor part
           font.x = c(10, "bold.italic", "darkred"),
           font.y = c(10, "bold.italic", "darkred"),
           font.tickslab = c(10, "plain", "darkgreen"),
           risk.table.title = "Number at risk"  )

**Comment by MarcinKosinski** [comment]
@Siahrood can you provide plots as a result of the code? can you include an example data that we also could use for testing? So far we don't have `Data` on our local machines. More over, can you paste the result of the `sessionInfo()` function so we know which versions of packages do you use?

If you want to properly format your comment read about markdown language https://guides.github.com/features/mastering-markdown/

**Comment by Siahrood** [comment]
[test.pdf](https://github.com/kassambara/survminer/files/2141469/test.pdf)
Plot file is attached. unfortunately we have a strong policy for data confidentiality and I cannot share them. I hope still I can get help. My question is about risk table that I have no control for changing font , size , color ,etc. I have used the same code that you have had in the following link but result are not applying on my risk table. 
http://r-addict.com/2017/01/15/Too-Far-With-Survival-Plots.html

Best Regards

**Comment by MarcinKosinski** [comment]
@Siahrood you are trying to edit the font that present the number of the risk set?
with `font` parameters I think one can only edit axis, titles and labels but not exactly numbers presented in the risk table

**Comment by kassambara** [comment]
Hi @Siahrood,

To control risk table font size and color, please read the documentation of `ggsurvplot()` (http://www.sthda.com/english/rpkgs/survminer/reference/ggsurvplot.html, section: Survival tables).

Example of R code:

```r
library(survminer)
library(survival)
fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurvplot(
  fit, data = lung, risk.table = TRUE, ggtheme = theme_bw(),
  risk.table.col = "steelblue", risk.table.fontsize = 6
  )
```

![rplot](https://user-images.githubusercontent.com/3313355/42002506-d58323ee-7a67-11e8-98cb-4a8c6f840a41.png)

**Comment by MarcinKosinski** [comment]
@kassambara this documentation is an immense and a great job! Wow. Amazing

**Comment by kassambara** [comment]
Thank you @MarcinKosinski for the positive feedback!

**Comment by Siahrood** [comment]
Thanks a lot @kassambara and @MarcinKosinski for your feedbacks. What I wanted to change was title , x-axis and y-axis color font size and style for risk table but what I could do was just color of numbers inside risk table  as you can see in my graph. So I remove them and just have title left now, which is still black. What I saw in @MarcinKosinski codes at http://r-addict.com/2017/01/15/Too-Far-With-Survival-Plots.html both survival graphs and risk tables "title and font size and color" have changed all together without extra coding for risk table. I dont know what should I do that make it happens for me too, even though I have about the same codes.

**Comment by Siahrood** [comment]
Hi and thousand thanks. Yes its working now.

**Comment by Siahrood** [comment]
I would appreciate if you help me with another question. I try to use pval=TRUE for having p-value, but I am receiving the following warning message: 

**Warning message:
In .pvalue(fit, data = data, method = method, pval = pval, pval.coord = pval.coord,  :
  There are no survival curves to be compared. 
 This is a null model.**
How should I correct it ?

**Comment by kassambara** [comment]
You're trying to add p-value for a null model (i.e: Surv(time, status) ~ 1). This is not possible. 

Log-rank test is used to compare two survival curves.

I think, we can close this issue.

**Comment by Siahrood** [comment]
Ok , now I understand it . Thanks .
