### ISSUE TITLE
Blog post about the short history of how survival plots were improved between survminer ver 0.1 and ver 0.2?

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#34]
This would be my entrance picture for this blog post :)
![survminer_blog](https://cloud.githubusercontent.com/assets/6773454/14755220/0702e9ae-08e1-11e6-8ba1-016e42c53e02.png)

I would like to write about how, with small my comments have you improved ggsurvplot function. This can be independent from your blog announcing differences between survminer ver 0.1 and ver 0.2 :)

**Comment by MarcinKosinski** [comment]
http://dev.to/rly

**Comment by kassambara** [comment]
Hi!

This is a very beautiful and persuasive cover design! Yes, please do it!! After your blog post, I'll announce the release of ver 0.2 when it is available on CRAN.

Thank you for the link. This will be a great help for my future "cover design"!!

**Comment by MarcinKosinski** [comment]
@kassambara what do you think of such blog post about differences between survminer ver 0.1.0 and 0.2.0 ? https://rawgit.com/MarcinKosinski/MarcinKosinski.github.io/master/_drafts/2016-05-20-Informative-Survival-Plots.html

I would like to post this  on my blog (and resubmit to r-bloggers) in a day or two. So feel free to provide changes (even lingusitic, since I am not a natvie :P) to this file https://github.com/MarcinKosinski/MarcinKosinski.github.io/blob/master/_drafts/2016-05-20-Informative-Survival-Plots.Rmd

**Comment by kassambara** [comment]
Hi @MarcinKosinski ,

Simply, It's a brilliant blog post, clear, concise and well written.  I've added a few minor changes.
Keep going and thanks for your contribution!!
A.

**Comment by MarcinKosinski** [comment]
Hi @kassambara I've seen that you have forked my repo, but you didn not provide commit nor PR.
https://github.com/kassambara/MarcinKosinski.github.io

Can I ask where have you added few minor changes? I've received a feedback from my friend that there are also few typos and linguistic issues, so I'll gather your feedback and his and I'll improve this post before I publish it on my blog, and then re-submit to r-bloggers :)

**Comment by kassambara** [comment]
Oups!

I sent to you the pull request now:-)!

**Comment by MarcinKosinski** [comment]
On r-bloggers now
http://www.r-bloggers.com/survival-plots-have-never-been-so-informative/

![r-bloggers_top](https://cloud.githubusercontent.com/assets/6773454/15468844/c942523a-20e6-11e6-9731-4c9949824697.png)

**Comment by MarcinKosinski** [comment]
Good question here :)
http://r-addict.com/2016/05/23/Informative-Survival-Plots.html#comment-2692945749

**Comment by MarcinKosinski** [comment]
@kassambara  by the way check statistics

https://www.facebook.com/rbloggers/posts/10153755904089891 - 150 likes on facebook fan-page
http://www.r-bloggers.com/survival-plots-have-never-been-so-informative/ - 300 shares on r-bloggers

Great job with this `ggsurvplot()` function!

**Comment by kassambara** [comment]
Waouuh! That's fantastic!! Thanks for this motivating work we did together. Let's keep it up!!
