### ISSUE TITLE
Risk table not aligned with plot

### ISSUE THREAD

**Issue by zoryfl** [kassambara/survminer#348]
### Expected behavior 
Risk table should be vertically aligned with plot, based on x-axis cuts. 

### Actual behavior
Risk table is not aligned with plot (and last values get cut off) (see picture).
![mismatch](https://user-images.githubusercontent.com/44613822/47743330-1c62e280-dc7f-11e8-93c4-a328421cc197.png)
I have found two previous issues here on github which supposedly got fixed (one of them had to do with the axes.offset=F option which I also use). I downloaded the newest survminer version from git, still have the same issue.
As you can see in my code below, I have a plot.margin which further aggravates the issue. If plotting without a margin the numbers will be cut off, though. There must be a way to combine both, no?

### Steps to reproduce the problem
My ggsurvplot code is as follows:
```
survplot1 <- ggsurvplot(surv1, 
                        ggtheme = ggplot2::theme_classic(12),
                        conf.int = FALSE,
                        pval = F, 
                        risk.table = T,
                        risk.table.pos = "out",
                        size = 1.5,
                        legend.labs = c("Low", "High"), 
                        legend.title = "Risk group     ", 
                        palette = c("lightskyblue", "firebrick"),
                        surv.scale = "percent", 
                        xlab = "Overall survival (days)",
                        ylim = c(0, 0.2),
                        xlim = c(0, 720),
                        censor = F,
                        axes.offset = F,
                        break.time.by=90,
                        fun = "event")

survplot1$plot <- survplot1$plot %++%
                        annotate("text", x = 400, y = 0.170, label = str_c(hrr, pp, sep = "\n"), hjust = 0, size = 5) %++%
                        theme(plot.margin = unit(c(5, 15, 5, 5), "mm"), legend.text = element_text(size = 12)) %++%
                        geom_vline(xintercept = 30, linetype = "dashed") %++%
                          annotate("text", x = 30, y = 0.195, label = "30d", hjust = -0.5) %++%
                        geom_vline(xintercept = 180, linetype = "dashed") %++%
                          annotate("text", x = 180, y = 0.195, label = "180d", hjust = -0.5) %++%
                        geom_vline(xintercept = 360, linetype = "dashed") %++%
                          annotate("text", x = 360, y = 0.195, label = "360d", hjust = -0.5) %++%
                        geom_vline(xintercept = 720, linetype = "dashed") %++%
                          annotate("text", x = 710, y = 0.195, label = "720d", hjust = 1.2) 
```
### `session_info()`

````{R}
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Arch Linux                  
 system   x86_64, linux-gnu           
 ui       RStudio                                
               

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package           * version   date       lib source                               
  survival          * 2.43-1    2018-10-29 [1] CRAN (R 3.5.1)                       
 survivalAnalysis  * 0.1.0     2018-09-03 [1] CRAN (R 3.5.1)                       
 survminer         * 0.4.3.999 2018-10-30 [1] Github (kassambara/survminer@1046ef7)
 survMisc            0.5.5     2018-07-05 [1] CRAN (R 3.5.1)                       
````

Any help is appreciated, thank you very much.

**Comment by zoryfl** [comment]
Figured out the solution. Turns out to not be a coding issue/bug but just a pain to set it up correctly.
Thanks.

**Comment by tiger-liang** [comment]
> 
> ### Expected behavior
> 
> Risk table should be vertically aligned with plot, based on x-axis cuts.
> ### Actual behavior
> 
> Risk table is not aligned with plot (and last values get cut off) (see picture).
> ![mismatch](https://user-images.githubusercontent.com/44613822/47743330-1c62e280-dc7f-11e8-93c4-a328421cc197.png)
> I have found two previous issues here on github which supposedly got fixed (one of them had to do with the axes.offset=F option which I also use). I downloaded the newest survminer version from git, still have the same issue.
> As you can see in my code below, I have a plot.margin which further aggravates the issue. If plotting without a margin the numbers will be cut off, though. There must be a way to combine both, no?
> ### Steps to reproduce the problem
> 
> My ggsurvplot code is as follows:
> 
> ```
> survplot1 <- ggsurvplot(surv1, 
>                         ggtheme = ggplot2::theme_classic(12),
>                         conf.int = FALSE,
>                         pval = F, 
>                         risk.table = T,
>                         risk.table.pos = "out",
>                         size = 1.5,
>                         legend.labs = c("Low", "High"), 
>                         legend.title = "Risk group     ", 
>                         palette = c("lightskyblue", "firebrick"),
>                         surv.scale = "percent", 
>                         xlab = "Overall survival (days)",
>                         ylim = c(0, 0.2),
>                         xlim = c(0, 720),
>                         censor = F,
>                         axes.offset = F,
>                         break.time.by=90,
>                         fun = "event")
> 
> survplot1$plot <- survplot1$plot %++%
>                         annotate("text", x = 400, y = 0.170, label = str_c(hrr, pp, sep = "\n"), hjust = 0, size = 5) %++%
>                         theme(plot.margin = unit(c(5, 15, 5, 5), "mm"), legend.text = element_text(size = 12)) %++%
>                         geom_vline(xintercept = 30, linetype = "dashed") %++%
>                           annotate("text", x = 30, y = 0.195, label = "30d", hjust = -0.5) %++%
>                         geom_vline(xintercept = 180, linetype = "dashed") %++%
>                           annotate("text", x = 180, y = 0.195, label = "180d", hjust = -0.5) %++%
>                         geom_vline(xintercept = 360, linetype = "dashed") %++%
>                           annotate("text", x = 360, y = 0.195, label = "360d", hjust = -0.5) %++%
>                         geom_vline(xintercept = 720, linetype = "dashed") %++%
>                           annotate("text", x = 710, y = 0.195, label = "720d", hjust = 1.2) 
> ```
> 
> ### `session_info()`
> 
> ```
> ─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>  setting  value                       
>  version  R version 3.5.1 (2018-07-02)
>  os       Arch Linux                  
>  system   x86_64, linux-gnu           
>  ui       RStudio                                
>                
> 
> ─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>  package           * version   date       lib source                               
>   survival          * 2.43-1    2018-10-29 [1] CRAN (R 3.5.1)                       
>  survivalAnalysis  * 0.1.0     2018-09-03 [1] CRAN (R 3.5.1)                       
>  survminer         * 0.4.3.999 2018-10-30 [1] Github (kassambara/survminer@1046ef7)
>  survMisc            0.5.5     2018-07-05 [1] CRAN (R 3.5.1)                       
> ```
> 
> Any help is appreciated, thank you very much.

I have the same problem with you. I need your help if you resolve it. thank you very much!
