### ISSUE TITLE
unable to install survminer

### ISSUE THREAD

**Issue by Jncaton** [kassambara/survminer#353]
Hello,

I am using Jupyter Notebook and I am unable to install the package "survminer". When I try to install, I get this message:

also installing the dependencies ‘ggrepel’, ‘exactRankTests’, ‘mvtnorm’, ‘ggpubr’, ‘maxstat’, ‘cmprsk’

Warning message in install.packages("survminer"):
“installation of package ‘ggrepel’ had non-zero exit status”Warning message in install.packages("survminer"):
“installation of package ‘exactRankTests’ had non-zero exit status”Warning message in install.packages("survminer"):
“installation of package ‘mvtnorm’ had non-zero exit status”Warning message in install.packages("survminer"):
“installation of package ‘cmprsk’ had non-zero exit status”Warning message in install.packages("survminer"):
“installation of package ‘ggpubr’ had non-zero exit status”Warning message in install.packages("survminer"):
“installation of package ‘maxstat’ had non-zero exit status”Warning message in install.packages("survminer"):
“installation of package ‘survminer’ had non-zero exit status”Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

**Comment by kassambara** [comment]
Can't reproduce this, I hope you found a solution
