### ISSUE TITLE
Wrong "number at risk" in table

### ISSUE THREAD

**Issue by teigentler** [kassambara/survminer#36]
Dear all,

I`m currently analysing a larger cohort with long follow-up.
As you see in the plot all three groups seem to have the same number of subject (203) which is not true. The survfit identifies 203, 308 and 89 subjects.
Also the number of subjects at risk in the second group increases at week 126 again. This may be due to the fact that no data for the second group is available for this time point.
Did anymore else encounter similar problems?

I'm currently using the latest development version of survminer and R version 3.2.4 Revised (2016-03-16 r70336)

Best wishes

Thomas
![plot](https://cloud.githubusercontent.com/assets/18628021/14761837/8412a756-096b-11e6-864a-4b0f3a066c56.png)

**Comment by kassambara** [comment]
Did you have the latest version of survminer?
If this is not the case, please install it as follow:  

```r
devtools::install_github("kassambara/survminer")
```

As you can see below, using demo data and the latest version I didn't have this problem:
  
```r
library(survminer)
require("survival")
fit2 <- survfit( Surv(time, status) ~ rx + adhere,
                data = colon )

# Visualize
#++++++++++++++++++++++++++++++++++++

# Visualize: add p-value, chang y limits
# change color using brewer palette
# Adjust risk table and survival plot heights
ggsurvplot(fit2, pval = TRUE,
          break.time.by = 400,
          risk.table = TRUE,
          risk.table.col = "strata",
          risk.table.height = 0.5, # Useful when you have multiple groups
          palette = "Dark2")
```

![rplot](https://cloud.githubusercontent.com/assets/3313355/14761907/581421c8-096d-11e6-91e5-8129f2d8414b.png)

If you still have this problem, please let me know and send me a sample data.

```r
devtools::session_info()
```
```
Session info ------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.4 (2016-03-10)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.491)          
 language (EN)                        
 collate  fr_FR.UTF-8                 
 tz       Europe/Paris                
 date     2016-04-23                  

Packages ----------------------------------------------------------------------------------------------------
 package      * version date       source        
 colorspace     1.2-6   2015-03-11 CRAN (R 3.2.0)
 devtools     * 1.10.0  2016-01-23 CRAN (R 3.2.3)
 digest         0.6.9   2016-01-08 CRAN (R 3.2.3)
 ggplot2      * 2.1.0   2016-03-01 CRAN (R 3.2.4)
 gridExtra      2.2.1   2016-02-29 CRAN (R 3.2.4)
 gtable         0.2.0   2016-02-26 CRAN (R 3.2.3)
 labeling       0.3     2014-08-23 CRAN (R 3.2.0)
 magrittr       1.5     2014-11-22 CRAN (R 3.2.0)
 memoise        1.0.0   2016-01-29 CRAN (R 3.2.3)
 munsell        0.4.3   2016-02-13 CRAN (R 3.2.3)
 plyr           1.8.3   2015-06-12 CRAN (R 3.2.0)
 RColorBrewer   1.1-2   2014-12-07 CRAN (R 3.2.0)
 Rcpp           0.12.4  2016-03-26 CRAN (R 3.2.4)
 roxygen2       5.0.1   2015-11-11 CRAN (R 3.2.2)
 rstudioapi     0.5     2016-01-24 CRAN (R 3.2.3)
 scales         0.4.0   2016-02-26 CRAN (R 3.2.3)
 stringi        1.0-1   2015-10-22 CRAN (R 3.2.0)
 stringr        1.0.0   2015-04-30 CRAN (R 3.2.0)
 survival     * 2.38-3  2015-07-02 CRAN (R 3.2.4)
 survminer    * 0.2.1   <NA>       local         
 withr          1.0.1   2016-02-04 CRAN (R 3.2.3)
```
Best,
AK

**Comment by teigentler** [comment]
Thanks for your prompt reply. 
Unfortunately, the problem still exists even when updating to the latest survminer dev version.

Sending you a sample file.

Best wishes

Thomas

attach(sample)
time_to_mets <- Surv(time_to_met/30.43,Metastasen)
time_to_mets.fit <- survfit(time_to_mets ~ Thickness)
ggsurvplot(time_to_mets.fit, risk.table=TRUE,risk.table.y.text = FALSE, break.time.by = 6,pval=TRUE,xlim=c(0,140),ylim=c(0.5,1))
detach(sample)

Session info ---------------------------------------------------------------------------------------------------------------------------------
 setting  value                                      
 version  R version 3.2.4 Revised (2016-03-16 r70336)
 system   x86_64, mingw32                            
 ui       RStudio (0.99.893)                         
 language (EN)                                       
 collate  German_Germany.1252                        
 tz       Europe/Berlin                              
 date     2016-04-23                                 

Packages -------------------------------------------------------------------------------------------------------------------------------------
 package      * version   date       source                               
 acepack        1.3-3.3   2013-05-03 CRAN (R 3.2.3)                       
 assertthat     0.1       2013-12-06 CRAN (R 3.2.4)                       
 bootstrap      2015.2    2015-02-19 CRAN (R 3.2.3)                       
 Cairo        * 1.5-9     2015-09-26 CRAN (R 3.2.3)                       
 car          * 2.1-2     2016-03-25 CRAN (R 3.2.4)                       
 class          7.3-14    2015-08-30 CRAN (R 3.2.4)                       
 cluster        2.0.4     2016-04-18 CRAN (R 3.2.5)                       
 codetools      0.2-14    2015-07-15 CRAN (R 3.2.4)                       
 colorspace     1.2-6     2015-03-11 CRAN (R 3.2.4)                       
 cowplot      * 0.6.2     2016-04-20 CRAN (R 3.2.4)                       
 curl           0.9.7     2016-04-10 CRAN (R 3.2.4)                       
 DBI            0.3.1     2014-09-24 CRAN (R 3.2.4)                       
 devtools       1.11.1    2016-04-21 CRAN (R 3.2.5)                       
 digest         0.6.9     2016-01-08 CRAN (R 3.2.4)                       
 dplyr        * 0.4.3     2015-09-01 CRAN (R 3.2.4)                       
 e1071          1.6-7     2015-08-05 CRAN (R 3.2.4)                       
 evaluate       0.8.3     2016-03-05 CRAN (R 3.2.4)                       
 foreach        1.4.3     2015-10-13 CRAN (R 3.2.4)                       
 foreign        0.8-66    2015-08-19 CRAN (R 3.2.4)                       
 Formula      * 1.2-1     2015-04-07 CRAN (R 3.2.3)                       
 ggplot2      * 2.1.0     2016-03-01 CRAN (R 3.2.4)                       
 git2r          0.14.0    2016-03-13 CRAN (R 3.2.4)                       
 glmnet         2.0-5     2016-03-17 CRAN (R 3.2.4)                       
 gridExtra    * 2.2.1     2016-02-29 CRAN (R 3.2.4)                       
 gtable         0.2.0     2016-02-26 CRAN (R 3.2.4)                       
 hdnom        * 3.6       2016-03-25 CRAN (R 3.2.4)                       
 Hmisc        * 3.17-3    2016-04-03 CRAN (R 3.2.4)                       
 htmltools      0.3.5     2016-03-21 CRAN (R 3.2.5)                       
 httr           1.1.0     2016-01-28 CRAN (R 3.2.4)                       
 iterators      1.0.8     2015-10-13 CRAN (R 3.2.3)                       
 KernSmooth     2.23-15   2015-06-29 CRAN (R 3.2.4)                       
 knitr        * 1.12.3    2016-01-22 CRAN (R 3.2.4)                       
 labeling       0.3       2014-08-23 CRAN (R 3.2.3)                       
 lattice      * 0.20-33   2015-07-14 CRAN (R 3.2.4)                       
 latticeExtra   0.6-28    2016-02-09 CRAN (R 3.2.4)                       
 lava           1.4.3     2016-04-11 CRAN (R 3.2.4)                       
 lme4           1.1-12    2016-04-16 CRAN (R 3.2.5)                       
 lubridate    * 1.5.6     2016-04-06 CRAN (R 3.2.4)                       
 magrittr       1.5       2014-11-22 CRAN (R 3.2.4)                       
 MASS           7.3-45    2015-11-10 CRAN (R 3.2.4)                       
 Matrix         1.2-5     2016-04-17 CRAN (R 3.2.5)                       
 MatrixModels   0.4-1     2015-08-22 CRAN (R 3.2.4)                       
 memoise        1.0.0     2016-01-29 CRAN (R 3.2.4)                       
 mgcv           1.8-12    2016-03-03 CRAN (R 3.2.4)                       
 minqa          1.2.4     2014-10-09 CRAN (R 3.2.4)                       
 multcomp       1.4-4     2016-02-17 CRAN (R 3.2.4)                       
 munsell        0.4.3     2016-02-13 CRAN (R 3.2.4)                       
 mvtnorm        1.0-5     2016-02-02 CRAN (R 3.2.3)                       
 ncvreg         3.5-2     2016-04-09 CRAN (R 3.2.4)                       
 nlme           3.1-127   2016-04-16 CRAN (R 3.2.5)                       
 nloptr         1.0.4     2014-08-04 CRAN (R 3.2.4)                       
 nnet           7.3-12    2016-02-02 CRAN (R 3.2.4)                       
 pbkrtest       0.4-6     2016-01-27 CRAN (R 3.2.4)                       
 penalized      0.9-46    2016-04-19 CRAN (R 3.2.5)                       
 plyr           1.8.3     2015-06-12 CRAN (R 3.2.4)                       
 polspline      1.1.12    2015-07-14 CRAN (R 3.2.3)                       
 prodlim      * 1.5.7     2015-12-19 CRAN (R 3.2.4)                       
 quantreg       5.21      2016-02-13 CRAN (R 3.2.4)                       
 R6             2.1.2     2016-01-26 CRAN (R 3.2.4)                       
 RColorBrewer   1.1-2     2014-12-07 CRAN (R 3.2.3)                       
 Rcpp           0.12.4    2016-03-26 CRAN (R 3.2.4)                       
 readxl       * 0.1.1     2016-03-28 CRAN (R 3.2.4)                       
 rmarkdown      0.9.5     2016-02-22 CRAN (R 3.2.4)                       
 rmeta          2.16      2012-10-29 CRAN (R 3.2.3)                       
 rms          * 4.5-0     2016-04-04 CRAN (R 3.2.4)                       
 rpart          4.1-10    2015-06-29 CRAN (R 3.2.4)                       
 rstudioapi     0.5       2016-01-24 CRAN (R 3.2.4)                       
 sandwich       2.3-4     2015-09-24 CRAN (R 3.2.4)                       
 scales         0.4.0     2016-02-26 CRAN (R 3.2.4)                       
 SparseM      * 1.7       2015-08-15 CRAN (R 3.2.3)                       
 stringi        1.0-1     2015-10-22 CRAN (R 3.2.3)                       
 stringr        1.0.0     2015-04-30 CRAN (R 3.2.4)                       
 SuppDists      1.1-9.2   2016-01-21 CRAN (R 3.2.3)                       
 survAUC        1.0-5     2012-09-04 CRAN (R 3.2.4)                       
 survcomp     * 1.20.0    2015-10-14 Bioconductor                         
 survey         3.30-3    2014-08-15 CRAN (R 3.2.4)                       
 survival     * 2.39-2    2016-04-16 CRAN (R 3.2.5)                       
 survivalROC    1.0.3     2013-01-13 CRAN (R 3.2.3)                       
 survminer    * 0.2.1.900 2016-04-23 Github (kassambara/survminer@8a4ee27)
 tableone     * 0.7.3     2015-11-11 CRAN (R 3.2.4)                       
 TH.data        1.0-7     2016-01-28 CRAN (R 3.2.4)                       
 withr          1.0.1     2016-02-04 CRAN (R 3.2.4)                       
 yaml           2.1.13    2014-06-12 CRAN (R 3.2.4)                       
 zoo            1.7-12    2015-03-16 CRAN (R 3.2.4)

**Comment by kassambara** [comment]
Thank you for sending the data.
 
May be there is something wrong in the way you're fitting survival curves.

Use the following script:

```r
d <- read.csv2("sample.csv")
# convert time column
d$time_to_met <- d$time_to_met/30.43

# Fit survival curves
library("survival")
fit <- survfit( Surv(time_to_met, Metastasen) ~ Thickness,
                 data = d)
# Visualize with survminer
library("survminer")
ggsurvplot(fit, risk.table =TRUE, risk.table.y.text = FALSE, 
           break.time.by = 6, pval = TRUE, xlim = c(0,140), 
           ylim=c(0.5,1))
```

The output is as follow:
![rplot12](https://cloud.githubusercontent.com/assets/3313355/14762310/ac67dd78-0977-11e6-844b-779d83f2067b.png)



Again, let me know if it is ok so that I can close the issue.

Best,
AK

**Comment by teigentler** [comment]
Sorry, with my system I still have the problems with the wrong "number at risk" table. 
Checking my packages now.

**Comment by kassambara** [comment]
I think that something should be wrong with your system or R session.

Make sure to restart R/Rstudio and run the script again.

**Comment by teigentler** [comment]
Did so, but without success. Also installed latest R 64-Bit Version and reinstalled all packages under this version. Still got the wrong numbers. Will investigate further.

**Comment by teigentler** [comment]
The problem seems to be unrelated to survminer indeed. Plotting using the rms package gives the same wrong numbers.

**Comment by kassambara** [comment]
Good to know that!! Thank you

**Comment by teigentler** [comment]
Plotting with survival package 2.38-3 resulted in the right numbering. Updating to package 2.39-2 introduced the wrong numbering. So, the faulty numbering seems not to be related to survminer.

**Comment by kassambara** [comment]
Thank you for investigating the source of the problem. It would be nice to file an issue to the maintainer  of survival package to fix this problem. 

Have a Great Day,
AK

**Comment by teigentler** [comment]
Already done.

 

Thank you. Keep on with the survminer package. It is really welcome.

 

Best wishes

 

Thomas

 

PD Dr. Thomas Eigentler,
Coordinator, Interdisciplinary Skin Cancer Center
Dept. of Dermatology
Liebermeisterstr. 25
72076 Tuebingen, Germany

UNIVERSITÄTSKLINIKUM TÜBINGEN
Südwestdeutsches Tumorzentrum – CCC Tübingen-Stuttgart

Tel. +49 7071 298 5748
Fax.: +49 7071 29 5265
Email:  <https://webmail.uni-tuebingen.de/imp/basic.php?mailbox=TWFpbC9zZW50&buid=12099&page=message> thomas.eigentler@med.uni-tuebingen.de
Internet:  <http://www.hauttumorzentrum.de/> www.hauttumorzentrum.de

 

Von: Alboukadel KASSAMBARA [mailto:notifications@github.com] 
Gesendet: Montag, 25. April 2016 14:27
An: kassambara/survminer <survminer@noreply.github.com>
Cc: teigentler <thomas@eigentler.de>; Author <author@noreply.github.com>
Betreff: Re: [kassambara/survminer] Wrong "number at risk" in table (#36)

 

Thank you for investigating the source of the problem. It would be nice to file an issue to the maintainer of survival package to fix this problem. 

Have a Great Day,
AK

**Comment by kassambara** [comment]
Thank you!! so we can close this issue!
