### ISSUE TITLE
ggsurvplot with recurrent events; number at risk at t0 is 0

### ISSUE THREAD

**Issue by ekoraytascilar** [kassambara/survminer#361]
Number at risk at time 0 is 0 with recurrent event survival curves. Below is an example using the bladder1 dataset of survival package.

````{R}
#Load packages
library(survival)
library(survminer)

#Generate survival object
survobjbladder <- with(bladder1, 
                       Surv(start,stop, status==1,type = "counting"))

#generate K-M plot
ggsurvplot(survfit(survobjbladder~1,data = bladder1),risk.table =T,break.time.by=3)

````
![exampleplot](https://user-images.githubusercontent.com/10676301/51251150-e9381180-1998-11e9-815d-29723b0ad8d8.png)

> sessionInfo()
> R version 3.5.1 (2018-07-02)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] survminer_0.4.3 ggpubr_0.2      magrittr_1.5    ggplot2_3.1.0   survival_2.43-3
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.0        pillar_1.3.1      compiler_3.5.1    plyr_1.8.4        bindr_0.1.1       tools_3.5.1      
>  [7] digest_0.6.18     tibble_1.4.2      gtable_0.2.0      nlme_3.1-137      lattice_0.20-38   pkgconfig_2.0.2  
> [13] rlang_0.3.0.1     Matrix_1.2-15     rstudioapi_0.8    cmprsk_2.2-7      yaml_2.2.0        xfun_0.4         
> [19] bindrcpp_0.2.2    gridExtra_2.3     knitr_1.21        withr_2.1.2       dplyr_0.7.8       generics_0.0.2   
> [25] survMisc_0.5.5    grid_3.5.1        tidyselect_0.2.5  data.table_1.11.8 glue_1.3.0        R6_2.3.0         
> [31] KMsurv_0.1-5      km.ci_0.5-2       purrr_0.2.5       tidyr_0.8.2       scales_1.0.0      backports_1.1.3  
> [37] splines_3.5.1     assertthat_0.2.0  xtable_1.8-3      colorspace_1.3-2  labeling_0.3      lazyeval_0.2.1   
> [43] munsell_0.5.0     broom_0.5.1       crayon_1.3.4      zoo_1.8-4

**Comment by Juhu39** [comment]
Hey ekoraytascilar, hey all,

I have encountered the same problem! However, I do not have recurrent data. When I use "start" and "stop" time the problem occurs, but not when in "Surv" only "time" (and not "time2") is specified. See my example with fictional data.

Does anyone know how to solve this?

Thanks in advance and best regards!

![kaplan_narzeroatstart_github](https://user-images.githubusercontent.com/48056961/53492215-9de54880-3a98-11e9-94f5-604b3027ded5.jpg)

**Comment by ekoraytascilar** [comment]
I believe this was closed due to innatention. maybe we could @kassambara to comment whether the issue is tractable?

**Comment by Juhu39** [comment]
Hey ekoraytascilar, it seems to have been a problem of the "survival"-package (with n.risk-table). When I recently upgraded survival to 2.44-1.1 the problem vanished. Maybe it works for you too. Regards and good luck!

**Comment by ekoraytascilar** [comment]
Hey Juhu39
Thanks for the heads-up, it is indeed resolved!
![grafik](https://user-images.githubusercontent.com/10676301/61390044-51b96a00-a8ba-11e9-8466-ea96c2a01562.png)
