### ISSUE TITLE
Comparing survival for 2 curves at given timepoints in Survminer

### ISSUE THREAD

**Issue by rizmalik** [kassambara/survminer#372]
### Expected behavior 
Hello, I am fairly new to Survminer and completeley new to github, so apologies in advance if this query is basic or not in the correct format. 
I have a dataset _km_data2__, which gives the success of 2 surgical procedures (_1,2_) over time for 62 patients with unique _id_. Surgical failure is given by _status_=1. I produced a survival curves using the code:
fit <- survfit(Surv(fu,status)
               ~ type, data = km_data2)

ggsurvplot(fit, data = km_data2,
           censor=FALSE,
           conf.int = FALSE,
           pval = TRUE,
           pval.coord=c(15,20),
           fun = "pct",
           risk.table = FALSE,
           ggtheme = theme_bw(),
           palette = c("#7FC97F", "#BEAED4"),
           size = 1.5,
           xlim=c(0,70),
           break.time.by = 10,
           linetype = "strata",
           legend = "bottom",
           font.x = c(14, "bold", "black"),
           font.y = c(14, "bold", "black"),
           font.main = c(16, "bold", "darkblue"),
           xlab = "Time (weeks)",
           legend.labs = c("Baerveldt","AADI"),
           font.legend =c(12,12))

### Actual behavior
This is the plot:
![image](https://user-images.githubusercontent.com/46148747/53265355-1fcb1f80-36ef-11e9-93dd-eb65ea281ea4.png)

````{R}
As I understand it, the p value given is the logrank test for overall survival difference.
What I need to do is compare the survival for the 2 curves at given time points (e.g. t=20, 40 and 60 weeks), and I'm not sure how to do this... Can anybody advise?

Thank you
Riz

**Comment by rizmalik** [comment]
@kassambara .. any thoughts on this? 
Thanks
Can I use an F-test to compare survival for given timepoints?

**Comment by kassambara** [comment]
Does [this StackExchange discussion](https://stats.stackexchange.com/questions/188148/how-can-i-focus-the-log-rank-test-in-a-selected-period-of-time-of-follow-up) help?

See also [this other related discussion](https://stats.stackexchange.com/questions/377335/r-calculate-log-rank-p-value-of-survival-curve-at-specific-time).

**Comment by rizmalik** [comment]
Thank you, thats helpful
The discussion points to subsetting the data to include data before the time of interest and then performing the logrank test.. I was wondering if the survival and SE of both curves can be directly compared, but maybe this is not a valid approach..
