### ISSUE TITLE
Unable install "Survminer"

### ISSUE THREAD

**Issue by AlfattanKurniawan** [kassambara/survminer#376]
I cant install packages("Survminer) in my Jupiter Notebook & R

There's the warnings when I installed the "survminer"

“installation of package ‘ggplot2’ had non-zero exit status”Warning message in install.packages(c("survival", "survminer")):
“installation of package ‘survival’ had non-zero exit status”Warning message in install.packages(c("survival", "survminer")):
“installation of package ‘survminer’ had non-zero exit status”

**Comment by huzhishan** [comment]
encounter with the same problem

**Comment by huzhishan** [comment]
Problem solved. It may caused by the R-package installaiton in  conda. In anaconda, the package should be installed with `conda install -c r r-EXACTNAME` in terminal. You can try: `conda install -c r r-survminer`.
