### ISSUE TITLE
risk table color mismatch

### ISSUE THREAD

**Issue by ahdee** [kassambara/survminer#383]
### Expected behavior 
The color for each schema should match
### Actual behavior
The plot is in one color while the risk table label is reverse. So the plot below for example happy is blue while it is label in red for risk table. 
### Steps to reproduce the problem
```
set.seed(0)
simData <- data.frame(
    time=runif(n=200, min=20, max=200), 
    event=sample(x=c(0, 1), size=200, replace=TRUE), 
    state=sample(x=c("excited", "happy"), size=200, replace=TRUE)
    )

p <- ggsurvplot(fit=survfit(Surv(time=time, event=event) ~ state, data=simData), risk.table = T ) 
print(p)
```
![HBTZHbu 1](https://user-images.githubusercontent.com/9808122/56459966-4c4a9300-6350-11e9-9c8e-52941da8343c.png)

### `session_info()`

````{R}
# please paste here the result of
```
other attached packages:
 [1] ggbeeswarm_0.6.0    beeswarm_0.2.3      openxlsx_4.1.0      ggridges_0.5.1      data.table_1.12.0   stringr_1.4.0       gridExtra_2.3      
 [8] survminer_0.4.3.999 ggpubr_0.2          magrittr_1.5        ggplot2_3.1.0       survival_2.44-1.1 
``` 
````

**Comment by kassambara** [comment]
fixed now, thanks

**Comment by ahdee** [comment]
@kassambara thanks, works great now!

**Comment by Lulares** [comment]
Hi, 
I'm having the same problem with my data. 

Fit<-survfit(surv_pacientes.status_1 ~1) # NULL - curva dos pacientes tratados
Fit

Fit1 <- survfit(surv_pacientes.status_1 ~ pacientes.status_1$diagnostico, data = pacientes.status_1)
Fit1

Fit.list<-list(diagnostico=Fit1, fit.null=Fit)
ggsurv<-ggsurvplot(Fit.list, data = pacientes.status_1, censor=TRUE,
                   combine = TRUE, keep.data=TRUE,
                   surv.median.line = "hv",
                   pval = TRUE,
                   break.time.by=25,
                   risk.table = TRUE,
                   tables.y.text=FALSE,
                   risk.table.col = "strata",
                   risk.table.title = NULL,
                   title = "Overall survival",
                   legend.labs = c("ALL","AML","APL","All"),
                   xlab="Month",
                   ggtheme = theme_pubr())
ggsurv


[Rplot.pdf](https://github.com/kassambara/survminer/files/4480659/Rplot.pdf)
