### ISSUE TITLE
ggadjustedcurves

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#386]
@pbiecek please find below an e-mail I received from Therneau Terry:

Someone else pointed out ggadjustedcurves to me this AM and I took a look at the documentation.  

I'm glad to see a nice implementation of my ideas, but I think your labels are backwards.
Look at the first sentence of section 5 of the "Adjusted survival curves" vignette.

" In the marginal approach we first balance the data set and then compute results on the adjusted data. In the conditional approach we first compute a predicted survival curve for each subject that accounts for flc group, age and sex, and then take a weighted average of the curves to get an overall estimate for each flc group."

Your paragraph title "conditional" is actually a marginal estimate, ie., "balance then fit".   In my section 4.2 that final fit is done using survfit and you use coxph, but that is a second discussion.  

I think that your paragraph labeled 'marginal' is a replicate of my section 5.2,  which is a conditional estimate.

Terry Therneau

**Comment by pbiecek** [comment]
@kassambara thanks, I'm working on this

**Comment by pbiecek** [comment]
@kassambara 
In January we got an email from Junfeng Wang that labels are incorrect. So we flipped them in this commit
https://github.com/kassambara/survminer/commit/b247ea9cf758f0767c0b16aee4241eca50194282#diff-37802fdad937f2629a560b65048ac2e9

Does the comment above refer to this old wrong labels (in this case current version is correct)?

**Comment by kassambara** [comment]
Oh yes, it is the same issue! so I need to submit  v0.4.4 on CRAN now, thanks
