### ISSUE TITLE
A proposition for vignette

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#39]
What would you say if we create a vignette from this blog post :)? We could add this to package, and then it will appear on CRAN and on staticdocs if you rebuild them :)

#34 

http://www.r-bloggers.com/survival-plots-have-never-been-so-informative/

![r-bloggers_top](https://cloud.githubusercontent.com/assets/6773454/15468855/e9fdeb60-20e6-11e6-9c73-7c0c71909a2d.png)

**Comment by kassambara** [comment]
I was thinking about the same thing yesterday! It would be very nice to create a vignette from your article

**Comment by MarcinKosinski** [comment]
I'll provide PR in the evening. Then you can eventually extend/modify it :)

**Comment by kassambara** [comment]
Great!!!

2016-05-23 13:49 GMT+02:00 Marcin Kosiński <notifications@github.com>:
