### ISSUE TITLE
Error about survminer package and ggsurvplot function

### ISSUE THREAD

**Issue by HeiYinK** [kassambara/survminer#398]
how can i solve it: ### **Error: package or namespace load failed for ‘survminer’ in rbind(info, getNamespaceInfo(env, "S3methods")):
 number of columns of matrices must match (see arg _2)**

**Comment by kassambara** [comment]
Make sure you have installed correctly survminer. See also discussion https://github.com/kassambara/survminer/issues/394

**Comment by kassambara** [comment]
You can install the latest dev version as follow:

```r
devtools::install_github("kassambara/survminer", build_vignettes = FALSE)
```
