### ISSUE TITLE
conf.int for plotting Cox model with ggsurvplot()

### ISSUE THREAD

**Issue by edvbb** [kassambara/survminer#399]
I have my own data but I will show from an example from here [How to plot Cox model with ggsurvplot()?](https://github.com/kassambara/survminer/issues/67)

```
library("survival")
res.cox <- coxph(Surv(time, status) ~ age + sex + wt.loss, data =  lung)
res.cox
new_df <- with(lung,
               data.frame(sex = c(1, 2), 
                          age = rep(mean(age, na.rm = TRUE), 2),
                          wt.loss = rep(mean(wt.loss, na.rm = TRUE), 2)
               )
)
new_df
library(survminer)
fit <- survfit(res.cox, newdata = new_df)
ggsurvplot(fit, conf.int = TRUE, palette = "Dark2", 
           censor = FALSE, surv.median.line = "hv")
```
First I get
```
Error in .get_data(fit, data = data, complain = FALSE) : 
  The `data` argument should be provided either to ggsurvfit or survfit.
```

Ok, I can use `new_df` or `lung`

```
ggsurvplot(fit, data = lung, conf.int = TRUE, palette = "Dark2", 
           censor = FALSE, surv.median.line = "hv")
```

It works but without confidence intervals? what's wrong?
![image](https://user-images.githubusercontent.com/19487225/59745747-1ce7d200-927e-11e9-83cb-70971cb24dbd.png)

**Comment by kassambara** [comment]
Hi, this issue is related to discussion https://github.com/kassambara/survminer/issues/393

Already fixed in the latest dev version. Please, re-install the dev version and try it. Let me know if it works, so that we can close this issue
