### ISSUE TITLE
Blog history

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#40]
What do you think of adding a new section like `Blog history` to README.md where we could list all blog posts about survminer. I remeber you must have wrote earlier about survminer so that I have discovered survminer (probably you spread the word on `Users of R package` or something like that on Facebook group, where I am banned now :P dunno why).

**Comment by kassambara** [comment]
Good idea!! I added the section. Feel free to change it.

It's strange that you're banned from the Facebook group!! I remember that I was also removed once from this group last year without knowing why. I Just sent a request again: and I was instantly added :)

**Comment by MarcinKosinski** [comment]
looks good.
I have similar blog history on my other pet project
http://pbiecek.github.io/archivist/Posts.html
