### ISSUE TITLE
Problem with surv_pvalue()

### ISSUE THREAD

**Issue by ruzankin** [kassambara/survminer#403]
### Steps to reproduce the problem
f=as.formula("Surv(t,event=ev)~group")
s=survfit(f,data=d)
ggsurvplot(s)

After that I get the error: Object of type "symbol" is not subsettable.

The "usual" code
s=survfit(Surv(t,event=ev)~group,data=d)
ggsurvplot(s)

works correctly.

The error arises in surv_pvalue() function.

**Comment by kassambara** [comment]
You need to use `do.call()`:

```r
f <- as.formula("Surv(time, status) ~ sex")
fit <- do.call(survfit, list(formula = f, data = d))
ggsurvplot(fit, data = d)
```

or use the survminer `surv_fit()` function:

```r
fit2 <- surv_fit(f, data = d)
ggsurvplot(fit2)
````

**Comment by ruzankin** [comment]
Thank you very much!
