### ISSUE TITLE
Make legend title bold without making other legend components bold

### ISSUE THREAD

**Issue by eaperkowski** [kassambara/survminer#419]
### Expected behavior 
Change legend title to bold without changing all legend elements to bold face
### Actual behavior
Entire legend turns to bold, or error message about incompatibility
### Steps to reproduce the problem
See R code below for code. I'm creating a plot comparing survivorship of caterpillars feeding on one of four different leaf diets. The data isn't important to show in this case. I'm trying to make the legend title in **bold** face, however I'm finding that I'm not able to without making the entire legend in boldface. I've tried all of the different ways in ggplot-type plots to create a bold legend title, but each time I return an error message about how it's incompatible with ggsurvplot.

Any help would be appreciated.

````{R}
## An example of one of the R codes I used to bold the legend title
plot <- ggsurvplot(fit = survivorshipByTreat, 
                   data = survivorship,
                   legend.title = "Host Plant Diet", 
                   legend.labs = c("Paw paw",
                                   "Sassafras",
                                   "Spicebush",
                                   "Tulip Poplar"),
                   palette = "jco",
                   legend = "bottom",
                   font.legend = 13,
                   xlab = "Time from Hatch (Days)",
                   font.x = c(16, "bold"),
                   ylab = "Survival Proportion",
                   font.y = c(16, "bold"),
                   font.tickslab = 13,
                   theme(legend.title = element_text(face = "bold)))
````

**Comment by kassambara** [comment]
`ggsurvplot()`  returns a list of ggplot. So, you can modify each component using ggplot2 verb:

```r
require("survival")
# Fit survival and create ggsurvplot
fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurv <- ggsurvplot(fit, data = lung)
# Modify plot legend title
ggsurv$plot <- ggsurv$plot + 
  theme(legend.title = element_text(face = "bold"))
# Print
ggsurv
```

![Rplot](https://user-images.githubusercontent.com/3313355/63151829-aca1c680-c00a-11e9-85b5-7fa60ee8797a.jpeg)

**Comment by eaperkowski** [comment]
This is super helpful, thank you very much!

**Comment by kassambara** [comment]
so we can close this issue

**Comment by eaperkowski** [comment]
Indeed
