### ISSUE TITLE
Still error in ggsurvplot

### ISSUE THREAD

**Issue by Surdaster** [kassambara/survminer#426]
Sorry, I am new with github and don't know if this post is properly written...

I am running the following code :

library(survival)
library(survminer)
library(dplyr)

data(ovarian)

ovarian$rx <- factor(ovarian$rx, 
                     levels = c("1", "2"), 
                     labels = c("A", "B"))
ovarian$resid.ds <- factor(ovarian$resid.ds, 
                           levels = c("1", "2"), 
                           labels = c("no", "yes"))
ovarian$ecog.ps <- factor(ovarian$ecog.ps, 
                          levels = c("1", "2"), 
                          labels = c("good", "bad"))

ovarian <- ovarian %>% mutate(age_group = ifelse(age >=50, "old", "young"))
ovarian$age_group <- factor(ovarian$age_group)

surv_object <- Surv(time = ovarian$futime, event = ovarian$fustat)
fit1 <- survfit(surv_object ~ rx, data = ovarian)

ggsurvplot(fit1, data = ovarian, pval = TRUE)

Then I get the following message:

Error in ggsurvplot(fit1, data = ovarian, pval = TRUE) : 
  unused arguments (data = ovarian, pval = TRUE)

What does it mean, please?

**Comment by kassambara** [comment]
This error is not reproducible with the latest version of survminer
