### ISSUE TITLE
installation of package ‘data.table’ had non-zero exit status

### ISSUE THREAD

**Issue by AyobamiA** [kassambara/survminer#429]
**### Expected behavior** 
Hi I am having issues loading the survminer package. I initially had success but uploaded software to R3.6.1 because ggsurvplot was not working, and now I cannot even install survminer. I tried multiple options th

**code**: 

> if(!require(devtools)) install.packages("devtools")
Loading required package: devtools
Loading required package: usethis

> devtools::install_github("kassambara/survminer", build_vignettes = FALSE)

**### Actual behavior**
Downloading GitHub repo kassambara/survminer@master
Installing 1 packages: data.table

  There is a binary version available but the source version is later:
           binary source needs_compilation
data.table 1.12.2 1.12.4              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) ```
Error: Failed to install 'survminer' from GitHub:
  Unrecognized response “```”
> 
**### Steps to reproduce the problem**
My R version is 3.6.1; Rstudio: Version 1.2.5001

**if(!require(devtools)) install.packages("devtools")**
**devtools::install_github("kassambara/survminer", build_vignettes = FALSE)**

### `session_info()`
This is the end part of the error message
* installing *source* package ‘data.table’ ...
** package ‘data.table’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘data.table’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/data.table’
Error: Failed to install 'survminer' from GitHub:
  (converted from warning) installation of package ‘data.table’ had non-zero exit status

**Comment by kassambara** [comment]
Please try to install `data.table`  and then survminer

**Comment by AyobamiA** [comment]
Thanks for your prompt response. Sorry, I forgot to mention I did that as well before. I tried it again but got the message below:

> install.packages ("data.table")
--- Please select a CRAN mirror for use in this session ---

  There is a binary version available but the source version is later:
           binary source needs_compilation
data.table 1.12.2 1.12.4              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) yes
installing the source package ‘data.table’

trying URL 'https://cran.mtu.edu/src/contrib/data.table_1.12.4.tar.gz'
Content type 'application/x-gzip' length 5010321 bytes (4.8 MB)
==================================================
downloaded 4.8 MB

* installing *source* package ‘data.table’ ...
** package ‘data.table’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘data.table’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/data.table’

The downloaded source packages are in
	‘/private/var/folders/7q/rsmnjx0d0dvfkr_7kjhqwv640000gn/T/RtmpWmgQZj/downloaded_packages’
Warning message:
In install.packages("data.table") :
  installation of package ‘data.table’ had non-zero exit status

**Comment by kassambara** [comment]
There might be something wrong with your R installation.

I'm pretty sure this indicates your using a mac, and need to install xcode. [Here are step by step instructions](https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a)

**Comment by AyobamiA** [comment]
Yes! It worked! Thank you!
