### ISSUE TITLE
error in documentation

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [kassambara/survminer#43]
Hi! First, congrats for the amazing package! I have found a small error in the documentation:

# Change color, linetype by strata, risk.table color by strata
ggsurvplot(fit,
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          **lienetype** = "strata", # Change line type by groups _(should be linetype, I think)_
          ggtheme = theme_bw(), # Change ggplot2 theme
          palette = c("#E7B800", "#2E9FDF"))

**Comment by kassambara** [comment]
Thanks @ViniciusBRodrigues!!! Bug fixed now!

Best,
A.
