### ISSUE TITLE
unable to install survminer

### ISSUE THREAD

**Issue by ldybug** [kassambara/survminer#438]
Hi Kassambara,

Please help. Like many others I'm unable to install survminer...although i was able to install "survival".
I've tried some of the steps you've recommended to other users, but still unable to install it...
I've tried:
remove.packages(c("ggplot2", "gtable"))
install.packages("ggplot2", dependencies = TRUE)
library("ggplot2")
install.packages("gtable", type="win.binary") 
library("gtable")
if(!require(devtools)) install.packages("devtools")
devtools::instal_github("kassambara/survminer")
devtools::install_github("kassambara/survminer", build_vignettes = FALSE)

Thank you in advance for any possible help.

**Comment by kassambara** [comment]
please report the error message, thanks
