### ISSUE TITLE
Error in ggsurvplot(fit, data = desmoplakin) : object 'ggsurv' not found

### ISSUE THREAD

**Issue by ETHoorntje** [kassambara/survminer#440]
### Expected behavior 
I am learning to do the Cox regression analysis via http://www.sthda.com/english/wiki/cox-proportional-hazards-model. I am using R version 3.6.2 and installed all the requiered packages.

The script I have been using
# load packages
library("survival")
library("survminer")

# import database CSV
data("lung")
head(lung)

fit <- coxph(Surv(time, status) ~ sex, data = lung)

ggsurvplot(fit, data = lung)

### Actual behavior
> # import database CSV
> data("lung")
> head(lung)
  inst time status age sex ph.ecog ph.karno pat.karno meal.cal wt.loss
1    3  306      2  74   1       1       90       100     1175      NA
2    3  455      2  68   1       0       90        90     1225      15
3    3 1010      1  56   1       0       90        90       NA      15
4    5  210      2  57   1       1       90        60     1150      11
5    1  883      2  60   1       0      100        90       NA       0
6   12 1022      1  74   1       1       50        80      513       0
> fit <- coxph(Surv(time, status) ~ sex, data = lung)
> ggsurvplot(fit, data = lung)
Error in ggsurvplot(fit, data = lung) : object 'ggsurv' not found

### `session_info()`

````{R}
# please paste here the result of
devtools::session_info()
````
Am I missing some steps?

**Comment by kassambara** [comment]
You need to follow these steps

1. Compute cox
2. Fit survival curves based on the cox result
3. Plot the survival curves

This should work:

```r
library(survival)
data("lung")
res.cox <- coxph(Surv(time, status) ~ sex, data = lung)
ggsurvplot(survfit(res.cox), data = lung)
```

See also the function `survminer::ggadjustedcurves()`

**Comment by BEFH** [comment]
I'm getting this same error.

**Comment by ggruenhagen3** [comment]
I had the same problems as above. I found the solution in this thread https://github.com/kassambara/survminer/issues/283

This should work:
```
library(survival)
library(survminer)
data("lung")
res.cox <- coxph(Surv(time, status) ~ sex, data = lung)
ggsurvplot(surv_fit(res.cox, data = lung), data = lung)
```

**Comment by kassambara** [comment]
This error is not reproducible on my computer

**Comment by javifar** [comment]
I am getting the same error

**Comment by plbaldoni** [comment]
Same for me
