### ISSUE TITLE
Risk table do not align properly with axes.offset=F

### ISSUE THREAD

**Issue by tiger-liang** [kassambara/survminer#457]
```
ggsurv <- ggsurvplot(
  fit, 
  data = lung, 
  pval = F, 
  risk.table = T,
  xlim = c(0,1050),
  axes.offset = F,
  ggtheme = theme_bw(),
  risk.table.y.text.col = F, 
  risk.table.y.text = T,
  tables.y.text =F)

ggsurv 


```
the first coloum number (138 & 90) do not align with the x axis .
![图片](https://user-images.githubusercontent.com/23011191/77046520-1699a880-69fe-11ea-8c6e-c341cca293be.png)

_Originally posted by @tiger-liang in https://github.com/kassambara/survminer/issues/448#issuecomment-601050977_

**Comment by kassambara** [comment]
duplicates of #488
