### ISSUE TITLE
Different P value in surv_pvalue

### ISSUE THREAD

**Issue by zhangwl** [kassambara/survminer#458]
#############problem

The P value of surv_pvalue(fit) and surv_pvalue(fit,myeloma) is different in the following example. P value of surv_pvalue(fit) is 1.094804e-05, and surv_pvalue(fit,myeloma) is 1.497306e-113. But their statistic method are the same (Log-rank). What are the difference between the two P value. It is confusing to chose the result. Thank you!

###############code
library("survminer")
library("survival")

res.cut <- surv_cutpoint(myeloma, time = "time", event = "event",
                         variables = c("DEPDC1"))
res.cat <- surv_categorize(res.cut)
fit <- survfit(Surv(time, event) ~DEPDC1, data = res.cat)

surv_pvalue(fit)
surv_pvalue(fit, myeloma)

##################result
> surv_pvalue(fit)
  variable         pval   method   pval.txt
1   DEPDC1 1.094804e-05 Log-rank p < 0.0001
> surv_pvalue(fit,myeloma)
  variable          pval   method   pval.txt
1   DEPDC1 1.497306e-113 Log-rank p < 0.0001

**Comment by kassambara** [comment]
You are giving the wrong data to the function `surv_pvalue()`. You should use `surv_pvalue(fit,  data = res.cat)` instead of `surv_pvalue(fit,  data = myeloma)`
