### ISSUE TITLE
[User Request] - "+" sign / adjust the number of legends

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#46]
I had some time to try it out, and it works perfect.

 

However, I would encourage you to make two other adjustments/possibilities.

 

1.       You should be able to remove the “+” sign that indicate censored data, both

a.       from the end of the curve (in case of no censored data), and

b.      from the legends.

2.       You should be able to adjust the number of legends, independent of the number of curves. This means you can have 6 curves (2 groups of 3 replicates (replicates with the same linetype)) and 2 legends that show the 2 groups. If I try this now,  I get:

 

        Error in .check_legend_labs(fit, legend.labs) : 

         The length of legend.labs must should be 6

 

 

Cheers

 

Nikolaj

**Comment by MarcinKosinski** [comment]
Sorry,

 

censor = FALSE

 

takes care of the censor issue. I have difficulties finding all the possible arguments available.

**Comment by MarcinKosinski** [comment]
@kassambara I don't know wheter you have added Email notifications for this repository so I am mentioning you in the issue.

**Comment by kassambara** [comment]
I'll work on that but I'm not sure that this is feasible in ggplot2. Changing the number of the items in the legends independently of the plots....

**Comment by MarcinKosinski** [comment]
Is this the moment we start Mining stackoverflow for golden-ggplot2-unexpected-by-anyone-tricks :)?

**Comment by ngandersen** [comment]
Would it be possible to make an argument/link to the number of linetypes? So if you have 2 linetypes = 2 legends, 3 linetypes = 3 legends etc.

**Comment by MarcinKosinski** [comment]
How do you think @kassambara ?

**Comment by kassambara** [comment]
Hi @MarcinKosinski ,

Linetypes can now be adjusted in ggsurvplot(). For example:  

```r
# Fit survival curves
require("survival")
fit <- survfit( Surv(time, status) ~ rx + adhere,
                data = colon )
# Visualize:
# Change color by "strata" and adjust linetype by "adhere" variable
require("survminer")
ggsurvplot(fit, color = "strata", linetype = "adhere", legend = "right")
```

![rplot07](https://cloud.githubusercontent.com/assets/3313355/19487340/b2f780f4-9562-11e6-8ace-9e70f7de4b56.png)

If it's OK, we can close this issue:-)!

**Comment by ngandersen** [comment]
It's OK with me. Thank you very much!

Nikolaj

**Comment by MarcinKosinski** [comment]
Nice, this is extremely useful :)
