### ISSUE TITLE
Email notifications for contributors

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#47]
Could you be so kind and create e-mail notification for this repository?
Settings -> Webhooks & services -> Add Service -> Email -> and paste0 mine gmail address? 

I strongly advice you to add your e-mail address also and create a filter for GitHub notifications on your e-mail-box.

**Comment by MarcinKosinski** [comment]
@kassambara

**Comment by kassambara** [comment]
Didn't know this option! Should work now:-)!
