### ISSUE TITLE
 Can't pass data to ggsurvplot within function call #342 

### ISSUE THREAD

**Issue by Noitamir** [kassambara/survminer#475]
Hello, 

I have an issue about ggsurvplot included in a loop. As my dataframe change with the loop i can't fix it and ggsurvplot doesn't work. 
Without the loop ggsurvplot in perfectly working. 
Can you help me ? 
Here is my script : 

i<-1 
while (i<=5){for (i in 1:5) { # I want evalueted only the 5 first variable
  DC13 <- DC12 [,c(6:10,i)] # my dataframe is changing with the loop
  V5 = survfit (Surv( Followup, Statut)~ Variable, data = DC13)
  ggsurvplot( V5, data = DC13) 
} 
  i<-i+1 
}

**Comment by kassambara** [comment]
Did you obtain any error with this loop? If yes, please provide it

Also, please consider using print(ggsurvplot(v5, data = DC13))  in the loop, if you have a plot printing issue

**Comment by Noitamir** [comment]
Ah bon bah mon post était un peu bête, il suffisait de faire print ... merci beaucoup!! Moi qui cherchais des problèmes d'environnement ... !
