### ISSUE TITLE
ver 0.2.2

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#48]
This better should be a Milestone instead of an Issue but I have no collaborator rights at this repository.
Are we planning to submit survminer ver 0.2.2 before useR2016? Should we also update staticdocs? http://www.sthda.com/english/rpkgs/survminer/

**Comment by MarcinKosinski** [comment]
@kassambara

**Comment by kassambara** [comment]
staticdocs is now updated: http://www.sthda.com/english/rpkgs/survminer/

**Comment by MarcinKosinski** [comment]
Great, we can close the issue after submision to CRAN
https://cran.r-project.org/web/packages/survminer/index.html

**Comment by MarcinKosinski** [comment]
Have you considered uploading this on CRAN? I am planning another blog post about new functions in survminer where I would create flexdashboard with full cox ph analysis with diagnostic plots from survminer :)

**Comment by kassambara** [comment]
Hi Marcin,

I'm trying to do some checks before submitting v0.2.2.
 
I received the following message, after using `devtools::build_win()`, mentioning 2 errors:

```
Dear package maintainer,

this notification has been generated automatically.
Your package survminer_0.2.2.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
http://win-builder.r-project.org/7eGnVpf7iT51
The files will be removed after roughly 72 hours.
Installation time in seconds: 11
Check time in seconds: 143
Status: 2 ERRORs, 1 WARNING, 3 NOTEs
R version 3.3.1 (2016-06-21)

All the best,
Uwe Ligges
(CRAN maintainer of binary packages for Windows)
```

Please check the log file at http://win-builder.r-project.org/7eGnVpf7iT51. The errors concerns particularly the example section of the function 'ggcoxdiagnostics()' as well as the vignette file (Informative_Survival_Plots.Rmd).

Question: Should we change the examples in these files to fix CRAN check errors?

For the function 'ggcoxdiagnostics()', we can use the function \donttest{} around the example section to avoid CRAN check.

Do you have any suggestion for the vignette file?

Best,
A.

**Comment by MarcinKosinski** [comment]
I have seen such a topic on stackoverflow where one solution is to
http://stackoverflow.com/a/38577486/3857701
http://stackoverflow.com/questions/14343817/cran-package-depends-on-bioconductor-package-installing-error
add

This is not documented anywhere but the trick is that you add a line that
says biocViews: in your DESCRIPTION file (yes, it ends with a colon and
then no need to list anything, you can keep it blank). Then R will know to
check bioconductor repositories for the package requirements.

So I'll maybe add this to DESCRIPTION and you can configure AppVeyor (
https://ci.appveyor.com/projects/new) for windows checks (this is travis
for windows ) to let us know if checks passes on windows?

2016-07-27 14:37 GMT+02:00 Alboukadel KASSAMBARA <notifications@github.com>:

**Comment by kassambara** [comment]
adding `biocViews: ` in DESCRIPTION file doesn't seem to work (http://win-builder.r-project.org/hh21OsuUs8D4)

**Comment by MarcinKosinski** [comment]
That's weird. I have added AppVeyor to my fork and it lists that cran-check checks for bioconductor package https://ci.appveyor.com/project/MarcinKosinski/survminer/build/1.0.2#L133 but I also receive a message that RTCGA.clinical can not be found, because was not installed.

Why this fails only for windows? Maybe we should contact cran-windows maintainers direclty? It has passed for Linux and Mac OS.

**Comment by kassambara** [comment]
mail sent:-)!

**Comment by kassambara** [comment]
The answer from Uwe Ligges:


On 27.07.2016 17:17, Alboukadel Kassambara wrote:
Dear Uwe Ligges,

Before submitting the update version (v0.2.2) of survminer, I did a
check on win-bulder that generated the following error:

"there is no package called 'RTCGA.clinical". (RTCGA.clinical is a bioconductor package.)

I'm wondering, why the check fails only for windows? It has passed for
Linux (Travis) and Mac OSX (local). Do you have any suggestion to fix
this error?

```
It is just not installed on winbuilder.
I will do that once you submit the new version, please write it in the sumission comments.

Anyway, you should also change inn your package that the checks do not require a suggested package: Please run code that requires the package only conditionally on its availability.

Best,
Uwe Ligges
```

**Comment by MarcinKosinski** [comment]
So it should normally pass, if she'll add a binary to winbuilder repository
:)
Thanks Alboukadel.

2016-07-28 7:43 GMT+02:00 Alboukadel KASSAMBARA <notifications@github.com>:

**Comment by kassambara** [comment]
v0.2.2 on CRAN now... Thanks!!
