### ISSUE TITLE
dotted tick labels in risk Table

### ISSUE THREAD

**Issue by LoSerigne** [kassambara/survminer#497]
### I have two survival curves in the same color however I used linetype (solid and dotted) to differentiate the curves. When 
y.text.col is FALSE, I got 2 solid tick labels. Would it be possible to specify linetype in order to have a dotted tick label to match the survival curves. 

### Example of my syntax is below
# Fit survival curves
#++++++++++++++++++++++++++++++++++++
require("survival")
fit<- survfit(Surv(time, status) ~ sex, data = lung)
          ggsurvplot(fit,
                    size=1.5, xlim=c(0,1000.5), ylim=c(0,1.04), data=lung,
                    palette=c('#0072B2','#0072B2'), linetype=c("solid","dotted"),
                    surv.scale = c("default", "percent")[2],
                    conf.int=FALSE, conf.int.style = "ribbon", 
                    break.time.by = 100, censor=FALSE,
                    xlab = "Follow-up time (days)", ylab = "Overal survival",
                    pval=FALSE,
                    surv.median.line = "hv",
                    risk.table=TRUE,
                    risk.table.height = 0.20,
                    surv.plot.height = 0.80,
                    ggtheme= theme_classic(), #theme_classic2(), 
                    legend.title = "Pathological responses", legend.labs = c("Male", "Female"),
                    risk.table.title = "Numbers at risk",
                    legend = c(0.8,0.9),
                    font.legend = c(20, "plain", "black"),
                    font.x = 16, font.y = 16,
                    risk.table.col="strata", 
                    risk.table.fontsize = 8,
                    risk.table.y.text.col = T,
                    risk.table.y.text = FALSE ) 

### `session_info()`
Session info -------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_Australia.1252      
 ctype    English_Australia.1252      
 tz       Australia/Sydney            
 date     2020-09-30

**Comment by kassambara** [comment]
You can try something like this:

``` r
suppressPackageStartupMessages(library(survminer))
suppressPackageStartupMessages(library("survival"))
fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurv <- ggsurvplot(fit,
           size=1.5, xlim=c(0,1000.5), ylim=c(0,1.04), data=lung,
           palette=c('#0072B2','#0072B2'), linetype=c("solid","dotted"),
           surv.scale = c("default", "percent")[2],
           conf.int=FALSE, conf.int.style = "ribbon",
           break.time.by = 100, censor=FALSE,
           xlab = "Follow-up time (days)", ylab = "Overal survival",
           pval=FALSE,
           surv.median.line = "hv",
           risk.table=TRUE,
           risk.table.height = 0.20,
           surv.plot.height = 0.80,
           ggtheme= theme_classic(), #theme_classic2(),
           legend.title = "Pathological responses", legend.labs = c("Male", "Female"),
           risk.table.title = "Numbers at risk",
           legend = c(0.8,0.9),
           font.legend = c(20, "plain", "black"),
           font.x = 16, font.y = 16,
           risk.table.col="strata",
           risk.table.fontsize = 8,
           risk.table.y.text.col = T,
           risk.table.y.text = F)
#> Warning: Vectorized input to `element_text()` is not officially supported.
#> Results may be unexpected or may change in future versions of ggplot2.


ggsurv$table <- ggsurv$table + scale_y_discrete(
  breaks = c("Female", "Male"), labels = c( "--", "\U2012" )
  )
#> Scale for 'y' is already present. Adding another scale for 'y', which will
#> replace the existing scale.

print(ggsurv, risk.table.height = 0.3)
```

![](https://i.imgur.com/jWREFVS.png)

<sup>Created on 2020-10-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by LoSerigne** [comment]
Many thanks Alboukadel,
This is great!
S
​​​​​


A/Prof Serigne Lo - PhD MSc MRes AStat
The University of Sydney,
Central Clinical School | Faculty of Medicine and Health
Faculty Member | Melanoma Institute Australia, MIA
Head | Research and Biostatistics Group, MIA

[https://www.melanoma.org.au/melanoma/assets/mialogo_2018.jpg]

<http://www.melanoma.org.au>The Poche Centre
40 Rocklands Road North Sydney NSW 2060

T + 61 2 9911 7338 F + 61 2 9954 9435 M 0421 244 806
www.melanoma.org.au<http://www.melanoma.org.au>

[https://www.melanoma.org.au/melanoma/assets/Zero%20Deaths%20Email%20signature%20update.png]

<https://donate.melanoma.org.au/%20>This message is intended for the addressee named and may contain confidential information.
If you are not the intended recipient, please destroy it and notify the sender.
