### ISSUE TITLE
Warning in surv_median: `select_()` is deprecated as of dplyr 0.7.0.

### ISSUE THREAD

**Issue by xinyihou** [kassambara/survminer#509]
When I use the function surv_median, I received the warning that `select_()` is deprecated as of dplyr 0.7.0. Please use `select()` instead.

Could you update the code to use select()? Thanks!

Reference: https://github.com/kassambara/survminer/blob/812537ad8e6437c3190b4236a1326f8991ef0ef3/R/surv_median.R#L62

**Comment by kassambara** [comment]
fixed in #579 and #665
