### ISSUE TITLE
Real faceting (like ggquickeda::geom_km) - is this possible?

### ISSUE THREAD

**Issue by Generalized** [kassambara/survminer#510]
Dear @kassambara @jennybc and other Authors of the SurvMiner.

I would like to ask, if there is any possibility to "chain" the function drawing the Kaplan-Meier curves to support facet_wrap or facet_grid in a more "natural" way?

Yes, I know that SurvMiner:
- returns an object, which stores relevant ggplot2 plots, that can be chained, e.g. to set the theme, play with axes, labels, and so on. I use it this way. But it doesn't work well with faceting.

- allows me to provide two categorical variables, by which the plot will be faceted. But not rarely I need to use more levels of faceting. Let me show you an example. I made the chart below using the **ggquickeda** package, which offers the geom_km(), geom_band() and geom_ticks(). These function support faceting naturally. Let me show you:

```
ggplot(data, aes(time = time, status = status, color=sex)) +
  facet_grid(TRT ~ RNR + N2O) +
  geom_segment(data=median_st, aes(x=0, xend=median, y=0.5, yend=0.5), linetype="dashed", size=1.05, color="gray") +
  geom_segment(data=median_st, aes(x=median, xend=median, y=0, yend=0.5), linetype="dashed", size=1.05, color="gray") +
  geom_km()+
  geom_kmticks()+
  theme_bw() +
  theme(legend.position = "top") +
  geom_text(data=MST, aes(x=5, y=0.07*grY, label=MST), hjust = 0, size=3.5, show.legend = FALSE) +
  geom_text(data=MST, aes(x=5, y=(max(grY)+1)*0.07, label="MST:"), hjust = 0, size=3.5, show.legend = FALSE, color="darkgrey") +
  xlab("Time [months]") +
  ylab("Survival probability") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1))
```
(the data are fake, no secret stuff here)

Anticipating the question, yes, I do want the 3 levels to be used at the same time, drawing sepearate graphs is not an option for me and my Client.

I could stick to these functions, doing my work efficiently if only I didn't like so much the SurvMiner with all those functionality available onboard :) Especially, I like the table with the number of events, patients at risk, censored ones. Sure, I could reproduce it manually, but why to reinvent the wheel? Ideally, I would like to be allowed to not mix packages unnecessarily to accomplish a very common task (one package for faceting, another package for annotating)

Do you have any plans to enable this?
![obraz](https://user-images.githubusercontent.com/60151643/106654600-9ee25700-6598-11eb-86f5-a08653c90e1e.png)

---
OK, I can reproduce the output with ggsurvplot:

![obraz](https://user-images.githubusercontent.com/60151643/107003621-5fc92700-678d-11eb-8829-af8aa0768fd2.png)

**Comment by sebastian-gerdes** [comment]
Dear Generalized,

could you provide the code with which you could reproduce the plot using survminer? I am looking for something similar, but I don't know how to implement it with survminer!

This would be great - thanks a lot!

Best greetings,
Sebastian
