### ISSUE TITLE
Is it possible to change the spacing between legends?

### ISSUE THREAD

**Issue by ngandersen** [kassambara/survminer#52]
In a ggsurvplot the legends are very close together. There is almost no spacing between them. Is it possible to increase this spacing?

I tried to insert `legend.key.height` in the ggtheme `ggtheme = theme_light(legend.key.height=0.2)`

and this error comes up 

> Error in theme_light(legend.key.height = 0.2) : 
  unused argument (legend.key.height = 0.2) 

Is there a right way of increasing this space in a ggsurvplot?

Thanks

Nikolaj

**Comment by MarcinKosinski** [comment]
This error comes from `theme_light` function does not allow to pass different arguments than those passed below

- base_size = 12, 
- base_family = ""

````{R}
> theme_light
function (base_size = 12, base_family = "") 
{
    half_line <- base_size/2
    theme_grey(base_size = base_size, base_family = base_family) %+replace% 
        theme(axis.ticks = element_line(colour = "grey70", size = 0.25), 
            legend.key = element_rect(fill = "white", colour = "grey50", 
                size = 0.25), panel.background = element_rect(fill = "white", 
                colour = NA), panel.border = element_rect(fill = NA, 
                colour = "grey70", size = 0.5), panel.grid.major = element_line(colour = "grey85", 
                size = 0.25), panel.grid.minor = element_line(colour = "grey93", 
                size = 0.125), strip.background = element_rect(fill = "grey70", 
                colour = NA), strip.text.x = element_text(colour = "white", 
                margin = margin(t = half_line, b = half_line)), 
            strip.text.y = element_text(colour = "white", angle = -90, 
                margin = margin(l = half_line, r = half_line)))
}
````

Which legend do you mean? The one above survival curves or the one on the left of risk table set?

**Comment by ngandersen** [comment]
I mean the ones above the survival curves (the ones you can move around the plot with  e.g. "legend = c(0.161,0.28)").


Nikolaj


________________________________

**Comment by MarcinKosinski** [comment]
This can be done but not with `theme_light` function as this function not take such parameter.
Check this example below


````{R}
library(survminer)
require("survival")
fit<- survfit(Surv(time, status) ~ sex, data = lung)
library(RTCGA)
ggsurvplot(fit, main = "Survival curve",
   font.main = c(16, "bold", "darkblue"),
   font.x = c(14, "bold.italic", "red"),
   font.y = c(14, "bold.italic", "darkred"),
   font.tickslab = c(12, "plain", "darkgreen")) -> survplot

survplot$plot <- survplot$plot + theme(legend.key.height = unit(2.5, "cm"))
survplot
````

![unit](https://cloud.githubusercontent.com/assets/6773454/16011854/57d60360-3187-11e6-85de-7d080e525478.png)

**Comment by kassambara** [comment]
Please try the following R code:

- **Fit survival curves**

```r
library("survival")
fit <- survfit( Surv(time, status) ~ rx + adhere,
                 data = colon )
```

- **Default plot with survminer**

```r
library("survminer")
ggsurvplot(fit, risk.table = TRUE)
```
![rplot](https://cloud.githubusercontent.com/assets/3313355/16011763/05f2c146-3187-11e6-89af-96cbac90c055.png)

- **Change spacing between legends**

```r
ggsurv <- ggsurvplot(fit, risk.table = TRUE)
ggsurv$plot <- ggsurv$plot + theme(legend.key.height = unit(0.5, "line"))
```
![rplot14](https://cloud.githubusercontent.com/assets/3313355/16011817/327f869a-3187-11e6-8b66-f33c83c5759c.png)

**Comment by MarcinKosinski** [comment]
I think we can close this issue, if you have updated the NEWS with that feature :)
