### ISSUE TITLE
How to add custom annotation to ggsurvplot?

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#54]
I received the following message by email from a survminer user:

I would like to put into the plot some custom annotations (chi value), but by now i have not sorted out how to put a text in the plot.
May be you have a clue.

KS

**Comment by kassambara** [comment]
Hi,

Please try the following R script:

  
- Fit survival curves and differences

```r
library(survival)
# Survival curves
fit <- survfit(Surv(time, status) ~ sex, data = lung)

# Significance: Survival differences
surv_diff <- survdiff(Surv(time, status) ~ sex, data = lung)
surv_diff
```

```
Call:
survdiff(formula = Surv(time, status) ~ sex, data = lung)

        N Observed Expected (O-E)^2/E (O-E)^2/V
sex=1 138      112     91.6      4.55      10.3
sex=2  90       53     73.4      5.68      10.3

 Chisq= 10.3  on 1 degrees of freedom, p= 0.00131 
```

- Visualize with survminer

```r
library(survminer)
# Default plot
ggsurv <- ggsurvplot(fit, risk.table = TRUE)
ggsurv

```
![rplot](https://cloud.githubusercontent.com/assets/3313355/16911724/6f8c86d6-4ce0-11e6-9410-eb83a2b96077.png)


- Add a custom text annotation

```r
ggsurv$plot <- ggsurv$plot+ 
              ggplot2::annotate("text", 
                                x = 100, y = 0.2, # x and y coordinates of the text
                                label = "Chisq = 10.3, \n p < 0.001", size = 5)
ggsurv
```

![rplot16](https://cloud.githubusercontent.com/assets/3313355/16911746/904c298a-4ce0-11e6-9443-143a195578a1.png)


Best,

A.

**Comment by mharary** [comment]
When I try to do this,  I am getting the label duplicated - one in the proper spot on the survival graph, and another appears in the same coordinates in the risk table. Anyone know how to suppress the label in the risk table?
![image](https://user-images.githubusercontent.com/29471094/37479284-aaa14fdc-2852-11e8-8d67-903f0a3bcd07.png)

**Comment by jmuncu** [comment]
@mharary 
As kassambara  did, you should to add the annotate only into ggsurv$plot, not in all ggsurv.

**Comment by johannesbx** [comment]
Thank you for a realt great package! I struggle a bit annotating 2 panels of survival plots. I have used arrange_ggsurvplots() to combine them. Using the approach described above, the annotation is confined within the axis-limits. I ended up using caption, but was unable to position this below the risk table. I used ggpar() in addition  to ggsurv() create the plot.

**Comment by koho0127** [comment]
Can I edit p value in italic font? 
Just 'p'
