### ISSUE TITLE
update README: p-value + xlim

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#6]
One could add an example on how the `xlim` is working now, and add proper plots (last 3) with the new p-value form.

**Comment by kassambara** [comment]
README.md has been updated to reflect the latest version of the survminer

**Comment by MarcinKosinski** [comment]
Oh, I haven't noticed that you have `https://github.com/kassambara/survminer/blob/master/README.Rmd` . Other way I would propose you some changes myself.

**Comment by MarcinKosinski** [comment]
https://github.com/kassambara/survminer/issues/8#issuecomment-184348360
