### ISSUE TITLE
Vertical grid lines are not shown beyond data limit

### ISSUE THREAD

**Issue by ngandersen** [kassambara/survminer#60]
Hi 

When I make a plot with ggsurvplot and use a ggtheme with grid lines, the vertical grid lines stops at the x axis where the data stops, and are not displayed to the end of the x axis. The vertical grid lines thereby only cover half of the plotting area. Any suggestions to make them cover the whole graph?

There is no problem if I dont specify the xlim parameter, only if I extent the x-axis beyond the limit for the data.

 `ggsurvplot (my_surv_kmest,
            size=0.3,
            main = NULL,
            conf.int = TRUE, 
            legend.title = "Text",
            censor= FALSE,
            surv.scale = "percent",
            break.time.by = 60,
            legend.labs = c("Text", "Text2"),
            linetype = c(1,2),
            legend = c(0.9,0.9), 
            palette = c(1,1), 
            ggtheme = theme_light(),
            ylab = "Survival",
            xlab = "Time (minutes)",
            xlim = c(0,720),
            font.x = 9,
            font.y = 9,
            font.legend = 6,
            font.tickslab = 8)`

Thanks

Nikolaj

**Comment by MarcinKosinski** [comment]
Hi Nikolaj, could you also please upload a plot that is the output and potentially the data source `my_surv_kmest` or any similiar dataset that is easy to obtain so we can reproduce this isse?

**Comment by ngandersen** [comment]
A simple dataset can show the problem

Time	Status	Treatment
1	1	1
2	1	2
3	1	1
4	1	2
5	1	1
6	0	2
7	0	1
8	0	2
9	0	1
10	0	2

![rplot](https://cloud.githubusercontent.com/assets/11414723/18310915/ab6fd7e0-7501-11e6-8191-238e757664f8.jpeg)

**Comment by ngandersen** [comment]
Here I set the xlim to 20, but can see that the x labels from 10 to 20 are also not shown.

**Comment by MarcinKosinski** [comment]
Are they really needed? when list time mark is 10, than what's the point of making x-lim to be 20 : ) ?

**Comment by kassambara** [comment]
I agree with @MarcinKosinski  and I'm wondering why one would like to expand x-limits?
 I updated ggsurvplot() to handle this situation..

If you still want to do expand xlim, please install the latest version of survminer as follow and try it again.
```
devtools::install_github("kassambara/survminer")
````

Please, let us know if it works for you so that we can close this issue.

Best regards,
A.

**Comment by ngandersen** [comment]
It now works perfectly, thanks.

Imagine you want to show the survival times of 3 populations. Each population is shown on its own graph in one figure; Figure 1a, b and c. If the survival time differs between the populations, then you set the xlim to the survival time of the population with the longest duration. Then you have a fast an intuitive overview of the survival times of each population. It is standard in scientific publishing (at least where I am publishing).

Thanks again :)

Nikolaj
