### ISSUE TITLE
Easy way of drawing a horizontal line at 50% survival?

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#61]
Question (by e-mail)  from a survminer user

**Comment by kassambara** [comment]
In the next version, we'll improve ggsurvplot() to add easily horizontal line at 50% survival.

The following R script should work....

```r
#++++++++++++++++++++++++++++++++++++
require("survival")
require("survminer")
fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurv <- ggsurvplot(fit,
              pval = TRUE, conf.int = TRUE,
              risk.table = TRUE, # Add risk table
              risk.table.col = "strata", # Change risk table color by groups
              ggtheme = theme_bw(), # Change ggplot2 theme
              palette = c("#E7B800", "#2E9FDF")
              )

# Drawing a horizontal line at 50% survival
surv_median <- as.vector(summary(fit)$table[, "median"])
df <- data.frame(x1 = surv_median, x2 = surv_median,
                 y1 = rep(0, length(surv_median)), y2 = rep(0.5, length(surv_median)))

ggsurv$plot <- ggsurv$plot + 
              geom_segment(aes(x = 0, y = 0.5, xend = max(surv_median), yend = 0.5),
                           linetype = "dashed", size = 0.5)+ # horizontal segment
              geom_segment(aes(x = x1, y = y1, xend = x2, yend = y2), data = df,
                               linetype = "dashed", size = 0.5) # vertical segments

print(ggsurv)
```
![rplot02](https://cloud.githubusercontent.com/assets/3313355/19357746/387674ea-9173-11e6-954e-862dcb0e20ca.png)

**Comment by kassambara** [comment]
New argument surv.median.line in `ggsurvplot()`: character vector for drawing a horizontal/vertical line at median (50%) survival. Allowed values include one of c("none", "hv", "h", "v"). v: vertical, h:horizontal.

```r
require("survival")
require("survminer")
fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurvplot(fit, conf.int = TRUE, surv.median.line = "hv")
```
![rplot14](https://cloud.githubusercontent.com/assets/3313355/19617856/d828dcf2-983b-11e6-9813-6047d25da332.png)

**Comment by m-macaskill** [comment]
👍Thanks for this wonderful package. 

Is there a way to control the thickness of the `surv.median.line` either when the graph is created or afterwards? Currently it seems to default to 0.5 and doesn't seem to be easily modifiable at the user end.
