### ISSUE TITLE
`gather_()` was deprecated in tidyr 1.2.0.

### ISSUE THREAD

**Issue by JingyiShi** [kassambara/survminer#614]
I'm using the ggcoxdiagnostics() function and getting the following warnings:

Warning message:
`gather_()` was deprecated in tidyr 1.2.0.
ℹ Please use `gather()` instead.
ℹ The deprecated feature was likely used in the survminer package.
  Please report the issue at <https://github.com/kassambara/survminer/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by kassambara** [comment]
fixed in #579 and #665
