### ISSUE TITLE
Please update reference to `gather_()`  in your code to `gather()` as the former was deprecated in tidyr 1.2.0

### ISSUE THREAD

**Issue by lgirola** [kassambara/survminer#618]
I just received the following message in running a Cox proportional hazards multivariate model (running `survival` and `survminer` packages), as shown in the image below:

![Image1](https://user-images.githubusercontent.com/84516599/227033727-2ea4b9c6-0af5-4da9-a6c3-f0315a135ed9.png)

**Comment by josemss** [comment]
geom_smooth() using formula = 'y ~ x'
Warning message:
gather_() was deprecated in tidyr 1.2.0.
ℹ Please use gather() instead.
ℹ The deprecated feature was likely used in the survminer package.
Please report the issue at https://github.com/kassambara/survminer/issues.
This warning is displayed once every 8 hours.
Call lifecycle::last_lifecycle_warnings() to see where this warning was generated.

**Comment by kassambara** [comment]
fixed in #579 and #665
