### ISSUE TITLE
How to facet ggsurvplot() output

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#64]
How to facet the output by strata or some combination of factors , for example sex ~ treatment,  like this: 

![facetted plot of km event curves](https://cloud.githubusercontent.com/assets/3313355/19416996/297f8190-93a1-11e6-84c8-93fa3e10393c.PNG)

**Comment by kassambara** [comment]
In the current version it's possible to facet by starta, as follow:  
  
    
    
```
require("survival")
library("survminer")
fit2 <- survfit( Surv(time, status) ~ rx, data = colon )
ggsurv <- ggsurvplot(fit2, conf.int = TRUE)
# Facet
ggsurv$plot + theme_bw()+facet_wrap(~strata)
```

![rplot](https://cloud.githubusercontent.com/assets/3313355/19417021/c88b977e-93a1-11e6-81d6-bb52a6b92c49.png)

We'll work on it to make faceting possible with a combination of factors.

**Comment by kassambara** [comment]
To make faceting possible with a combination of factors, we'll update survminer as follow:   
   
1. Add a new function **surv_summary()**:  Compared to the default summary() function, surv_summary(), will create a data frame containing a nice summary from survfit results. 

This (new) helper function will be used in ggsurvplot() to summarize survival curves.

In a situation, where survival curves have been fitted with one or more variables, surv_summary object contains **extra columns** representing the variables. 

An example might be:  
   
```r
# Fit survival curves
require("survival")
fit <- survfit(Surv(time, status) ~ rx + adhere, data = column)

# Summarize
res.sum <- surv_summary(fit)
head(res.sum)
```

<pre>
 time n.risk n.event n.censor      surv     std.err     upper     lower           strata  rx adhere
1   20    536       1        0 0.9981343 0.001867414 1.0000000 0.9944878 rx=Obs, adhere=0 Obs      0
2   43    535       1        0 0.9962687 0.002643394 1.0000000 0.9911204 rx=Obs, adhere=0 Obs      0
3   45    534       1        0 0.9944030 0.003240519 1.0000000 0.9881072 rx=Obs, adhere=0 Obs      0
4   59    533       1        0 0.9925373 0.003745345 0.9998501 0.9852780 rx=Obs, adhere=0 Obs      0
5   72    532       1        0 0.9906716 0.004191364 0.9988435 0.9825667 rx=Obs, adhere=0 Obs      0
6   77    531       1        0 0.9888060 0.004595738 0.9977529 0.9799393 rx=Obs, adhere=0 Obs      0
</pre>

**Note that, supplementary columns (rx, adhere) have been added.**


This makes it possible to facet the output of ggsurvplot by strata or by some combinations of factors.

An example might be:  
 
```r
# Facet by strata
ggsurv$plot + theme_bw()+facet_wrap(~strata)

# Facet by treatment rx
ggsurv$plot + theme_bw()+facet_wrap(~rx)
```

**Comment by bmackenz** [comment]
That sounds great Alboukadel! Thanks so much for your effort and generosity to implement this feature, further improving what is already a stellar package.

**Comment by kassambara** [comment]
Faceting should work now.

1. Install the latest version of survminer
 
```r
devtools::install_github("kassambara/survminer")
``` 

2. Try this:   
    
```r
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Facet ggsurvplot() output by
# a combination of factors
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

# Fit (complexe) survival curves
#++++++++++++++++++++++++++++++++++++
require("survival")
fit3 <- survfit( Surv(time, status) ~ sex + rx + adhere,
                data = colon )

# Visualize: plot survival curves by sex and facet by rx and adhere
#++++++++++++++++++++++++++++++++++++
ggsurv <- ggsurvplot(fit3, fun = "cumhaz", conf.int = TRUE)
ggsurv$plot +theme_bw() + facet_grid(rx ~ adhere)
```

It looks like this:  

![rplot](https://cloud.githubusercontent.com/assets/3313355/19473377/aa3243fa-952b-11e6-9bf9-92fe5ded158b.png)

Best,
/A

**Comment by MarcinKosinski** [comment]
A magnificence masterpiece :O I'm amazed. Great that you are still working on `survminer` and providing such an informative messages during the issue's conversation.

**Comment by MarcinKosinski** [comment]
I am wondering how this can be displayed with risk tables? Do you think that 1 risk table under all plots is better than plotting as many risk tables as there are columns of graphs after faceting?

**Comment by kassambara** [comment]
Thank you Marcin, I appreciate your positive comment!!

I will work on that, it should be possible to suggest something about facet + risk tables!

**Comment by kassambara** [comment]
ggurvplot() returns a list of two different ggplots:
- plot: for survival curves
- table: for risk tables

It's now possible to apply facet to the two components plot and table. I think that, it's not possible to combine items of two different facets.

In trying to answer to your question,  survminer  now makes it possible to apply faceting as follow.

If it's ok, then we can close this issue:-)!
Best,
/A

- **Fit survival curves and use ggsurvplot()**
   

```r
# Fit (complexe) survival curves
#++++++++++++++++++++++++++++++++++++
require("survival")
fit <- survfit( Surv(time, status) ~ sex + rx + adhere,
                data = colon )

# Visualize
#++++++++++++++++++++++++++++++++++++
require("survminer")
ggsurv <- ggsurvplot(fit3, fun = "cumhaz", conf.int = TRUE,
  risk.table = TRUE, risk.table.col="strata",
  ggtheme = theme_bw())
```

- **Faceting survival curves**
    
```r
# Faceting survival curves
curv_facet <- ggsurv$plot + facet_grid(rx ~ adhere)
curv_facet
```

![rplot08](https://cloud.githubusercontent.com/assets/3313355/19549622/a2465d72-96a5-11e6-80e5-7f57e1738f81.png)

- **Faceting risk tables: Generate risk table for each facet plot item**

```r
# Faceting risk tables:
# Generate risk table for each facet plot item
ggsurv$table + facet_grid(rx ~ adhere, scales = "free")+
 theme(legend.position = "none")
```

![rplot10](https://cloud.githubusercontent.com/assets/3313355/19549685/f91ddc88-96a5-11e6-93eb-310904019ab7.png)
  


- **Generate risk table for each facet columns**

```r
 # Generate risk table for each facet columns
tbl_facet <- ggsurv$table + facet_grid(.~ adhere, scales = "free")
tbl_facet + theme(legend.position = "none")
```

![rplot09](https://cloud.githubusercontent.com/assets/3313355/19549690/012c03be-96a6-11e6-966e-27effa8af92b.png)

- **Arrange faceted survival curves and risk tables**

```r
# Arrange faceted survival curves and risk tables
g2 <- ggplotGrob(curv_facet)
g3 <- ggplotGrob(tbl_facet)
min_ncol <- min(ncol(g2), ncol(g3))
g <- gridExtra::rbind.gtable(g2[, 1:min_ncol], g3[, 1:min_ncol], size="last")
g$widths <- grid::unit.pmax(g2$widths, g3$widths)
grid::grid.newpage()
grid::grid.draw(g)
```

![rplot11](https://cloud.githubusercontent.com/assets/3313355/19549738/4e8d7836-96a6-11e6-89bc-f88cd7180972.png)

**Comment by kassambara** [comment]
To add risk table in each facet item, we should implement an option in the future to place the risk table inside the Kaplan-Meier curve, so that risk table can propagate with facet items.

**Comment by kassambara** [comment]
I think that it's not a good idea to place the risk table inside the KM curve, the final plot is unreadable. So we can close this issue.

**Comment by DanChaltiel** [comment]
I'm trying to reproduce this example, but using the code 

```
require("survival")
require("survminer")
fit3 <- survfit( Surv(time, status) ~ sex + rx + adhere, data = colon )
ggsurv <- ggsurvplot(fit3, fun = "cumhaz", conf.int = TRUE,
                     risk.table = TRUE, risk.table.col="strata",
                     ggtheme = theme_bw())
ggsurv$plot + facet_grid(rx ~ adhere)
```

throws this error:

> Error in f(...) : Aesthetics can not vary with a ribbon

I get the same message when trying on my own dataset.

Am I doing it wrong ?

**Comment by smouksassi** [comment]
try using strata sometimes the extraction of strata into column names can fail.
I also show how you can do something similar more flexible in geom_km ( it understands, grouping, color, fill etc) up to you to decide how to split the plot using ggplot synthax without a survfit object. ( no risk table and other advanced features) also up to you to ensure variables are factor or continous etc.

``` r
require("survival")
#> Loading required package: survival
require("survminer")
#> Loading required package: survminer
#> Loading required package: ggplot2
#> Loading required package: ggpubr
#> Loading required package: magrittr
require("ggquickeda")
#> Loading required package: ggquickeda
#> 
#> Attaching package: 'ggquickeda'
#> The following object is masked from 'package:base':
#> 
#>     +

fit3 <- survfit( Surv(time, status) ~ sex + rx + adhere, data = colon )
ggsurv <- ggsurvplot(fit3, fun = "cumhaz", conf.int = TRUE)$plot + facet_wrap(~ strata)

ggsurv
```

![](https://i.imgur.com/o00oZ7p.png)

``` r
ggplot(colon, aes(time = time, status = status)) +
         geom_km()+
  geom_kmband()+
  geom_kmticks()+
  facet_grid(~ sex + rx + adhere)
```

![](https://i.imgur.com/M0vbQaT.png)

``` r

ggplot(colon, aes(time = time, status = status,fill=sex,color=sex,group=sex)) +
  geom_km()+
  geom_kmband()+
  geom_kmticks()+
  facet_grid(rx ~ adhere)
```

![](https://i.imgur.com/eQJ0sWV.png)

<sup>Created on 2019-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by Ragg3d** [comment]
> try using strata sometimes the extraction of strata into column names can fail.
> I also show how you can do something similar more flexible in geom_km ( it understands, grouping, color, fill etc) up to you to decide how to split the plot using ggplot synthax without a survfit object. ( no risk table and other advanced features) also up to you to ensure variables are factor or continous etc.
> 
> ```r
> require("survival")
> #> Loading required package: survival
> require("survminer")
> #> Loading required package: survminer
> #> Loading required package: ggplot2
> #> Loading required package: ggpubr
> #> Loading required package: magrittr
> require("ggquickeda")
> #> Loading required package: ggquickeda
> #> 
> #> Attaching package: 'ggquickeda'
> #> The following object is masked from 'package:base':
> #> 
> #>     +
> 
> fit3 <- survfit( Surv(time, status) ~ sex + rx + adhere, data = colon )
> ggsurv <- ggsurvplot(fit3, fun = "cumhaz", conf.int = TRUE)$plot + facet_wrap(~ strata)
> 
> ggsurv
> ```
> 
> ![](https://camo.githubusercontent.com/fbe6e987f6b7f969c3f51be7154d4342813b2317/68747470733a2f2f692e696d6775722e636f6d2f6f30306f5a37702e706e67)
> 
> ```r
> ggplot(colon, aes(time = time, status = status)) +
>          geom_km()+
>   geom_kmband()+
>   geom_kmticks()+
>   facet_grid(~ sex + rx + adhere)
> ```
> 
> ![](https://camo.githubusercontent.com/85d976716a5f365e4eb00ed7ca9cd411ac78dd7f/68747470733a2f2f692e696d6775722e636f6d2f4d3076625161542e706e67)
> 
> ```r
> ggplot(colon, aes(time = time, status = status,fill=sex,color=sex,group=sex)) +
>   geom_km()+
>   geom_kmband()+
>   geom_kmticks()+
>   facet_grid(rx ~ adhere)
> ```
> 
> ![](https://camo.githubusercontent.com/a2cde4dfcd8becf9cdbd57293bb7d36004d2dce3/68747470733a2f2f692e696d6775722e636f6d2f65514a307357562e706e67)
> 
> Created on 2019-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

OMG this is definitely what I want! ggsurvplot() is great but it's still not the real "facet". Both are great anyway, thanks!
