### ISSUE TITLE
deprecated feature in survminer

### ISSUE THREAD

**Issue by annewinkelman** [kassambara/survminer#646]
### 
ggsurvplot_combine(fit, demo.data)
Warning message:
There was 1 warning in `mutate()`.
ℹ In argument: `survtable = purrr::map2(...)`.
Caused by warning:
! `select_()` was deprecated in dplyr 0.7.0.
ℹ Please use `select()` instead.
ℹ The deprecated feature was likely used in the survminer package.
  Please report the issue at <https://github.com/kassambara/survminer/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
> packageVersion(survminer)
Error in packageDescription(pkg, lib.loc = lib.loc, fields = "Version") : 
  object 'survminer' not found
> packageVersion("survminer")
[1] ‘0.4.9’

### `session_info()`

````{R}
# please paste here the result of
devtools::session_info()
 setting  value
 version  R version 4.1.0 (2021-05-18)
 os       Ubuntu 18.04.6 LTS
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  C.UTF-8
 ctype    C.UTF-8
 tz       Pacific/Auckland
 date     2024-03-13
 pandoc   3.1.2 @ /usr/bin/pandoc

**Comment by kassambara** [comment]
fixed in #579 and #665
