### ISSUE TITLE
`select_()` was deprecated in dplyr 0.7.0. error

### ISSUE THREAD

**Issue by gdebreczeni** [kassambara/survminer#652]
Warning message:

There was 1 warning in `mutate()`.
ℹ In argument: `survtable = purrr::map2(...)`.
Caused by warning:
! `select_()` was deprecated in dplyr 0.7.0.
ℹ Please use `select()` instead.
ℹ The deprecated feature was likely used in the survminer package.
  Please report the issue at <https://github.com/kassambara/survminer/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 

R>lifecycle::last_lifecycle_warnings()
list()

**Comment by mafed** [comment]
was about to post the same thing 😅

**Comment by trevorschrotz** [comment]
I was going to add an issue for the same select_() error, but I found that it has already been logged.  Thanks!

**Comment by dariotru** [comment]
Me too. thank you for updating.

**Comment by kassambara** [comment]
fixed in #579 and #665
