### ISSUE TITLE
Change font family and arrange multiple ggsurvplot on the same page

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#66]
Email from a survminer user:

Hello! 

I am trying to use the survminer package to show my data, and I found it very nice!!!

I just wanted to ask a couple of easy question, sorry if they are stupid, but I am not an expert R user:

1)Do you know if it is possible to edit the text's style (e.g. to times new roman)? 
2) is it possible to have multiple curves in the same page, in sequence, not on top of each other?

my code is for 3 survplots is:

all <- ggsurvplot(surv2,risk.table = FALSE,pval = FALSE,conf.int = TRUE,xlim = c(0,30),
        break.time.by = 10, risk.table.y.text = FALSE ,
        palette = c("#e71e00", "#0039e7"),legend = c("none"),
        xlab = "Days", ylab = "Survival probability",
        font.x = c(15, "plain", "black"), font.y = c(15, "plain", "black"), 
        font.tickslab = c(15, "plain", "black"))
fem <- ggsurvplot(survfe,risk.table = FALSE,pval = FALSE,conf.int = TRUE,xlim = c(0,30),
        break.time.by = 10, risk.table.y.text = FALSE ,
        palette = c("#e71e00", "#0039e7"),legend = c("none"),
        font.x = c(15, "plain", "black"), font.y = c(15, "plain", "black"), 
        font.tickslab = c(15, "plain", "black"))
mal <- ggsurvplot(survma,risk.table = FALSE,pval = FALSE,conf.int = TRUE,xlim = c(0,30),
         break.time.by = 10, risk.table.y.text = FALSE ,
         palette = c("#e71e00", "#0039e7"),legend = c("none"),
         font.x = c(15, "plain", "black"), font.y = c(15, "plain", "black"), 
         font.tickslab = c(15, "plain", "black"))

thanks for the help in advance
cheers
Luca

**Comment by kassambara** [comment]
Hi Luca,

Sorry for  the delay.

Please try the following script and let me know if it works:

```r
# Fit survival curves
library(survival)
library(survminer)
fit<- survfit(Surv(time, status) ~ sex, data = lung)

# 0) Default plot
ggsurvplot(fit, conf.int = TRUE)

# 1) Change font family
ggsurvplot(fit, conf.int = TRUE, ggtheme = theme_classic2(base_family = "Times New Roman"))

# 2) Multiple ggsurvplot in the same page
# Consider splots as a list of ggsurvplot objects.
splots = list()
splots[[1]] <- ggsurvplot(fit, conf.int = TRUE)
splots[[2]] <- ggsurvplot(fit, conf.int = TRUE, ggtheme = theme_bw())
splots[[3]] <- ggsurvplot(fit, conf.int = TRUE, ggtheme = theme_minimal())
splots[[4]] <- ggsurvplot(fit, conf.int = TRUE, ggtheme = theme_grey())
require(gridExtra)
do.call(marrangeGrob, list(grobs = lapply(splots, function(x) x$plot), ncol = 2, nrow = 2))
```

Have a great day,
/A

**Comment by lpfy** [comment]
Hi @kassambara ,

Above code works for combine multiple plots without risktable, just wondering how to include risk table as well?

Regards,
Sasha

**Comment by kassambara** [comment]
I'll work on that!

Best regards,
/Albou

**Comment by kassambara** [comment]
A quick fix to arrange and print multiple ggsurvplots on the same page:

```r
require("survival")
fit<- survfit(Surv(time, status) ~ sex, data = lung)


# List of ggsurvplot
require("survminer")
splots <- list()
splots[[1]] <- print(ggsurvplot(fit, data = lung, risk.table = TRUE, ggtheme = theme_minimal()))
splots[[2]] <- print(ggsurvplot(fit, data = lung, risk.table = TRUE, ggtheme = theme_grey()))

# Arrange multiple ggsurvplots
multiple_survs <- do.call(marrangeGrob, list(grobs = splots, ncol = 2, nrow = 1))

# Print the arranged plots
print(multiple_survs)

# Save the arranged plots into pdf
ggsave("multiple_survs.pdf", multiple_survs)
```

The output looks like this:

![capture d ecran 2017-02-14 a 14 17 43](https://cloud.githubusercontent.com/assets/3313355/22930429/6e3338b2-f2c0-11e6-9c9c-18bdcc3492a9.png)


I will create an easy to use function in the survminer package (suggestion: `arrange_ggsurvplot()` or `arrange_multiple_ggsurvplot()`)

**Comment by jiajiaybyb** [comment]
Do you by chance have a solution to make the right panel shows correct information in this case? Many thanks!

**Comment by woodie123456** [comment]
Can you add a function to change the order of picture? sometimes i just want to let the pictures display from left to right rather than  from top to bottom.
