### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by yourusern** [kassambara/survminer#661]
### Expected behavior 
no warning
### Actual behavior
`geom_smooth()` using formula = 'y ~ x'
Warnmeldung:
`gather_()` was deprecated in tidyr 1.2.0.
ℹ Please use `gather()` instead.
ℹ The deprecated feature was likely used in the survminer package.
  Please report the issue at <https://github.com/kassambara/survminer/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
### Steps to reproduce the problem
library(survival)
library(survminer)

vfit <- coxph(Surv(time,status) ~ trt + factor(celltype) + 
              karno + age, data=veteran, x=TRUE)

ggcoxdiagnostics(vfit, type = "schoenfeld")
### `session_info()`

````{R}
# please paste here the result of
devtools::session_info()
````

**Comment by kassambara** [comment]
fixed in #665 and #579
