### ISSUE TITLE
ggsurvplot: Displaying risk table as a percentage of individuals at risk

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#70]
(survminer user request by e-mail)

At the moment, Survminer displays the absolute number of individuals at risk.
Is there an option for presenting (as a complementary information) the percentage of individuals at risk?
If not, could you indicate me a possible way to estimate them and include them in the table?

**Comment by kassambara** [comment]
Now, allowed values for the argument risk.table, include:

- TRUE or FALSE specifying whether to show or not the risk table. Default is FALSE.
- "absolute" or "percentage": to show the absolute number or the percentage of subjects at risk by time, respectively.

Examples:

```r
# Fit survival curves and visualize
require("survival")
fit<- survfit(Surv(time, status) ~ sex, data = lung)

# Default plot
require("survminer")
ggsurvplot(fit, risk.table = TRUE)
```

![rplot12](https://cloud.githubusercontent.com/assets/3313355/19617404/eedf31be-982f-11e6-9f4e-1a7a3b00f0bf.png)

Risk table containing the percentage at risk:

```r
ggsurvplot(fit, risk.table ="percentage")
```

![rplot13](https://cloud.githubusercontent.com/assets/3313355/19617443/a7437b3e-9830-11e6-8ab3-2661d81e6a68.png)

**Comment by DeLaRiva** [comment]
Is it possible to show both, absolute and percentage?
