### ISSUE TITLE
ggplot2 2.2.0 and 'number at risk' table

### ISSUE THREAD

**Issue by cardiomoon** [kassambara/survminer#72]
I am using the upcoming version of ggplot2 2.1.0.9001. I am not able to add number at risk table.
Could you please fix it?

**Comment by kassambara** [comment]
Hi @cardiomoon,

This has been already fixed (https://github.com/kassambara/survminer/issues/68).

Please, install the latest version of survminer on GitHub:

```r
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/survminer", build_vignettes = FALSE)
```

Let me know if it works, so that we can close this issue.

Best,
A.

**Comment by cardiomoon** [comment]
Dear A KASSAMBARA,

it works !

Thank you very much.

Sincerely,

Keon Woong Moon

**Comment by kassambara** [comment]
Great!! so we can close the issue.

Have a great day,
A. Kassambara
