### ISSUE TITLE
Error in sort.list(y) : 'x' must be atomic for 'sort.list'

### ISSUE THREAD

**Issue by teigentler** [kassambara/survminer#73]
I recently updates to the current ggplot release (2.2.0) and installed the newest survminer from GitHub
Whereas the follow skript plot a correctly with survminer from CRAN, the development version fails with:

Error in sort.list(y) : 'x' must be atomic for 'sort.list'
Have you called 'sort' on a list?

I used the following script:

installed.packages("survminer")

library(survival)
library(survminer)

data(veteran)
s <- Surv(veteran$time,veteran$status)
fit <- survfit(s~veteran$trt)
survminer::ggsurvplot(fit)

if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/survminer", build_vignettes = FALSE)

data(veteran)
s <- Surv(veteran$time,veteran$status)
fit <- survfit(s~veteran$trt)
survminer::ggsurvplot(fit)

Any hint?

best wishes

Thomas

**Comment by kassambara** [comment]
Hi,

I will work on that! 

In the meantime, please, try the following R code, which should work

```r
library(survival)
data(veteran)
fit <- survfit(Surv(time, status)~trt, data = veteran)
survminer::ggsurvplot(fit, risk.table = TRUE)
```

Best regards,
AK

**Comment by kassambara** [comment]
Hi,

Now, the github version should handle survfit() results, in the situation where users use data$variable to compute survival curves.

If it's ok for you, then we can close the issue.

Thank you for pointing this out!!

Best,
A.

**Comment by teigentler** [comment]
The veteran sample works indeed, however I still have the same error in a larger example.

It looks like:

time_OS <- Surv(as.numeric(dataSet$timeOS)/DaysPerYear*12,!is.na(dataSet$TodDat))
time_OS.fit <- survfit(time_OS~as.factor(strata))
pl1 <- ggsurvplot(time_OS.fit, risk.table=FALSE,ggtheme = cowplot::theme_cowplot(),palette=mypal,color=mypal[1],risk.table.y.text = FALSE, break.time.by = 6,xlim=c(0,116), conf.int=FALSE, main="10Y Overall survival",pval=TRUE,legend.labs = c("small","intermediate","large"))
pl1

strata is a factor with 3 possible values

Hope this short copy of the script is sufficient for you to reproduce the problem.

**Comment by teigentler** [comment]
The workround with
time_OS.fit <- survfit(Surv(as.numeric(timeOS)/DaysPerYear*12,!is.na(TodDat))~strata, data = dataSet)
give this error message:
Error in `[.data.frame`(eval(fit$call$data), , variable) : 
  undefined columns selected

**Comment by kassambara** [comment]
Yeah, I can see.... Preparing/cleaning the data set inside the Surv() function are not supported by the current version of survminer. 

But, does the following code works?
   
   
```r
# Preparing/cleaning the data
dataSet$timeOS <- as.numeric(dataSet$timeOS)/DaysPerYear*12
dataSet <- dataSet[!is.na(dataSet$TodDat), ]
dataSet$strata <- as.factor(dataSet$strata)

# Fit survival curves
library(survival)
fit<- survfit(Surv(timeOS, TodDat) ~ strata, data = dataSet)

# Visualize
library("survminer")
pl1 <- ggsurvplot(time_OS.fit, pval = TRUE)
```

Best,
A

**Comment by teigentler** [comment]
This seems to work:

dataSet$tmp_timeOS <- as.numeric(dataSet$timeOS)/DaysPerYear*12
dataSet$tmp_status <- !is.na(dataSet$TodDat)
dataSet$tmp_strata <- as.factor(dataSet$Thickness)

fit<- survfit(Surv(tmp_timeOS, tmp_status) ~ tmp_strata, data = dataSet)
pl1 <- ggsurvplot(fit, pval = TRUE)
pl1

Best,
Thomas

**Comment by kassambara** [comment]
Great!

Have a good day,
A

**Comment by paulael** [comment]
Hi I'm using the following script:

library(agricolae)
str(SSNL1)
SSNL1$PLOT = factor(SSNL1$PLOT)

block<-c(rep("I",24),rep("II",24),rep("III",24),rep("IV",24),rep("V",24),rep("VI",24),rep("VII",24),rep("VIII",24),rep("IX",24),rep("X",24),rep("XI",24),rep("XII",24),rep("XIII",24),rep("XIV",24),rep("XV",24),rep("XVI",24),rep("XVII",24),rep("XVIII",24),rep("XIX",24))
model<-DAU.test(block,SSNL1[,3],SSNL1[,5],method = c("lsd","tukey"),alpha=0.05,group=TRUE,console=FALSE)


and it fails with:
Error in sort.list(y) : 'x' must be atomic for 'sort.list'
Have you called 'sort' on a list?

Kindly advice.

**Comment by kassambara** [comment]
Hi @paulael,

your issue is not related to survminer and I'm not familiar with the agricolae package. I'm sorry that I can't help.

**Comment by KohSoonho** [comment]
Hi, I'm using a follow script

# creating simulation data
control_mutant <- list(rate = 0.03, rep = 25, treat = "control", genotype = "mutant")
treat_mutant <- list(rate = 0.03 * 0.55, rep = 125, treat = "treat", genotype = "mutant")
control_wild <- list(rate = 0.03 * 0.2, rep = 125, treat = "control", genotype = "wild")
treat_wild <- list(rate = 0.03 * 0.55 * 0.2, rep = 25, treat = "treat", genotype = "wild")

lst <- list(control_mutant, treat_mutant, control_wild, treat_wild)

# set seed
set.seed(4321)

# make simulated df
simulated_df <- map(lst, ~ tibble(time = rexp(.$rep, rate = .$rate),  
                                  status = 1,                         # there is no censoring
                                  treat = .$treat, 
                                  genotype = .$genotype)) %>%   # making list of tibble
                  bind_rows()   # combine to one table

# plot K-M curve 
ggsurvplot(surv_fit(Surv(time, status) ~ treat, data = simulated_df))

and it's fail with
sort.list(y) でエラー: 'x' must be atomic for 'sort.list'
Have you called 'sort' on a list?

Can you advise me for this error?
