### ISSUE TITLE
can't plot variables specified in `var` argument in ggcoxzph

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#75]
User private e-mail

> Can you provide an example of how to use the var argument in ggcoxzph?  I only want to print a plot for specific variables.
 
> Thank you,
 
> Mason Burley

I'll answer in a second.

**Comment by MarcinKosinski** [comment]
Mason,

This will be possible after merging this pull request https://github.com/kassambara/survminer/pull/76


An example on how to use the var argument in ggcoxzph
================

``` r
library(survival)
fit <- coxph(Surv(futime, fustat) ~ age + ecog.ps + rx, data=ovarian)
cox.zph.fit <- cox.zph(fit)
library(survminer)
ggcoxzph(cox.zph.fit) 
```

![unnamed-chunk-1-1](https://cloud.githubusercontent.com/assets/6773454/20457132/e1178a02-ae84-11e6-98e8-67f5dec78c13.png)


``` r
# change the plots order
ggcoxzph(cox.zph.fit, var = c("ecog.ps", "rx", "age"))
```

![unnamed-chunk-1-2](https://cloud.githubusercontent.com/assets/6773454/20457133/e5e0a7a8-ae84-11e6-82df-005cc16431db.png)


``` r
# plot only specified vairables
ggcoxzph(cox.zph.fit, var = c("ecog.ps", "rx"))
```

![unnamed-chunk-1-3](https://cloud.githubusercontent.com/assets/6773454/20457134/e9d91ef8-ae84-11e6-8d2f-983ca50e0ae0.png)


Thanks for reporting this issue.
Till that time you can install `survminer` from my fork

```{r}
devtools::install_github('MarcinKosinski/survminer')
```

**Comment by kassambara** [comment]
pull request merged now:-)!

**Comment by MarcinKosinski** [comment]
> That works great now!  Thanks for responding so quickly
 
> Mason Burley
