### ISSUE TITLE
weird behavior of surv_categorize - too many columns in the output

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#78]
### Expected behavior

`surv_categorize` translates `surv_cutpoint` to a data frame with additional column that specifies the group

example

``` r
# 0. Load some data
library(survival)
library(survminer)
data(myeloma)
head(myeloma)
```

             molecular_group chr1q21_status treatment event  time   CCND1 CRIM1
    GSM50986      Cyclin D-1       3 copies       TT2     0 69.24  9908.4 420.9
    GSM50988      Cyclin D-2       2 copies       TT2     0 66.43 16698.8  52.0
    GSM50989           MMSET       2 copies       TT2     0 66.50   294.5 617.9
    GSM50990           MMSET       3 copies       TT2     1 42.67   241.9  11.9
    GSM50991             MAF           <NA>       TT2     0 65.00   472.6  38.8
    GSM50992    Hyperdiploid       2 copies       TT2     0 65.20   664.1  16.9
             DEPDC1    IRF4   TP53   WHSC1
    GSM50986  523.5 16156.5   10.0   261.9
    GSM50988   21.1 16946.2 1056.9   363.8
    GSM50989  192.9  8903.9 1762.8 10042.9
    GSM50990  184.7 11894.7  946.8  4931.0
    GSM50991  212.0  7563.1  361.4   165.0
    GSM50992  341.6 16023.4 2096.3   569.2

``` r
# 1. Determine the optimal cutpoint of variables
res.cut <- surv_cutpoint(myeloma, time = "time", event = "event",
   variables = c("DEPDC1", "WHSC1", "CRIM1"))

summary(res.cut)
```

           cutpoint statistic
    DEPDC1    279.8  4.275452
    WHSC1    3205.6  3.361330
    CRIM1      82.3  1.968317

``` r
#2. Categorize variables
res.cat <- surv_categorize(res.cut)
head(res.cat)
```

              time event DEPDC1 WHSC1 CRIM1
    GSM50986 69.24     0   high   low  high
    GSM50988 66.43     0    low   low   low
    GSM50989 66.50     0    low  high  high
    GSM50990 42.67     1    low  high   low
    GSM50991 65.00     0    low   low   low
    GSM50992 65.20     0   high   low   low

### Actual behavior

`surv_categorize` adds too many columns

### Steps to reproduce the problem

``` r
library(tidyverse) # pipes (%>%) and dplyr data munging
# installation
# source("https://bioconductor.org/biocLite.R")
# biocLite("RTCGA.clinical")
# biocLite("RTCGA.rnaseq")
library(RTCGA.clinical) # survival times
library(RTCGA.rnaseq) # genes' expression


survivalTCGA(BRCA.clinical, 
             HNSC.clinical) -> BRCA_HNSC.surv

expressionsTCGA(
   BRCA.rnaseq, HNSC.rnaseq,
   extract.cols = c("ABCD4|5826")) %>%
   rename(cohort = dataset,
          ABCD4 = `ABCD4|5826`) %>%
   filter(substr(bcr_patient_barcode, 14, 15) == "01") %>% 
   # only cancer samples
   mutate(bcr_patient_barcode = 
             substr(bcr_patient_barcode, 1, 12)) -> BRCA_HNSC.rnaseq

head(BRCA_HNSC.surv)
```

      times bcr_patient_barcode patient.vital_status
    1  3767        TCGA-3C-AAAU                    0
    2  3801        TCGA-3C-AALI                    0
    3  1228        TCGA-3C-AALJ                    0
    4  1217        TCGA-3C-AALK                    0
    5   158        TCGA-4H-AAAK                    0
    6  1477        TCGA-5L-AAT0                    0

``` r
head(BRCA_HNSC.rnaseq)
```

    # A tibble: 6 × 3
      bcr_patient_barcode      cohort    ABCD4
                    <chr>       <chr>    <dbl>
    1        TCGA-3C-AAAU BRCA.rnaseq 322.2560
    2        TCGA-3C-AALI BRCA.rnaseq 486.6775
    3        TCGA-3C-AALJ BRCA.rnaseq 308.2502
    4        TCGA-3C-AALK BRCA.rnaseq 589.1601
    5        TCGA-4H-AAAK BRCA.rnaseq 615.7447
    6        TCGA-5L-AAT0 BRCA.rnaseq 896.3191

``` r
BRCA_HNSC.surv %>%
   left_join(BRCA_HNSC.rnaseq,
             by = "bcr_patient_barcode") ->
   BRCA_HNSC.surv_rnaseq

head(BRCA_HNSC.surv_rnaseq)
```

      times bcr_patient_barcode patient.vital_status      cohort    ABCD4
    1  3767        TCGA-3C-AAAU                    0 BRCA.rnaseq 322.2560
    2  3801        TCGA-3C-AALI                    0 BRCA.rnaseq 486.6775
    3  1228        TCGA-3C-AALJ                    0 BRCA.rnaseq 308.2502
    4  1217        TCGA-3C-AALK                    0 BRCA.rnaseq 589.1601
    5   158        TCGA-4H-AAAK                    0 BRCA.rnaseq 615.7447
    6  1477        TCGA-5L-AAT0                    0 BRCA.rnaseq 896.3191

``` r
table(BRCA_HNSC.surv_rnaseq$cohort, useNA = "always")
```

    BRCA.rnaseq HNSC.rnaseq        <NA> 
           1093         519          13 

``` r
BRCA_HNSC.surv_rnaseq <- BRCA_HNSC.surv_rnaseq %>%
   filter(!is.na(cohort))

dim(BRCA_HNSC.surv_rnaseq)
```

    [1] 1612    5

``` r
head(BRCA_HNSC.surv_rnaseq)
```

      times bcr_patient_barcode patient.vital_status      cohort    ABCD4
    1  3767        TCGA-3C-AAAU                    0 BRCA.rnaseq 322.2560
    2  3801        TCGA-3C-AALI                    0 BRCA.rnaseq 486.6775
    3  1228        TCGA-3C-AALJ                    0 BRCA.rnaseq 308.2502
    4  1217        TCGA-3C-AALK                    0 BRCA.rnaseq 589.1601
    5   158        TCGA-4H-AAAK                    0 BRCA.rnaseq 615.7447
    6  1477        TCGA-5L-AAT0                    0 BRCA.rnaseq 896.3191

``` r
#devtools::install_github('kassambara/survminer')
library(survminer)

BRCA_HNSC.surv_rnaseq.cut <- surv_cutpoint(
   BRCA_HNSC.surv_rnaseq,
   time = "times",
   event = "patient.vital_status",
   variables = c("ABCD4")
)
summary(BRCA_HNSC.surv_rnaseq.cut)
```

          cutpoint statistic
    ABCD4 468.6417  1.944138

``` r
surv_categorize(BRCA_HNSC.surv_rnaseq.cut)
```

         time event ABCD4   NA  NA   NA   NA   NA   NA  NA  NA  NA   NA   NA   NA
    1    3767     0   low high low high high high high low low low high high high
    2    3801     0   low high low high high high high low low low high high high
    3    1228     0   low high low high high high high low low low high high high
    4    1217     0   low high low high high high high low low low high high high
    5     158     0   low high low high high high high low low low high high high
    6    1477     0   low high low high high high high low low low high high high
    7    1471     0   low high low high high high high low low low high high high
    8      12     0   low high low high high high high low low low high high high
    9     259     0   low high low high high high high low low low high high high
    10    437     0   low high low high high high high low low low high high high
and so on..............................................................................
     [ reached getOption("max.print") -- omitted 1551 rows ]
```


### `session_info()`

``` r
# please paste here the result of
devtools::session_info()
```

     setting  value                       
     version  R version 3.3.1 (2016-06-21)
     system   x86_64, linux-gnu           
     ui       X11                         
     language English                     
     collate  pl_PL.UTF-8                 
     tz       <NA>                        
     date     2016-11-21                  

     package        * version      date       source                               
     assertthat       0.1          2013-12-06 CRAN (R 3.3.1)                       
     chron            2.3-47       2015-06-24 CRAN (R 3.3.1)                       
     colorspace       1.2-7        2016-10-11 CRAN (R 3.3.1)                       
     data.table       1.9.6        2015-09-19 CRAN (R 3.3.1)                       
     DBI              0.5-1        2016-09-10 CRAN (R 3.3.1)                       
     devtools         1.12.0       2016-06-24 CRAN (R 3.3.1)                       
     digest           0.6.10       2016-08-02 CRAN (R 3.3.1)                       
     dplyr          * 0.5.0        2016-06-24 CRAN (R 3.3.1)                       
     evaluate         0.10         2016-10-11 cran (@0.10)                         
     exactRankTests   0.8-28       2015-02-20 cran (@0.8-28)                       
     ggplot2        * 2.2.0        2016-11-11 CRAN (R 3.3.1)                       
     ggthemes         3.2.0        2016-07-20 Github (jrnold/ggthemes@dbbd61e)     
     gridExtra        2.2.1        2016-02-29 CRAN (R 3.3.1)                       
     gtable           0.2.0        2016-02-26 CRAN (R 3.3.1)                       
     htmltools        0.3.5        2016-03-21 CRAN (R 3.3.1)                       
     httr             1.2.1        2016-07-03 CRAN (R 3.3.1)                       
     knitr          * 1.15         2016-11-09 CRAN (R 3.3.1)                       
     lattice          0.20-34      2016-09-06 CRAN (R 3.3.1)                       
     lazyeval         0.2.0        2016-06-12 CRAN (R 3.3.1)                       
     magrittr         1.5          2014-11-22 CRAN (R 3.3.1)                       
     Matrix           1.2-7.1      2016-09-01 CRAN (R 3.3.1)                       
     maxstat          0.7-24       2016-04-06 cran (@0.7-24)                       
     memoise          1.0.0        2016-01-29 CRAN (R 3.3.1)                       
     munsell          0.4.3        2016-02-13 CRAN (R 3.3.1)                       
     mvtnorm          1.0-5        2016-02-02 CRAN (R 3.3.1)                       
     plyr             1.8.4        2016-06-08 CRAN (R 3.3.1)                       
     purrr          * 0.2.2        2016-06-18 CRAN (R 3.3.1)                       
     R6               2.2.0        2016-10-05 CRAN (R 3.3.1)                       
     Rcpp             0.12.7       2016-09-05 cran (@0.12.7)                       
     readr          * 1.0.0        2016-08-03 CRAN (R 3.3.1)                       
     rmarkdown        1.1          2016-10-16 cran (@1.1)                          
     RTCGA          * 1.3.4        2016-09-29 Bioconductor (R 3.3.1)               
     RTCGA.clinical * 20151101.2.2 2016-08-30 Bioconductor (R 3.3.1)               
     RTCGA.rnaseq   * 20151101.2.2 2016-07-06 Bioconductor (R 3.3.1)               
     rvest            0.3.2        2016-06-17 CRAN (R 3.3.1)                       
     scales           0.4.1        2016-11-09 CRAN (R 3.3.1)                       
     stringi          1.1.2        2016-10-01 CRAN (R 3.3.1)                       
     stringr          1.1.0        2016-08-19 CRAN (R 3.3.1)                       
     survival       * 2.40-1       2016-10-30 CRAN (R 3.3.1)                       
     survminer      * 0.2.2.999    2016-11-21 Github (kassambara/survminer@f0efd0f)
     tibble         * 1.2          2016-08-26 CRAN (R 3.3.1)                       
     tidyr          * 0.6.0        2016-08-12 CRAN (R 3.3.1)                       
     tidyverse      * 1.0.0        2016-09-09 CRAN (R 3.3.1)                       
     viridis          0.3.4        2016-03-12 CRAN (R 3.3.1)                       
     withr            1.0.2        2016-06-20 CRAN (R 3.3.1)                       
     XML              3.98-1.4     2016-03-01 CRAN (R 3.3.1)                       
     xml2             1.0.0        2016-06-24 CRAN (R 3.3.1)                       
     yaml             2.1.13       2014-06-12 CRAN (R 3.3.1)

**Comment by kassambara** [comment]
surv_categorize() uses the `apply()` function to categorize each variable. 

Problem: apply() isn't a tidy function. It returns a data.frame when length(variables) >= 2 and a vector when length(variables) == 1. 

This issue has been fixed now.

Thanks

**Comment by MarcinKosinski** [comment]
Thanks.
