### ISSUE TITLE
`surv_categorize` output has not the same column names as the `surv_cutpoint` input

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#79]
Expeted behaviour
=================

`surv_categorize` output has the same column names as the `surv_cutpoint` input

Actual behaviour
================

`surv_categorize` output has not the same column names as the `surv_cutpoint` input. In my opinion this is confusing that always the time and event variable are renamed for `surv_categorize` - I suggest they remain the same as in the input data or the might be an optional `change.names = FALSE`.

``` r
library(survminer)
```

    ## Loading required package: ggplot2

``` r
# 0. Load some data
data(myeloma)
myeloma2 <- myeloma[, c("DEPDC1", "WHSC1", "CRIM1", "time", "event")]
myeloma2 <- setNames(myeloma2, c("DEPDC1", "WHSC1", "CRIM1", "timeASDF", "event1234"))
head(myeloma2)
```

    ##          DEPDC1   WHSC1 CRIM1 timeASDF event1234
    ## GSM50986  523.5   261.9 420.9    69.24         0
    ## GSM50988   21.1   363.8  52.0    66.43         0
    ## GSM50989  192.9 10042.9 617.9    66.50         0
    ## GSM50990  184.7  4931.0  11.9    42.67         1
    ## GSM50991  212.0   165.0  38.8    65.00         0
    ## GSM50992  341.6   569.2  16.9    65.20         0

``` r
# 1. Determine the optimal cutpoint of variables
res.cut <- surv_cutpoint(myeloma2, time = "timeASDF", event = "event1234",
   variables = c("DEPDC1", "WHSC1", "CRIM1"))

# 2. Categorize variables
res.cat <- surv_categorize(res.cut)
head(res.cat)
```

    ##           time event DEPDC1 WHSC1 CRIM1
    ## GSM50986 69.24     0   high   low  high
    ## GSM50988 66.43     0    low   low   low
    ## GSM50989 66.50     0    low  high  high
    ## GSM50990 42.67     1    low  high   low
    ## GSM50991 65.00     0    low   low   low
    ## GSM50992 65.20     0   high   low   low

Session info
============

``` r
devtools::session_info()


    ## Session info --------------------------------------------------------------

    ##  setting  value                       
    ##  version  R version 3.3.1 (2016-06-21)
    ##  system   x86_64, linux-gnu           
    ##  ui       X11                         
    ##  language English                     
    ##  collate  pl_PL.UTF-8                 
    ##  tz       <NA>                        
    ##  date     2016-11-21

    ## Packages ------------------------------------------------------------------

    ##  package        * version   date      
    ##  assertthat       0.1       2013-12-06
    ##  colorspace       1.2-7     2016-10-11
    ##  devtools         1.12.0    2016-06-24
    ##  digest           0.6.10    2016-08-02
    ##  evaluate         0.10      2016-10-11
    ##  exactRankTests   0.8-28    2015-02-20
    ##  ggplot2        * 2.2.0     2016-11-11
    ##  gtable           0.2.0     2016-02-26
    ##  htmltools        0.3.5     2016-03-21
    ##  knitr            1.15      2016-11-09
    ##  lattice          0.20-34   2016-09-06
    ##  lazyeval         0.2.0     2016-06-12
    ##  magrittr         1.5       2014-11-22
    ##  Matrix           1.2-7.1   2016-09-01
    ##  maxstat          0.7-24    2016-04-06
    ##  memoise          1.0.0     2016-01-29
    ##  munsell          0.4.3     2016-02-13
    ##  mvtnorm          1.0-5     2016-02-02
    ##  plyr             1.8.4     2016-06-08
    ##  Rcpp             0.12.7    2016-09-05
    ##  rmarkdown        1.1       2016-10-16
    ##  scales           0.4.1     2016-11-09
    ##  stringi          1.1.2     2016-10-01
    ##  stringr          1.1.0     2016-08-19
    ##  survival         2.40-1    2016-10-30
    ##  survminer      * 0.2.2.999 2016-11-21
    ##  tibble           1.2       2016-08-26
    ##  withr            1.0.2     2016-06-20
    ##  yaml             2.1.13    2014-06-12
    ##  source                               
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  cran (@0.10)                         
    ##  cran (@0.8-28)                       
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  cran (@0.7-24)                       
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  cran (@0.12.7)                       
    ##  cran (@1.1)                          
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  Github (kassambara/survminer@f0efd0f)
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)                       
    ##  CRAN (R 3.3.1)
```

**Comment by MarcinKosinski** [comment]
Thanks, good job : )
I have posted a new post about survminer yesterday about 1:00 pm CET http://r-addict.com/2016/11/21/Optimal-Cutpoint-maxstat.html but it didn't yet reach r-bloggersa

**Comment by kassambara** [comment]
Yeah, I read it yesterday and I really appreciate it!! I shared it on R users facebook group page...

**Comment by kassambara** [comment]
Link to the blog plost added in the Readme.Rmd file:-)!

**Comment by MarcinKosinski** [comment]
I was about to add this, after it reach R-bloggers :)
Once I thought the publication process on R-bloggers is automatical, but it
looks like it is done by hand and maybe this time there is longer queue for
posts.

I only regret I didn't write more about calculations of maxstats and it's
explanation

2016-11-22 22:09 GMT+01:00 Alboukadel KASSAMBARA <notifications@github.com>:

**Comment by MarcinKosinski** [comment]
Talking about R Users Group on facebook - you ment this group - https://www.facebook.com/groups/rusers/ ? It's a pitty that I am banned on this group :) 
Is Pearson Kassim your alter ego - https://www.facebook.com/groups/rusers/permalink/10154292058248740/ ?

**Comment by MarcinKosinski** [comment]
I am also reposting my posts in many other R groups
https://www.facebook.com/shares/view?id=1901335666756744&av=100004520681971

2016-11-22 22:14 GMT+01:00 Marcin Kosiński <m.p.kosinski@gmail.com>:

**Comment by kassambara** [comment]
Yeah, Pearson Kassim is my alter ego :-)! should update this...

**Comment by kassambara** [comment]
Hi @MarcinKosinski ,

In your blog post, you used the following R code to categorize the data:

```r
BRCA_HNSC.surv_rnaseq.cat <- BRCA_HNSC.surv_rnaseq %>%
   mutate(ABCD4_expr = ifelse(ABCD4 >= summary(BRCA_HNSC.surv_rnaseq.cut)[1,1], "high", "low"))
```

As the issue has been fixed now,  I would suggest to simplify the code using: 

```r
BRCA_HNSC.surv_rnaseq.cat <- surv_categorize(BRCA_HNSC.surv_rnaseq.cut) 
```

**Comment by MarcinKosinski** [comment]
Yes, now I can specify factor variable in `variables` in `surv_cutpoint` :)
Thanks.
This post somehow did not appear on R-bloggers. I will write to Tal Galili
about that : / maybe he will post this

2016-11-23 7:49 GMT+01:00 Alboukadel KASSAMBARA <notifications@github.com>:
