### ISSUE TITLE
risk.table.y.axis.text.col

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#8]
Haye you considered merging regular legend with the `y.axis.text` element on `risk.table` plot?
The the function call could like this:

````{R}
ggsurvplot(fit, pval = TRUE, conf.int = TRUE, risk.table.ticks.col = TRUE,
           risk.table = TRUE, legend = "none" )
````

And the legend would appear vertically instead of `y.axis.text` element on `risk.table` plot OR the `y.axis.text` element could be coloured to the corresponding strata values?

**Comment by kassambara** [comment]
Good idea!
New argument risk.table.ticks.col added: logical value. Default value is FALSE. If TRUE, risk table tick labels will be colored by strata.

**Comment by MarcinKosinski** [comment]
Looks great 

````{R}
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/survminer")
#++++++++++++++++++++++++++++++++++++
require("survival")
fit<- survfit(Surv(time, status) ~ sex, data = lung)
library("survminer")
# Drawing survival curves
ggsurvplot(fit)
ggsurvplot(fit, pval = TRUE, conf.int = TRUE, risk.table.ticks.col = TRUE,
           risk.table = TRUE, legend = "none" )

````

Thanks!

![risk_tbl_ticks_col](https://cloud.githubusercontent.com/assets/6773454/13057846/09696cdc-d41f-11e5-9661-8193d78d70a9.png)

**Comment by MarcinKosinski** [comment]
Maybe it's better to call this 'risk.table.text.col'? What do You think?

Marcin Kosinski

Dnia 15.02.2016 o godz. 19:56 Alboukadel KASSAMBARA <notifications@github.com> napisał(a):

**Comment by kassambara** [comment]
Which one is most explicit among these 3 options:

- risk.table.text.col?
- risk.table.ytext.col?
- risk.table.strata.col?

Thanks in advance!

**Comment by MarcinKosinski** [comment]
I would go `risk.table.y.text.col` as `y.text` is a ggplot object in
theme() ?
No problem, it is you who are doing a favour to me :)

2016-02-15 22:21 GMT+01:00 Alboukadel KASSAMBARA <notifications@github.com>:

**Comment by kassambara** [comment]
risk.table.y.text.col argument can be used now.

Thanks,
A. Kassambara
