### ISSUE TITLE
Can't pass categorical variable to surv_cutpoint

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#81]
Expected behaviour
=======================

``` r
library(survminer)
# 0. Load some data
data(myeloma)
myeloma2 <- myeloma[, c("DEPDC1", "WHSC1", "CRIM1", "time", "event", "treatment")]
head(myeloma2)

# 1. Determine the optimal cutpoint of variables
res.cut <- surv_cutpoint(myeloma2, time = "time", event = "event",
   variables = c("DEPDC1", "WHSC1", "CRIM1", "treatment"))

# 2. Categorize variables
res.cat <- surv_categorize(res.cut)
head(res.cat)
```

What do I have to do since it is impossible to pass categorical variable to surv\_cutpoint
==========================================================================================

``` r
library(survminer)
# 0. Load some data
data(myeloma)
myeloma2 <- myeloma[, c("DEPDC1", "WHSC1", "CRIM1", "time", "event", "treatment")]
head(myeloma2)
```

             DEPDC1   WHSC1 CRIM1  time event treatment
    GSM50986  523.5   261.9 420.9 69.24     0       TT2
    GSM50988   21.1   363.8  52.0 66.43     0       TT2
    GSM50989  192.9 10042.9 617.9 66.50     0       TT2
    GSM50990  184.7  4931.0  11.9 42.67     1       TT2
    GSM50991  212.0   165.0  38.8 65.00     0       TT2
    GSM50992  341.6   569.2  16.9 65.20     0       TT2

``` r
# 1. Determine the optimal cutpoint of variables
res.cut <- surv_cutpoint(myeloma2, time = "time", event = "event",
   variables = c("DEPDC1", "WHSC1", "CRIM1"))

# 2. Categorize variables
res.cat <- surv_categorize(res.cut)

##################################
res.cat <- cbind(res.cat, treatment = myeloma2$treatment)
##################################

head(res.cat)
```

              time event DEPDC1 WHSC1 CRIM1 treatment
    GSM50986 69.24     0   high   low  high       TT2
    GSM50988 66.43     0    low   low   low       TT2
    GSM50989 66.50     0    low  high  high       TT2
    GSM50990 42.67     1    low  high   low       TT2
    GSM50991 65.00     0    low   low   low       TT2
    GSM50992 65.20     0   high   low   low       TT2

Users might not trust that the output of `surv_categorize` has the same order as the input of `surv_cutpoint`. Do you think providing a functionality that allows to store categorical variables in surv\_cutpoint would be valuable?

Session info
============

``` r
devtools::session_info()
```

     setting  value                       
     version  R version 3.3.1 (2016-06-21)
     system   x86_64, linux-gnu           
     ui       X11                         
     language English                     
     collate  pl_PL.UTF-8                 
     tz       <NA>                        
     date     2016-11-21                  

     package        * version   date       source                               
     assertthat       0.1       2013-12-06 CRAN (R 3.3.1)                       
     colorspace       1.2-7     2016-10-11 CRAN (R 3.3.1)                       
     devtools         1.12.0    2016-06-24 CRAN (R 3.3.1)                       
     digest           0.6.10    2016-08-02 CRAN (R 3.3.1)                       
     evaluate         0.10      2016-10-11 cran (@0.10)                         
     exactRankTests   0.8-28    2015-02-20 cran (@0.8-28)                       
     ggplot2        * 2.2.0     2016-11-11 CRAN (R 3.3.1)                       
     gtable           0.2.0     2016-02-26 CRAN (R 3.3.1)                       
     htmltools        0.3.5     2016-03-21 CRAN (R 3.3.1)                       
     knitr          * 1.15      2016-11-09 CRAN (R 3.3.1)                       
     lattice          0.20-34   2016-09-06 CRAN (R 3.3.1)                       
     lazyeval         0.2.0     2016-06-12 CRAN (R 3.3.1)                       
     magrittr         1.5       2014-11-22 CRAN (R 3.3.1)                       
     Matrix           1.2-7.1   2016-09-01 CRAN (R 3.3.1)                       
     maxstat          0.7-24    2016-04-06 cran (@0.7-24)                       
     memoise          1.0.0     2016-01-29 CRAN (R 3.3.1)                       
     munsell          0.4.3     2016-02-13 CRAN (R 3.3.1)                       
     mvtnorm          1.0-5     2016-02-02 CRAN (R 3.3.1)                       
     plyr             1.8.4     2016-06-08 CRAN (R 3.3.1)                       
     Rcpp             0.12.7    2016-09-05 cran (@0.12.7)                       
     rmarkdown        1.1       2016-10-16 cran (@1.1)                          
     scales           0.4.1     2016-11-09 CRAN (R 3.3.1)                       
     stringi          1.1.2     2016-10-01 CRAN (R 3.3.1)                       
     stringr          1.1.0     2016-08-19 CRAN (R 3.3.1)                       
     survival         2.40-1    2016-10-30 CRAN (R 3.3.1)                       
     survminer      * 0.2.2.999 2016-11-21 Github (kassambara/survminer@f0efd0f)
     tibble           1.2       2016-08-26 CRAN (R 3.3.1)                       
     withr            1.0.2     2016-06-20 CRAN (R 3.3.1)                       
     yaml             2.1.13    2014-06-12 CRAN (R 3.3.1)

**Comment by kassambara** [comment]
should work now

**Comment by MarcinKosinski** [comment]
Thank you, great job :) Are you planning to release `survminer` ver 0.2.3?

**Comment by kassambara** [comment]
v0.2.3 should be on CRAN next week!!
