### ISSUE TITLE
P-values are not displayed properly when iterating over an Apply family loop

### ISSUE THREAD

**Issue by jacorvar** [kassambara/survminer#82]
When I iterate the function over a sapply loop, for instance, all plots show the same p-values (when plotting two curves on the same plot), which is wrong. A for-loop works though, but if I need to use the ggsurvplot many times it might be too slow.
Could anyone tell me please how to circumvent this?

Thanks a lot in advance

**Comment by kassambara** [comment]
Hi @jacorvar ,

As specified at  #58, using do.call() should fix this problem: 

```
library(survminer)
library(survival)
f1 <- Surv(futime, fustat) ~ resid.ds
f2 <- Surv(futime, fustat) ~ age
f <- list(f1, f2)

s <- lapply(f, function(x) do.call(survfit, list(formula = x, data = ovarian)))
lapply(s, function(x) do.call(ggsurvplot, list(fit = x, pval = TRUE)))
```

Does it work in your hand?

Best regards,
A.

**Comment by megha20** [comment]
How about legend.title? If I want to give different "legend title" or "main" to each ggsurvplot within lapply.
Can you use the above code to explain?

**Comment by kassambara** [comment]
Would you, please,  open a new issue concerning legend.title?
