### ISSUE TITLE
object of type 'closure' is not subsettable

### ISSUE THREAD

**Issue by GregorySchwartz** [kassambara/survminer#84]
Using the latest git version of this library, I receive the following error:

### Expected behavior 
Output plot.
### Actual behavior
Error in eval(fit$call$data)[, variable] :
  object of type 'closure' is not subsettable
### Steps to reproduce the problem
  library(survminer)

   args = commandArgs(trailingOnly = TRUE)

   env <- new.env()
   load(args[1], envir=env)
   fit <- env$fit
   print(summary(fit))

   p = ggsurvplot( fit
                 ## , risk.table = TRUE
                 ## , pval = TRUE
                 ## , conf.int = TRUE
                 ## , risk.table.y.text.col = T
                 ## , risk.table.y.text = FALSE
                 )

   saveFile = gsub(".RData", ".pdf", args[1])

   pdf(file = saveFile)
   print(p)
   dev.off()
### `session_info()`

R version 3.2.3

**Comment by kassambara** [comment]
Hi,

With R code you provided, It's not possible to reproduce the problem.
Can you please provide a reproducible R code?

Please try the R code below. It should work:

```
# Fit survival curves using lung data
require("survival")
fit<- survfit(Surv(time, status) ~ sex, data = lung)


library(survminer)
ggsurvplot( fit, risk.table = TRUE,
                pval = TRUE,
                conf.int = TRUE,
                risk.table.y.text.col = T
)
```
Best,
A.

**Comment by GregorySchwartz** [comment]
Yes, that does work for me. Is it my data? plot(fit) works and ggsurvplot(fit) from CRAN works, it's just the newest git version for me that doesn't...

**Comment by kassambara** [comment]
the git version should work also. Could you provide the R code you use to fit the survival curves?

**Comment by GregorySchwartz** [comment]
fit = survfit(Surv(time, event) ~ group, data = df)

I can't share the df, unfortunately.

**Comment by kassambara** [comment]
As illustrated with the demo data, it should work also with your data. It's difficult to help if the problem is not reproducible...

**Comment by GregorySchwartz** [comment]
It appears to be specific to my use case, so I'll close this issue unless it pops up in the above case.

**Comment by kassambara** [comment]
Ok, thanks!
