### ISSUE TITLE
Risk table not displayed

### ISSUE THREAD

**Issue by akhats** [kassambara/survminer#85]
Hi there,
I was trying to run the example givein by Marcin Kosiński. When I plot to data using 
`ggsurvplot(fit, risk.table = TRUE)`

 I always get this error:

**"Error in -x : invalid argument to unary operator
In addition: Warning message:
In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'**

I don't know what I am doing wrong. Please resolve

**Comment by kassambara** [comment]
Hi,

Please install the latest version from Github:

```r
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/survminer", build_vignettes = FALSE)
```

Best,
/A

**Comment by akhats** [comment]
I did but now it is giving me different kind or errors:

**Error: lazy-load database '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/survminer/R/survminer.rdb' is corrupt
In addition: Warning messages:
1: restarting interrupted promise evaluation 
2: internal error -2 in R_decompress1**

Thanks

**Comment by kassambara** [comment]
Hi,

This error is not reproducible on my computer. Have you considered restarting your R session before installation?

**Comment by akhats** [comment]
Thanks it did work after the restart. No just gives me a warning:

 **TEXT_SHOW_BACKTRACE environmental variable.**

**Comment by kassambara** [comment]
Great!! so we can close this issue!
Best,
/A
