### ISSUE TITLE
survminer broke on CRAN

### ISSUE THREAD

**Issue by MarcinKosinski** [kassambara/survminer#87]
ftp://ftp.oregonstate.edu/.1/cran/web/checks/check_results_survminer.html

**Comment by MarcinKosinski** [comment]
https://cran.rstudio.com/web/checks/check_results_survminer.html
probably due to #86

**Comment by MarcinKosinski** [comment]
I think this might have happen due to new ggplot2 ver 2.2.0 https://github.com/tidyverse/ggplot2/blob/master/revdep/README.md

**Comment by kassambara** [comment]
yes, it's due to ggplot2 ver 2.2.0. The github version of survminer is compatible with ggplot2 v2.2.0. Survminer 0.2.3 Should be released on CRAN this weekend.

Best,
/A

**Comment by MarcinKosinski** [comment]
Thank you @kassambara  :) keep going with this project. Are you planning to maybe show `surminer` on user2017?

**Comment by kassambara** [comment]
survminer 0.2.3 on CRAN now https://cran.r-project.org/web/packages/survminer/
staticdocs updated: http://www.sthda.com/english/rpkgs/survminer/

CRAN takes few more days (1 - 2 days) to  update the online check results and to build the package binaries.

**Comment by MarcinKosinski** [comment]
Thanks, good job. I've seen that for some platforms cran reports version 0.2.2 and for some 0.2.3 :) https://cran.rstudio.com/web/checks/check_results_survminer.html

Have you moved from staticdocs to pkgdown :)? It looks cooler now

**Comment by kassambara** [comment]
Yep!! it's no longer possible to install staticdocs... Hadley replaces it with pkgdown, which output is better than and it is more flexible for customization compared to staticdocs...

**Comment by MarcinKosinski** [comment]
It is possible if you have local binary like me ^^ but pkgdown are really
better!

2016-12-07 17:50 GMT+01:00 Alboukadel KASSAMBARA <notifications@github.com>:
