### ISSUE TITLE
releasing survminer 0.2.4

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#94]
Hi @MarcinKosinski,

Major bugs have been detected in survminer 0.2.3 (https://github.com/kassambara/survminer/blob/master/NEWS.md). I think that we should submit survminer 0.2.4 to CRAN as soon as possible  even if the CRAN policy suggests a new version once every 1-2 months at most.

What do you think about that?

**Comment by kassambara** [comment]
survminer 0.2.4 on CRAN now: https://cran.r-project.org/web/packages/survminer/

**Comment by MarcinKosinski** [comment]
Thank you for the update :) I don't have to change RTCGA code. Good job!
