### ISSUE TITLE
Number at risk and number censored in the same table

### ISSUE THREAD

**Issue by kassambara** [kassambara/survminer#96]
In this lancet article ([Prediction of overall survival for patients with metastatic castration-resistant prostate cancer: development of a prognostic model through a crowdsourced challenge with open clinical trial data - The Lancet Oncology](http://www.thelancet.com/pdfs/journals/lanonc/PIIS1470-2045(16)30560-5.pdf)), the authors put the number at risk and the number censored in the same table below the survival curves.

![2016-12-13_1207](https://cloud.githubusercontent.com/assets/3313355/21138167/22346b1c-c12d-11e6-9796-ab931936989a.png)

This could be an alternative option to the ncensor.plot generated by the current version of ggsurvplot()

**Comment by MarcinKosinski** [comment]
Here I see it's done http://www.sthda.com/english/wiki/survminer-0-2-4

**Comment by kassambara** [comment]
It looks like, but this was an answer to the issue #70, where the user asks for the absolute number and the percentage of subjects at risk in the same table.

**Comment by kassambara** [comment]
Now, `ggsurvplot()` can display both the number at risk and the cumulative number of censored in the same table using the option `risk.table = 'nrisk_cumcenor'` ([#96](https://github.com/kassambara/survminer/issues/96)). It's also possible to display the number at risk and the cumulative number of events using the option `risk.table = 'nrisk_cumevents'`

```r
# Fit survival curves
library(survival)
fit <- survfit( Surv(time, status) ~ sex, data = lung )

# Plot 
library(survminer)
ggsurvplot(fit, data = lung,
           risk.table = "nrisk_cumcensor",
           palette = "jco",
           tables.height = 0.2, 
           tables.y.text = FALSE, 
           tables.theme = theme_cleantable()
)
```

![rplot13](https://cloud.githubusercontent.com/assets/3313355/23447195/8edcc9cc-fe49-11e6-8e21-f541f6ab0910.png)
